export enum InputCellCommand {
  CLEAR = 'CLEAR',
  REVEAL = 'REVEAL',
  CHECK = 'CHECK',
  SWITCH_MODE_TO_SINGLE = 'SWITCH_MODE_TO_SINGLE',
  SWITCH_MODE_TO_UNLIMITED = 'SWITCH_MODE_TO_UNLIMITED',
  NOOP = 'NOOP',
}
