export const rawNounsForms = `das Abendessen;Die Abendessen;Dinner;4;kolacja
das Abenteuer;Die Abenteuer;Adventure;4;Przygoda
das Abzeichen;Die Abzeichen;Badge;4;Odznaka
das Ahorn;Die Ahorne;Maple;2;Klon
das Alter;Das Alter;Age;2;wiek
das Angebot;Die Angebote;Offer;3;Oferta
das Armband;Die Armbänder;Bracelet;3;Bransoletka
das Arschloch;Die Arschlöcher;Asshole;4;Dupek
das Artefakt;Die Artefakte;Artifact;4;Artefakt
das Aspekt;Die Aspekte;Aspect;3;Aspekt
das Auge;Die Augen;Eye;1;oko
das Augenlid;Die Augenlider;Eyelid;4;Powieka
das Ausmaß;Die Ausmaße;Extent;3;Zakres
das Bad;Die Bäder;Bath;1;kąpiel
das Band;Die Bänder;Tape;1;Taśma
das Bauernhaus;Die Bauernhäuser;Farmhouse;4;Dom wiejski
das Becken;Die Becken;Basin;3;Basen
das Bedürfnis;Die Bedürfnisse;Need;4;Potrzebować
das Begräbnis;Die Begräbnisse;Funeral;4;Pogrzeb
das Bein;Die Beine;Leg;1;noga
das Beispiel;Die Beispiele;Example;4;przykład
das Bericht;Die Berichte;Report;3;Raport
das Bett;Die Betten;Bed;1;łóżko
das Bewusstsein;Die Bewussts;Consciousness;4;Świadomość
das Bier;Die Biere;Beer;1;piwo
das Bild;Die Bilder;Picture;1;obraz
das Blatt;Die Blätter;Leaf;2;Liść
das Blaue;Der Blues;Blue;2;Niebieski
das Blut;Die Blut;Blood;1;krew
das Boot;Die Boote;Boat;1;łódź
das Brett;Die Bretter;Plank;2;Deska
das Buch;Die Bücher;Book;1;książka
das Bündel;Die Bündel;Bundle;3;plik czegoś
das Büro;Die Büros;Office;1;biuro
das Dach;Die Dächer;Roof;1;dach
das Datum;Die Daten;Date;2;data
das Ding;Die Dinge;Thing;1;Rzecz
das Dokument;Die Dokumente;Document;4;Dokument
das Dorf;Die Dörfer;Village;1;wieś
das Dreieck;Die Dreiecke;Triangle;3;Trójkąt
das Dunkel;Die Dunkel;Gloom;3;Mrok
das Ei;Die Eier;Egg;1;jajo
das Eichhörnchen;Die Eichhörnchen;Squirrel;4;Wiewiórka
das Einkaufen;Die Einkäufe;Shopping;4;Zakupy
das Einkommen;Die Einkommen;Income;4;Dochód
das Elend;Das Elend;Misery;2;Nieszczęście
das Elternteil;Die Eltern;Parent;4;Rodzic
das Ende;Die Enden;End;1;koniec
das Englisch;Die Englishes;English;4;język angielski
das Erdbeben;Die Erdbeben;Earthquake;4;Trzęsienie ziemi
das Ereignis;Die Events;Event;4;Wydarzenie
das Ergebnis;Die Ergebnisse;Result;4;Wynik
das Erlebnis;Die Erlebnisse;Experience;4;Doświadczenie
das Essen;Die Eatings;Eating;2;Jedzenie
das Etikett;Die Etiketten;Label;3;Etykieta
das Fahrrad;Die Fahrräder;Bike;3;rower
das Fahrzeug;Die Fahrzeuge;Vehicle;4;Pojazd
das Feld;Die Felder;Field;1;Pole
das Fell;Die Felle;Fur;1;Futro
das Fenster;Die Fenster;Window;3;okno
das Fernsehen;Die Fernseher;Television;4;Telewizja
das Fest;Die Feste;Festival;1;Festiwal
das Festmahl;Die Feste;Feast;4;Święto
das Fett;Die Fette;Fat;1;Gruby
das Feuer;Die Feuer;Fire;2;ogień
das Feuerzeug;Die Feuerzeuge;Lighter;4;zapalniczka
das Fieber;Die Fieber;Fever;3;Gorączka
das Fitnesscenter;Die FitnessStudios;Gym;4;siłownia
das Fleisch;Das Fleisch;Meat;3;mięso
das Flimmern;Die Flackert;Flicker;4;Migotanie
das Floß;Die Flöße;Raft;1;Tratwa
das Flugzeug;Die Flugzeuge;Plane;4;samolot
das Flüstern;Das Flüstern;Whisper;4;Szept
das Foto;Die Fotos;Photo;1;Zdjęcie
das Frühstück;Das Frühstück;Breakfast;4;śniadanie
das Gasthaus;Die Gasthöfe;Inn;4;Zajazd
das Gebet;Die Gebete;Prayer;2;Modlitwa
das Gebäude;Die Gebäude;Building;3;budynek
das Gedicht;Die Gedichte;Poem;3;Wiersz
das Gefrier;Die Gefrier;Freezer;3;Zamrażarka
das Gefängnis;Die Gefängnisse;Prison;4;Więzienie
das Gefäss;Die Gläser;Jar;3;Słoik
das Gefühl;Die Gefühle;Feeling;3;Uczucie
das Gehalt;Die Gehälter;Salary;3;Pensja
das Geheimnis;Die Geheimnisse;Secret;4;Sekret
das Gehirn;Die Gehirne;Brain;3;mózg
das Geld;Die Gelder;Money;1;pieniądze
das Gelächter;Die Gelächter;Laughter;4;Śmiech
das Geländer;Die Geländer;Railing;4;Balustrada
das Gemälde;Die Gemälde;Painting;3;malunek
das Gemüse;Das Gemüse;Vegetable;3;Warzywo
das Gen;Die Gene;Gene;1;Gen
das Genie;Die Genies;Genius;2;Geniusz
das Gepäck;Die Gepäck;Luggage;3;bagaż
das Gericht;Die Gerichte;Court;3;Sąd
das Gerichtsgebäude;Die Gerichtsgebäuden;Courthouse;4;Budynek sądu
das Geräusch;Die Geräusche;Noise;4;Hałas
das Gerücht;Die Gerüchte;Rumor;3;Plotka
das Geschenk;Die Geschenke;Gift;4;prezent
das Gesetz;Die Gesetze;Law;3;Ustawa
das Gesicht;Die Gesichter;Face;3;twarz
das Gespenst;Die Geister;Ghost;4;Duch
das Gespräch;Die Gespräche;Talk;4;Rozmowa
das Getränk;Die Getränke;Drink;3;napój
das Gewebe;Die Gewebe;Tissue;3;Papierowa chusteczka
das Gewehr;Die Gewehre;Rifle;3;karabin
das Gewicht;Die Gewichte;Weight;3;Waga
das Gewissen;Das Gewissen;Conscience;4;Sumienie
das Gift;Die Gifte;Poison;1;Zatruć
das Glück;Die Glück;Fortune;2;szczęście
das Glühen;Die Glüht;Glow;3;Blask
das Grab;Die Gräber;Grave;1;Mogiła
das Gras;Die Gräser;Grass;1;trawa
das Grinsen;Die Grins;Grin;3;Szeroki uśmiech
das Grunzen;Das Grunzen;Grunt;3;Chrząknięcie
das Grün;Die Grünen;Green;1;Zielony
das Gute;Die Güter;Good;1;Dobry
das Gänseblümchen;Das Gänseblümchen;Daisy;4;Stokrotka
das Haar;Die Haare;Hair;1;włos
das Handgelenk;Die Handgelenke;Wrist;4;Nadgarstek
das Handtuch;Die Handtücher;Towel;4;Ręcznik
das Handwerk;Das Handwerk;Craft;4;Rękodzieło
das Hauptquartier;Die Headquarterses;Headquarters;4;Siedziba
das Haus;Die Häuser;House;1;dom
das Haustier;Die Haustiere;Pet;4;Zwierzak domowy
das Heck;Die Hecks;Stern;1;rufa
das Hemd;Die Hemden;Shirt;1;koszula
das Herrenhaus;Die Herrenhäuser;Manor;4;Dwór
das Herz;Die Herzen;Heart;1;serce
das Heulen;Das Heulen;Howl;3;Wycie
das Hinken;Die Hinkt;Limp;3;Utykać
das Huhn;Die Hühner;Chicken;1;kurczak
das Insekt;Die Insekten;Insect;3;Owad
das Institut;Die Institute;Institute;4;Instytut
das Intervall;Die Intervalle;Interval;4;Interwał
das Jahr;Die Jahre;Year;1;rok
das Jahrhundert;Die Jahrhunderte;Century;4;stulecie
das Jahrzehnt;Die Jahrzehnte;Decade;4;Dekada
das Juwel;Die Juwelen;Jewel;2;Klejnot
das Kabel;Die Kabel;Cable;2;Kabel
das Kalb;Die Kälber;Calf;1;cielak
das Kamel;Die Kamele;Camel;2;Wielbłąd
das Kanu;Die Kanus;Canoe;1;Kajak
das Kapitel;Die Kapitel;Chapter;3;Rozdział
das Keuchen;Die Keuchen;Gasp;3;Łapanie tchu
das Kind;Die Kinder;Child;1;dziecko
das Kinderbett;Die Kinderbetten;Cot;4;Łóżko składane
das Kinn;Die Kinne;Chin;1;podbródek
das Kissen;Die Kissen;Pillow;3;Poduszka
das Klassenzimmer;Die Klassenzimmer;Classroom;4;sala, klasa
das Klavier;Die Klaviere;Piano;3;Fortepian
das Kleid;Die Kleider;Dress;2;sukienka
das Kleidungsstück;Die Kleidungsstücke;Garment;4;Część garderoby
das Knie;Die Knie;Knee;1;kolano
das Kompliment;Die Komplimente;Compliment;4;Komplement
das Kongress;Die Kongresse;Congress;4;Kongres
das Konzept;Die Konzepte;Concept;3;Pojęcie
das Konzert;Die Konzerte;Concert;3;Koncert
das Korn;Die Körner;Grain;1;Ziarno
das Kostüm;Die Kostüme;Costume;3;Kostium
das Krankenhaus;Die Krankenhäuser;Hospital;4;szpital
das Kraut;Die Kräuter;Herb;2;Ziele
das Kreuz;Die Kreuze;Cross;2;Krzyż
das Kupfer;Die Kupfer;Copper;3;Miedź
das Kätzchen;Die Kätzchen;Kitten;4;Kotek
das Königreich;Die Königreiche;Kingdom;4;Królestwo
das Küken;Die Küken;Chick;2;Pisklę
das Labor;Die Labore;Lab;2;Laboratorium
das Labyrinth;Die Labyrinthe;Maze;4;Labirynt
das Lachen;Die Lachen;Laugh;3;uśmiech
das Lamm;Die Lämmer;Lamb;1;owieczka
das Land;Die Länder;Country;1;kraj
das Leben;Die Leben;Life;2;życie
das Lebensmittel;Die Lebensmittel;Grocery;4;Sklep spożywczy
das Leder;Die Leder;Leather;2;materiał skóra
das Lehren;Die Lehren;Teaching;3;Nauczanie
das Leiden;Die Leiden;Suffering;3;Cierpienie
das Licht;Die Lichter;Light;2;swiatło
das Liebesspiel;Die Lovemakings;Lovemaking;4;Uprawianie miłości
das Lied;Die Lieder;Song;1;Utwór muzyczny
das Lob;Das Lob;Praise;1;Pochwała
das Loch;Die Löcher;Hole;1;dziura
das Los;Die Lose;Lot;1;Działka
das Lächeln;Die Lächeln;Smile;3;Uśmiechnij się
das Maultier;Die Maultiere;Mule;4;Muł
das Meer;Die Meere;Sea;1;morze
das Mehl;Die Mehle;Flour;1;Mąka
das Menü;Die Menüs;Menu;1;Menu
das Messer;Die Messer;Knife;3;nóż
das Metall;Die Metalle;Metal;3;metal
das Mikrofon;Die Mikrofone;Microphone;4;Mikrofon
das Mittagessen;Die Mittagessen;Lunch;4;obiad
das Mondlicht;Die Mondlicht;Moonlight;4;światło księżyca
das Moos;Die Moose;Moss;1;Mech
das Motiv;Die Motive;Motive;2;Motyw
das Motorrad;Die Motorräder;Motorcycle;4;Motocykl
das Murmeln;Das Murmeln;Murmur;3;Szmer
das Muster;Die Muster;Pattern;3;Wzór
das Mädchen;Die Mädchen;Girl;3;dziewczynka
das Nachthemd;Die Nachthemden;Nightgown;4;Koszula nocna
das Nasenloch;Die Nasenlöcher;Nostril;4;Nozdrze
das Netzwerk;Die Netzwerke;Network;4;Sieć
das Objekt;Die Objekte;Object;3;Obiekt
das Ohr;Die Ohren;Ear;1;ucho
das Opfer;Die Opfer;Victim;2;Ofiara
das Paar;Die Paare;Pair;1;para
das Paket;Die Pakete;Package;2;paczka
das Paradies;Die Paradiese;Paradise;4;raj
das Personal;Die Personnels;Personnel;4;Personel
das Pferd;Die Pferde;Horse;2;koń
das Pflaster;Die Pflaster;Plaster;4;Gips
das Pfund;Die Pfunde;Pound;2;Funt
das Phänomen;Die Phänomene;Phenomenon;4;Zjawisko
das Picknick;Die Picknicks;Picnic;4;Piknik
das Plakat;Die Poster;Poster;3;Plakat
das Porträt;Die Porträts;Portrait;3;Portret
das Produkt;Die Produkte;Product;3;Produkt
das Profil;Die Profile;Profile;3;Profil
das Programm;Die Programme;Program;4;Program
das Publikum;Das Publikum;Audience;4;Publiczność
das Pulver;Die Pulver;Powder;3;Proszek
das Quadrat;Die Quadrate;Square;3;Kwadrat
das Rad;Die Räder;Wheel;1;koło
das Rasiermesser;Die Rasierer;Razor;4;Brzytwa
das Recht;Die Rechte;Right;2;prawo
das Regal;Die Regale;Shelf;2;regał
das Reich;Die Reiche;Empire;2;Imperium
das Rennen;Die Rennen;Race;3;Wyścigi
das Rezept;Die Rezepte;Recipe;3;Przepis
das Rindfleisch;Die Rindfleische;Beef;4;wołowina
das Risiko;Die Risiken;Risk;3;Ryzyko
das Rohr;Die Röhren;Pipe;1;Rura
das Rotkehlchen;Die Rotkehlchen;Robin;4;Rudzik
das Salz;Die Salze;Salt;1;sól
das Schaf;Die Schafe;Sheep;2;Owce
das Scharnier;Die Scharniere;Hinge;4;Zawias
das Schicksal;Die Schicksale;Fate;4;Los
das Schiff;Die Schiffe;Ship;3;statek
das Schlafzimmer;Die Schlafzimmer;Bedroom;4;sypialnia
das Schlagen;Die Schläge;Beating;4;Bicie
das Schließfach;Die Schließfächer;Locker;4;Szafka
das Schloss;Die Schlösser;Lock;3;Zamek
das Schlurfen;Die Shufflings;Shuffling;4;Shuffling.
das Schnäppchen;Die Schnäppchen;Bargain;4;Okazja
das Schreiben;Die Schriften;Writing;4;Pismo
das Schwein;Die Schweine;Pig;3;świnia
das Schwert;Die Schwerter;Sword;3;Miecz
das Schwimmen;Die Swimming;Swimming;4;Pływanie
das Segel;Die Segel;Sail;2;Żagiel
das Seil;Die Seile;Rope;1;lina
das Silber;Die Silber;Silver;3;srebro
das Skelett;Die Skelette;Skeleton;3;Szkielet
das Sonnenlicht;Die Sunlights;Sunlight;4;Światło słoneczne
das Spannfutter;Die Spann;Chuck;4;Gdakanie
das Speicher;Die Speicher;Storage;4;Składowanie
das Spiel;Die Spiele;Game;2;Gra
das Spielzeug;Die Spielzeuge;Toy;4;Zabawka
das Sprichwort;Die Sprüche;Saying;4;Powiedzenie
das Staub;Die Stäube;Dust;2;Pył
das Stirnrunzeln;Die Stirn Runzelt;Frown;4;Marszczyć brwi
das Stöhnen;Das Stöhnen;Groan;3;Jęk
das Stück;Die Stücke;Piece;2;kawałek
das Szenario;Die Szenarien;Scenario;4;Scenariusz
das Tagebuch;Die Tagebücher;Diary;4;Dziennik
das Tal;Die Täler;Valley;1;Dolina
das Taschentuch;Die Taschentücher;Handkerchief;4;chusteczka
das Telefon;Die Telefone;Phone;3;telefon
das Teleskop;Die Teleskope;Telescope;4;Teleskop
das Thema;Die Themen;Topic;2;Temat
das Tier;Die Tiere;Animal;1;zwierze
das Treppenhaus;Die Treppenhäuser;Staircase;4;Klatka schodowa
das Trikot;Die Trikots;Jersey;3;Golf
das Unbehagen;Die Unbehagen;Discomfort;4;Dyskomfort
das Universum;Die Universen;Universe;4;Wszechświat
das Unkraut;Das Unkraut;Weed;3;Chwast
das Unternehmen;Die Unternehmen;Enterprise;4;Przedsiębiorstwo
das Urteil;Die Urteile;Judgment;3;Osąd
das Verbrechen;Die Verbrechen;Crime;4;przestępstwo
das Verfahren;Die Verfahren;Procedure;4;Procedura
das Verhalten;Die Verhalten;Behavior;4;Zachowanie
das Versprechen;Die Versprechen;Promise;4;Obietnica
das Vertrauen;Die Vertrauen;Confidence;4;Zaufanie
das Viertel;Die Viertel;Quarter;3;Jedna czwarta
das Violett;Die Veilchen;Violet;3;Fioletowy
das Volk;Die Völker;People;1;Ludzie
das Volumen;Die Volumina;Volume;3;Tom
das Wachs;Die Wachse;Wax;2;Wosk
das Wachstum;Die Wachstum;Growth;4;Wzrost
das Wandern;Die Wandern;Walk;3;Spacerować
das Warten;Die Warten;Wait;3;Czekać
das Waschbecken;Die Waschbecken;Sink;4;Tonąć
das Wasser;Die Wasser;Water;3;woda
das Weibchen;Die Weibchen;Female;4;Płeć żeńska
das Weihnachtslied;Die Weihnachtslieder;Carol;4;kolęda
das Weiß;Die Weißen;White;1;biały
das Werkzeug;Die Werkzeuge;Tool;4;Narzędzie
das Wetter;Die Wetter;Weather;3;pogoda
das Willkommen;Die Willkommen;Welcome;4;Witamy
das Wochenende;Die Wochenenden;Weekend;4;Weekend
das Wohl;Die Willen;Sake;1;Wzgląd
das Wort;Die Worte;Word;1;słowo
das Wrack;Die Wracks;Wreck;2;Wrak
das Wunder;Die Wunder;Wonder;3;Zastanawiać się
das Wörterbuch;Die Wörterbücher;Dictionary;4;słownik
das Zelt;Die Zelte;Tent;1;Namiot
das Zentrum;Die Zentren;Center;3;centrum
das Zeugnis;Die Zeugnisse;Testimony;3;Świadectwo
das Ziel;Die Ziele;Target;1;cel
das Zifferblatt;Die Zifferblätter;Dial;4;Wybierz
das Zischen;Die Zischt;Hiss;3;Syk
das Zittern;Die Zittern;Shiver;3;Dreszcz
das Zusammentreffen;Die Zufälle;Coincidence;4;Zbieg okoliczności
das Öl;Die Öle;Oil;1;olej
der Abend;Die Abende;Evening;2;wieczór
der Abstieg;Die Abfahrten;Descent;3;Zejście
der Absturz;Die Abstürze;Crash;3;Rozbić się
der Abzug;Die Abzüge;Trigger;2;Cyngiel
der Adler;Die Adler;Eagle;2;Orzeł
der Affe;Die Affen;Monkey;1;Małpa
der Akzent;Die Akzente;Accent;3;Akcent
der Albtraum;Die Alpträume;Nightmare;4;Koszmar
der Alkohol;Die Alkohole;Alcohol;3;alkohol
der Anfang;Die Anfänge;Beginning;3;początek
der Angriff;Die Angriffe;Attack;3;Atak
der Anhänger;Die Anhänger;Trailer;4;Zwiastun filmu
der Anruf;Die Anrufe;Call;2;Połączenie
der Anrufer;Die Anrufer;Caller;3;dzwoniący
der Ansager;Die Ansager;Announcer;3;Spiker
der Ansatz;Die Ansätze;Approach;3;Zbliżać się
der Anspruch;Die Ansprüche;Claim;4;pretensja, roszczenie
der Anstieg;Die Anstiege;Climb;3;Wspiąć się
der Anwalt;Die Anwälte;Lawyer;3;Prawnik
der Anzug;Die Anzüge;Suit;2;garnitur
der Appetit;Die Appetit;Appetite;3;apetyt
der Arbeiter;Die Arbeiter;Worker;4;Pracownik
der Arbeitgeber;Die Arbeitgeber;Employer;4;Pracodawca
der Angestellte;Die Angestellten;Employee;4;zatrudniony
der Artikel;Die Artikel;Article;3;Artykuł
der Aschenbecher;Die Aschenbecher;Ashtray;4;Popielniczka
der Assistent;Die Assistenten;Assistant;4;Asystent
der Atem;Die Atem;Breath;1;Oddech
der Attentäter;Die Attentäter;Assassin;4;Morderca
der Aufenthalt;Die Aufenthalte;Stay;4;Zostać
der Aufgang;Der Anstieg;Rise;3;Podwyżka
der Aufprall;Die Aufpralle;Impact;4;Uderzenie
der Aufsatz;Die Aufsätze;Essay;3;Praca pisemna
der Aufwand;Die Aufwände;Effort;3;Wysiłek
der Aufzug;Die Aufzüge;Elevator;3;Winda
der Ausdruck;Die Ausdrücke;Expression;4;Wyrażenie
der Ausgang;Die Ausgänge;Exit;3;wyjście
der Ausländer;Die Ausländer;Foreigner;4;Cudzoziemiec
der Autor;Die Autoren;Author;2;Autor
der Bach;Die Bäche;Creek;1;zatoczka
der Bademantel;Die Bademäntel;Bathrobe;4;Szlafrok
der Baldachin;Die Baldachine;Canopy;4;Daszek
der Balkon;Die Balkone;Balcony;3;Balkon
der Ballon;Die Ballons;Balloon;3;Balon
der Barbier;Die Barbiere;Barber;3;Fryzjer
der Barkeeper;Die Barkeeper;Bartender;4;Barman
der Bart;Die Bärte;Beard;1;broda
der Bauch;Die Bäuche;Belly;2;Brzuch
der Bauer;Die Bauern;Farmer;2;Rolnik
der Bauernhof;Die Bauernhöfe;Farm;4;gospodarstwo rolne
der Baum;Die Bäume;Tree;1;drzewo
der Becher;Die Becher;Mug;3;Kubek
der Befehl;Die Befehle;Command;3;Komenda
der Begriff;Die Begriffe;Term;3;Semestr
der Bereich;Die Bereiche;Range;3;Zasięg
der Berg;Die Berge;Mountain;1;góra
der Bergmann;Die Bergleute;Miner;4;Górnik
der Beruf;Die Berufe;Profession;2;Zawód
der Besen;Die Besen;Broom;2;miotła
der Besuch;Die Besuche;Visit;3;Odwiedzać
der Besucher;Die Besucher;Visitor;4;odwiedzający
der Beton;Die Betone;Concrete;2;Beton
der Betreiber;Die Betreiber;Operator;4;Operator
der Beweis;Die Beweise;Evidence;3;Dowód
der Bewohner;Die Bewohner;Resident;4;Mieszkaniec
der Bischof;Die Bischöfe;Bishop;3;Biskup
der Biss;Die Bisse;Bite;1;Ugryzienie
der Blick;Die Blicke;Gaze;2;Spojrzenie
der Blitz;Die Blitze;Flash;2;Lampa błyskowa
der Bluterguss;Die Blutergüsse;Bruise;4;Siniak
der Boden;Die Böden;Floor;2;ziemia
der Bogen;Die Bögen;Bow;2;Kokarda
der Bogenschütze;Die Bogenschützen;Archer;4;Łucznik
der Bohrer;Die Bohrer;Drill;3;Wiertarka
der Bolzen;Die Bolzen;Bolt;3;Śruba
der Bote;Die Boten;Messenger;1;Posłaniec
der Botschafter;Die Botschafter;Ambassador;4;Ambasador
der Brief;Die Briefe;Letter;2;list
der Bruder;Die Brüder;Brother;3;brat
der Brunnen;Die Brunnen;Fountain;3;studnia
der Bulle;Die Bullen;Bull;2;Byk
der Busch;Die Büsche;Bush;2;Krzak
der Bäcker;Die Bäcker;Baker;3;piekarz
der Bär;Die Bären;Bear;1;niedźwiedź
der Bücherladen;Die Bücherladen;Bookstore;4;Księgarnia
der Büffel;Die Büffel;Buffalo;3;Bawół
der Bürger;Die Bürger;Citizen;3;Obywatel
der Bürgermeister;Die Bürgermeister;Mayor;4;Burmistrz
der Bürgersteig;Die Bürgersteige;Sidewalk;4;Chodnik
der Champagner;Die Champagner;Champagne;4;szampan
der Charakter;Die Charaktere;Character;4;Postać
der Chirurg;Die Chirurgen;Surgeon;3;Chirurg
der Chor;Die Chöre;Chorus;1;Chór
der Dachboden;Die Dachböden;Attic;4;Strych
der Damm;Die Dämme;Dam;1;Zapora
der Dampf;Die Dämpfe;Steam;2;Parowy
der Datensatz;Die Datensätze;Record;4;Nagrywać
der Daumen;Die Daumen;Thumb;3;kciuk
der Deckel;Die Deckel;Lid;3;Pokrywa
der Dekan;Die Dekane;Dean;2;Dziekan
der Delfin;Die Delphine;Dolphin;3;Delfin
der Detektiv;Die Detektive;Detective;4;Detektyw
der Deutsche;Die Deutschen;German;4;Niemiecki
der Diakon;Die Diakone;Deacon;3;Diakon
der Dialog;Die Dialoge;Dialogue;3;Dialog
der Diamant;Die Diamanten;Diamond;3;Diament
der Dieb;Die Diebe;Thief;1;Złodziej
der Diener;Die Diener;Servant;3;Sługa
der Dinosaurier;Die Dinosaurier;Dinosaur;4;Dinozaur
der Direktor;Die Direktoren;Director;4;Dyrektor
der Doktor;Die Doktoren;Doctor;3;Lekarz
der Dolch;Die Dolche;Dagger;2;Sztylet
der Donner;Der Donner;Thunder;3;grzmot
der Doppelgänger;Die Doppelgänger;Double;4;Podwójnie
der Dorfbewohner;Die Dorfbewohner;Villager;4;Wieśniak
der Dorn;Die Dornen;Thorn;1;Cierń
der Drache;Die Drachen;Dragon;3;smok
der Dreck;Die Dirts;Dirt;2;Brud
der Druck;Die Drücke;Pressure;2;Nacisk
der Dschungel;Die Dschungel;Jungle;4;Dżungla
der Duft;Die Düfte;Scent;1;aromat, woń
der Durchgang;Die Durchgänge;Passage;4;Przejście
der Dämon;Die Dämonen;Demon;2;Demon
der Efeu;Die Efeu;Ivy;1;Bluszcz
der Effekt;Die Effekte;Effect;3;Efekt
der Ehemann;Die Ehemänner;Husband;3;mąż
der Eimer;Die Eimer;Bucket;2;Wiaderko
der Eindringling;Die Eindringlinge;Intruder;4;Intruz
der Eindruck;Die Eindrücke;Impression;4;Wrażenie
der Eine;Die Einen;One;1;Jeden
der Einfluss;Die Einflüsse;Influence;4;Wpływ
der Einheimische;Die Eingeborenen;Native;4;Rodzinny
der Einsatz;Die Einsätze;Stake;3;Stawka
der Eintopf;Die Eintöpfe;Stew;3;Gulasz
der Eintritt;Die Einträge;Entry;4;Wejście
der Einwand;Die Einwände;Objection;3;Sprzeciw
der Ekel;Die Ekelt;Disgust;1;Niesmak
der Elefant;Die Elefanten;Elephant;3;słoń
der Ellbogen;Die Ellbogen;Elbow;4;łokieć
der Empfänger;Die Empfänger;Receiver;4;Odbiorca
der Engel;Die Engel;Angel;2;Anioł
der Enkel;Die Enkel;Grandchild;2;Wnuczkek
der Entwurf;Die Entwürfe;Draft;3;Projekt
der Erbe;Die Erben;Heir;1;Dziedzic
der Erfolg;Die Erfolge;Success;3;Powodzenie
der Ermittler;Die Ermittler;Investigator;4;Badacz
der Erwachsene;Die Erwachsenen;GrownUp;4;Dorosły
der Erzähler;Die Erzähler;Narrator;4;Narrator
der Esel;Die Esel;Ass;1;osioł
der Experte;Die Experten;Expert;3;Ekspert
der Faden;Die Fäden;Thread;2;nić
der Fahrer;Die Fahrer;Driver;3;Kierowca
der Faktor;Die Faktoren;Factor;3;Czynnik
der Fall;Die Fälle;Case;1;przypadek
der Fang;Die Fänge;Catch;1;Łapać
der Farbton;Die Farbtöne;Hue;3;barwa
der Favorit;Die Favoriten;Favorite;3;Ulubiony
der Fehler;Die Fehler;Mistake;3;błąd
der Feier;Die Feiern;Celebration;2;Uroczystość
der Feigling;Die Feiglinge;Coward;4;tchórz
der Feind;Die Feinde;Enemy;2;wróg
der Fingernagel;Die Fingernägel;Fingernail;4;Paznokieć
der Fisch;Die Fische;Fish;2;Ryba
der Fischer;Die Fischer;Fisherman;3;Rybak
der Fleck;Die Flecken;Stain;2;Plama
der Fluch;Die Flüche;Curse;2;Przekleństwo
der Flug;Die Flüge;Flight;1;Lot
der Flughafen;Die Flughäfen;Airport;4;lotnisko
der Flur;Die Flure;Hallway;1;Korytarz
der Fluss;Die Flüsse;River;2;rzeka
der Flüchtling;Die Flüchtlinge;Refugee;4;Uchodźca
der Flügel;Die Flügel;Wing;3;Skrzydło
der Fortschritt;Die Fortschritte;Progress;4;Postęp
der Fotograf;Die Fotografen;Photographer;4;Fotograf
der Fremde;Die Fremden;Stranger;3;Nieznajomy
der Freund;Die Freunde;Friend;3;przyjacieł
der Friedhof;Die Friedhöfe;Cemetery;4;Cmentarz
der Frosch;Die Frösche;Frog;3;Żaba
der Frühling;Die Federn;Spring;4;wiosna
der Fuchs;Die Foxs;Fox;2;lis
der Fuhrmann;Die Fuhr;Carter;4;Furman
der Funke;Die Funken;Spark;2;Iskra
der Fuß;Die Füße;Foot;1;Stopa
der Fußball;Die Fußbälle;Football;3;Piłka nożna
der Führer;Die Führer;Leader;3;Lider
der Gang;Die Gänge;Aisle;1;Nawa
der Garten;Die Gärten;Garden;3;ogród
der Gast;Die Gäste;Guest;1;Gość
der Gastgeber;Die Gastgeber;Host;4;Gospodarz
der Geburtstag;Die Geburtstage;Birthday;4;urodziny
der Gedanke;Die Gedanken;Thought;3;Myśl
der Gefangene;Die Gefangenen;Prisoner;4;Więzień
der Gegenstand;Die Gegenstände;Item;4;Przedmiot
der Gegner;Die Gegner;Opponent;3;Przeciwnik
der Gehweg;Die Gehwege;Walkway;3;ścieżka
der Geist;Die Gemüter;Mind;2;Umysł
der Geldbeutel;Die Geldbeutel;Purse;4;Portmonetka
der Gelehrte;Die Gelehrten;Scholar;4;Uczony
der Genosse;Die Genossen;Comrade;3;Towarzysz
der Geruch;Die Gerüche;Smell;3;Zapach
der Gesang;Die Gesänge;Singing;3;Śpiewanie
der Geschmack;Die Geschmäcker;Taste;4;Smak
der Gestank;Die Gestank;Stench;3;Smród
der Gewinn;Die Gewinne;Profit;3;Zysk
der Gewinner;Die Gewinner;Winner;4;Zwycięzca
der Glaube;Die Glauben;Faith;3;Wiara
der Gott;Die Götter;God;1;bóg
der Gouverneur;Die Gouverneure;Governor;4;Gubernator
der Graben;Die Gräben;Ditch;3;Rów
der Grad;Die Grade;Degree;1;stopień
der Graf;Die Grafen;Earl;1;Hrabia
der Granit;Die Granite;Granite;3;Granit
der Grat;Die Grate;Ridge;1;Grzbiet
der Grieche;Die Griechen;Greek;3;grecki
der Griff;Die Griffe;Grip;2;Chwyt
der Großvater;Die Großväter;Grandfather;4;Dziadek
der Grund;Die Gründe;Reason;2;powód
der Gurt;Die Gurte;Strap;1;pas
der Gürtel;Die Gürtel;Belt;3;Pasek
der Hafen;Die Häfen;Harbor;2;Port
der Hai;Die Haie;Shark;1;Rekin
der Hain;Die Haine;Grove;1;Gaj
der Haken;Die Haken;Hook;2;Hak
der Hals;Die Hälse;Neck;1;szyja
der Handel;Das Handwerk;Trade;3;Handel
der Handschuh;Die Handschuhe;Glove;4;Rękawica
der Hase;Die Hasen;Rabbit;1;Królik
der Hass;Die Hass;Hatred;1;Nienawiść
der Haushalt;Die Haushalte;Household;4;Gospodarstwo domowe
der Hecht;Die Hechte;Pike;2;Szczupak
der Heilige;Die Heiligen;Saint;3;Święty
der Held;Die Helden;Hero;1;Bohater
der Helm;Die Helme;Helmet;1;Kask
der Herbst;Die Herbste;Autumn;3;jesień
der Herzog;Die Herzöge;Duke;3;Książę
der Herzschlag;Die Herzschläge;Heartbeat;4;Bicie serca
der Himmel;Der Himmel;Sky;3;niebo
der Hinter;Die Hintern;Rear;3;Tył
der Hintergrund;Die Hintergründe;Background;4;Tło
der Hinweis;Die Hinweise;Hint;3;Wskazówka
der Hirte;Die Hirten;Shepherd;2;Pasterz
der Hof;Die Höfe;Courtyard;1;Dziedziniec
der Honig;Die Honige;Honey;2;Miód
der Horizont;Die Horizonte;Horizon;4;Horyzont
der Hubschrauber;Die Hubschrauber;Helicopter;4;Śmigłowiec
der Huf;Die Hufe;Hoof;1;Kopyto
der Hund;Die Hunde;Dog;1;pies
der Hurrikan;Die Hurrikane;Hurricane;4;Huragan
der Hut;Die Hüte;Hat;1;kapelusz
der Händler;Die Händler;Dealer;3;Kupiec
der Hügel;Die Hügel;Hill;2;Wzgórze
der Impuls;Die Impulse;Impulse;3;Impuls
der Ingenieur;Die Ingenieure;Engineer;4;Inżynier
der Ingwer;Die Ingwer;Ginger;3;Imbir
der Inhalt;Die Inhalte;Content;3;Zadowolony
der Innenraum;Die Innenräume;Interior;4;Wnętrze
der Inspektor;Die Inspektoren;Inspector;4;Inspektor
der Instinkt;Die Instinkte;Instinct;4;Instynkt
der Jahrestag;Die Jahrestage;Anniversary;4;Rocznica
der Jasmin;Die Jasmin;Jasmine;3;Jaśmin
der Jäger;Die Jäger;Hunter;2;Łowca
der Kabelbaum;Die Kabelbäume;Harness;4;Uprząż
der Kaffee;Die Kaffee;Coffee;3;kawa
der Kaiser;Die Kaiser;Emperor;3;cesarz
der Kalender;Die Kalender;Calendar;4;Kalendarz
der Kamin;Die Kamine;Fireplace;2;Kominek
der Kamm;Die Kämme;Comb;1;grzebień
der Kampf;Die Kämpfe;Fight;2;Bić się
der Kanal;Die Kanäle;Channel;2;Kanał
der Kandidat;Die Kandidaten;Candidate;4;Kandydat
der Kapitän;Die Kapitäne;Captain;3;Kapitan
der Kauf;Die Käufe;Purchase;1;Zakup
der Keks;Die Kekse;Cookie;1;Ciastko
der Keller;Die Keller;Basement;3;piwnica
der Kellner;Die Kellner;Waiter;3;kelner
der Kerl;Die Kerle;Guy;1;Facet
der Kern;Die Kerne;Core;1;Rdzeń
der Kies;Die Kiese;Gravel;1;Żwir
der Klick;Die Klicks;Click;2;Kliknij
der Klumpen;Die Klumpen;Lump;3;Bryła
der Knochen;Die Knochen;Bone;3;kość
der Knopf;Die Knöpfe;Button;2;guzik
der Knoten;Die Knoten;Knot;3;Węzeł
der Knöchel;Die Knöchel;Ankle;3;kostka
der Koch;Die Köche;Cook;1;kocharz
der Koffer;Die Koffer;Suitcase;3;Walizka
der Kojote;Die Kojoten;Coyote;3;Kojot
der Koks;Die Kokse;Coke;1;Koks
der Kollege;Die Kollegen;Colleague;3;Współpracownik
der Kommandant;Die Kommandeure;Commander;4;Dowódca
der Kommentar;Die Kommentare;Comment;4;Komentarz
der Konflikt;Die Konflikte;Conflict;4;Konflikt
der Kontakt;Die Kontakte;Contact;3;Kontakt
der Kontext;Die Kontexte;Context;3;Kontekst
der Kontinent;Die Kontinente;Continent;4;Kontynent
der Konus;Die Kegel;Cone;2;Stożek
der Kopf;Die Köpfe;Head;1;głowa
der Kopfschmerz;Die Kopfschmerzen;Headache;4;Bół głowy
der Korb;Die Körbe;Basket;1;kosz
der Kragen;Die Kragen;Collar;3;kołnierz
der Kran;Die Kräne;Crane;1;Dźwig
der Krankenwagen;Die Krankenwagen;Ambulance;4;Ambulans
der Krater;Die Krater;Crater;3;Krater
der Krebs;Die Krebs;Cancer;2;Nowotwór
der Kredit;Die Kredite;Credit;3;Kredyt
der Kreis;Die Kreise;Circle;2;okrąg
der Kreislauf;Die Kreisläufe;Cycle;4;Cykl
der Kreuzer;Die Kreuzer;Cruiser;3;Krążownik
der Krieg;Die Kriege;War;2;Wojna
der Krieger;Die Krieger;Warrior;3;Wojownik
der Kristall;Die Kristalle;Crystal;4;Kryształ
der Kritiker;Die Kritiker;Critic;4;Krytyk
der Krug;Die Krüge;Pitcher;1;Dzban
der Kuchen;Die Kuchen;Cake;3;placek
der Kunden;Die Kunden;Customer;3;Klient
der Kunststoff;Die Kunststoff;Plastic;4;Plastikowy
der Kurs;Die Kurse;Course;1;kurs
der Kuss;Die Küsse;Kiss;1;pocałunek
der Käfer;Die Käfer;Beetle;2;Chrząszcz
der Käfig;Die Käfige;Cage;2;Klatka szybowa
der Kämpfer;Die Kämpfer;Fighter;3;zawodnik sportów walki
der Käse;Die Käse;Cheese;1;Ser
der König;Die Könige;King;2;król
der Körper;Die Körper;Body;3;ciało
der Küchenchef;Die Köche;Chef;4;Szef kuchni
der Kühler;Die Kühler;Cooler;3;Chłodnica
der Kühlschrank;Die Kühlschränke;Refrigerator;4;lodówka
der Kürbis;Die Kürbisse;Pumpkin;3;Dynia
der Lachs;Die Lachse;Salmon;2;Łosoś
der Lautsprecher;Die Lautsprecher;Speaker;4;Głośnik
der Lavendel;Die Lavendel;Lavender;4;Lawenda
der Lehrer;Die Lehrer;Teacher;3;nauczyciel
der Leser;Die Leser;Reader;2;Czytelnik
der Leutnant;Die Leutnants;Lieutenant;4;Porucznik
der Liebhaber;Die Liebhaber;Lover;4;Kochanek
der Liebling;Die Lieblinge;Darling;4;kochanie
der Lippenstift;Die Lippenstifte;Lipstick;4;Pomadka
der Lorbeer;Die Lorbeeren;Laurel;3;Laur
der Läufer;Die Läufer;Runner;3;Biegacz
der Löffel;Die Löffel;Spoon;3;łyżka
der Löwe;Die Löwen;Lion;1;Lew
der Lügner;Die Lügner;Liar;3;kłamca
der Macher;Die Macher;Maker;3;Producent
der Magier;Die Magier;Mage;3;Mag
der Maler;Die Maler;Painter;2;Malarz
der Mann;Die Männer;Man;1;mężczyzna
der Mantel;Die Mäntel;Coat;3;płaszcz
der Markt;Die Märkte;Market;2;Rynek
der Marmor;Die Murmeln;Marble;3;Marmur
der Marsch;Die Märsche;March;3;Marsz
der Maulwurf;Die Maulwürfe;Mole;4;Kret
der Maurer;Die Maurer;Mason;3;Mason
der Mechaniker;Die Mechanik;Mechanic;4;Mechanik
der Meister;Die Meister;Master;3;mistrz
der Mensch;Die Menschen;Human;3;człowiek
der Metzger;Die Metzger;Butcher;3;rzeźnik
der Missbrauch;Die Missbräuche;Abuse;4;Nadużywać
der Mitbewohner;Die Mitbewohner;Roommate;4;Współlokator
der Modus;Die Modi;Mode;2;Tryb
der Mohn;Der Mohn;Poppy;1;MAK
der Monat;Die Monate;Month;2;miesiąc
der Mond;Die Monde;Moon;1;księżyc
der Mord;Die Morde;Murder;1;Morderstwo
der Morgen;Die Morgen;Morning;3;ranek
der Motor;Die Motoren;Engine;2;Silnik
der Mund;Die Münder;Mouth;1;usta
der Musiker;Die Musiker;Musician;3;Muzyk
der Muskel;Die Muskeln;Muscle;3;Mięsień
der Mythos;Die Mythen;Myth;3;Mit
der Mönch;Die Mönche;Monk;2;Mnich
der Mörder;Die Mörder;Killer;3;Zabójca
der Müller;Die Müller;Miller;3;Młynarz
der Nachbar;Die Nachbarn;Neighbor;3;sąsiad
der Nachmittag;Die Nachmittage;Afternoon;4;popołudnie
der Nagel;Die Nägel;Nail;2;gwóźdź
der Nebel;Die Nebel;Fog;2;Mgła
der Neffe;Die Neffen;Nephew;2;Siostrzeniec
der Nerv;Die Nerven;Nerve;1;Nerw
der Nervenkitzel;Die Nervenkitzel;Thrill;4;Dreszczyk
der Norden;Die Norths;North;3;północ
der Oberst;Die Obersten;Colonel;3;Pułkownik
der Obstgarten;Die Obstgärten;Orchard;4;sad owocowy
der Offizier;Die Offiziere;Officer;4;Oficer
der Ohrring;Die Ohrringe;Earring;3;Kolczyk
der Onkel;Die Onkel;Uncle;2;wuj
der Ort;Die Orte;Place;1;miejsce
der Ozean;Die Ozeane;Ocean;2;Ocean
der Palast;Die Paläste;Palace;3;Pałac
der Papst;Die Päpste;Pope;2;Papież
der Pass;Die Pässe;Passport;1;paszport
der Passagier;Die Passagiere;Passenger;4;Pasażer
der Passant;Die Passanten;PasserBy;3;Przechodzień
der Pfannkuchen;Die Pfannkuchen;Pancake;4;Naleśnik
der Pfarrer;Die Pastoren;Reverend;3;Czcigodny
der Pfeffer;Die Paprika;Pepper;3;Pieprz
der Pfeil;Die Pfeile;Arrow;2;Strzałka
der Pferdeschwanz;Die Pferdeschwänze;Ponytail;4;Koński ogon
der Pfirsich;Die Pfirsiche;Peach;4;Brzoskwinia
der Pilger;Die Pilger;Pilgrim;3;Pielgrzym
der Pilz;Die Pilze;Mushroom;1;Grzyb
der Pinguin;Die Pinguine;Penguin;3;Pingwin
der Pirat;Die Piraten;Pirate;2;Pirat
der Plattenteller;Die Platten;Platter;4;Talerz
der Platz;Die Plätze;Plaza;2;miejsce do siedzenia
der Pol;Die Pole;Pole;1;Polak
der Politiker;Die Politiker;Politician;4;Polityk
der Polizist;Die Polizisten;Cop;4;Policjant
der Prediger;Die Prediger;Preacher;4;Kaznodzieja
der Preis;Die Preise;Price;2;cena
der Priester;Die Priester;Priest;4;Kapłan
der Privatsphäre;Die Privatsphären;Privacy;4;Prywatność
der Prozess;Die Prozesse;Process;3;Proces
der Präsident;Die Präsidenten;President;4;Prezydent
der Psychiater;Die Psychiater;Psychiatrist;4;Psychiatra
der Pullover;Die Pullover;Sweater;4;Sweter
der Punkt;Die Punkte;Point;2;Punkt
der Rabe;Die Raben;Raven;1;Kruk
der Rahmen;Die Rahmen;Frame;3;Rama
der Rang;Die Reihen;Rank;1;Ranga
der Rasen;Der Rasen;Lawn;2;Trawnik
der Rat;Die Räte;Council;1;rada
der Ratschlag;Die Ratschläge;Advice;4;porada
der Rauch;Die Raucht;Smoke;2;Palić
der Raum;Die Räume;Space;1;Przestrzeń
der Rebell;Die Rebellen;Rebel;3;Buntownik
der Rechtsmittelgrund;Die Rechtsmittelgründe;Plea;4;Zarzut
der Regen;Die Regen;Rain;2;deszcz
der Regenbogen;Die Regenbogen;Rainbow;4;Tęcza
der Reichtum;Die Reichtümer;Wealth;4;Bogactwo
der Reiniger;Die Reiniger;Cleaner;4;Odkurzacz
der Reis;Die Reis;Rice;1;Ryż
der Reisende;Die Reisenden;Traveler;4;Podróżny
der Rhythmus;Die Rhythmen;Rhythm;4;Rytm
der Richter;Die Richter;Judge;3;Sędzia
der Riss;Die Risse;Crack;1;Pękać
der Ritter;Die Ritter;Knight;3;Rycerz
der Roboter;Die Roboter;Robot;3;Robot
der Rock;Die Röcke;Skirt;1;spódnica
der Rollstuhl;Die Rollstühle;Wheelchair;4;Wózek inwalidzki
der Roman;Die Romane;Novel;2;Powieść
der Rubin;Die Rubinen;Ruby;2;Rubin
der Rucksack;Die Rucksäcke;Backpack;4;Plecak
der Ruf;Der Ruf;Reputation;1;Reputacja
der Rumpf;Die Rümpfe;Hull;2;kadłub
der Russe;Die Russen;Russian;2;Rosyjski
der Rücken;Die Rücken;Back;3;plecy
der Rücksitz;Die Rücksitze;Backseat;4;Tylne siedzenie
der Saft;Die Säfte;Juice;1;sok
der Salat;Die Salate;Salad;2;sałatka
der Sarg;Die Särge;Coffin;1;Trumna
der Satellit;Die Satelliten;Satellite;4;Satelita
der Sattel;Die Sättel;Saddle;3;Siodło
der Satz;Die Sätze;Set;1;Ustawić
der Saum;Die Säume;Hem;1;Brzeg
der Schaden;Die Schäden;Damage;3;Szkoda
der Schal;Die Schals;Scarf;2;Szalik
der Schalter;Die Schalter;Switch;4;Przełącznik
der Schatten;Die Schatten;Shadow;4;cień
der Schatz;Die Schätze;Treasure;3;Skarb
der Schaum;Die Schäume;Foam;3;Pianka
der Scheinwerfer;Die Scheinwerfer;Headlight;4;Reflektor
der Schinken;Die Schinken;Ham;4;szynka
der Schlaf;Die Schlaf;Sleep;3;Spać
der Schlag;Die Schläge;Blow;3;Cios
der Schlamm;Die Schlämme;Mud;3;Błoto
der Schlauch;Die Schläuche;Hose;4;Wąż gumowy
der Schleier;Die Schleier;Veil;4;Welon
der Schlepper;Die Schlepper;Tug;4;Holownik
der Schlitz;Die Schlitze;Slot;3;Otwór
der Schläger;Die Schläger;Thug;4;Bandyta
der Schlüssel;Die Schlüssel;Key;4;klucz
der Schmerz;Die Schmerzen;Pain;3;Ból
der Schmetterling;Die Schmetterlinge;Butterfly;4;motyl
der Schmuck;Die Schmuck;Jewelry;3;Biżuteria
der Schnabel;Die Schnäbel;Beak;4;Dziób
der Schnee;Der Schnee;Snow;3;śnieg
der Schnitt;Die Schnitte;Cut;3;Skaleczenie
der Schnittpunkt;Die Schnittpunkte;Intersection;4;Skrzyżowanie
der Schnurrbart;Die Schnurrbärte;Mustache;4;Wąsy
der Schock;Die Schocks;Shock;3;Zaszokować
der Schornstein;Die Schornsteine;Chimney;4;Komin
der Schrank;Die Schränke;Closet;3;szafa
der Schrecken;Die Schrecken;Terror;4;Terror
der Schrei;Die Schreie;Scream;3;Krzyk
der Schreibtisch;Die Schreibtische;Desk;4;Biurko
der Schritt;Die Schritte;Step;3;Krok
der Schuh;Die Schuhe;Shoe;2;but
der Schuppen;Die Schuppen;Shed;4;Szopa
der Schuss;Die Schüsse;Shot;3;Strzał
der Schutz;Die Schutz;Protection;3;Ochrona
der Schwan;Die Schwäne;Swan;3;Łabędź
der Schweif;Die Schwänze;Tail;3;Ogon
der Schwimmer;Die Schwimmer;Float;4;Pływak
der Schädel;Die Schädel;Skull;3;Czaszka
der Schüler;Die Schüler;Pupil;3;Uczeń
der See;Die Seen;Lake;1;jezioro
der Segen;Die Segen;Blessing;2;Błogosławieństwo
der Sekretär;Die Sekretäre;Secretary;4;Sekretarz
der Sessel;Die Sessel;Armchair;3;fotel
der Seufzer;Die Sighes;Sigh;3;Westchnienie
der Sieg;Die Siege;Victory;1;Zwycięstwo
der Sieger;Die Sieger;Victor;3;triumpfator
der Sinn;Die Sinne;Sense;1;Sens
der Smaragd;Die Smaragde;Emerald;3;Szmaragd
der Sohn;Die Söhne;Son;1;syn
der Soldat;Die Soldaten;Soldier;3;Żołnierz
der Sommer;Die Sommer;Summer;3;lato
der Sonnenaufgang;Die Sonnenaufgang;Sunrise;4;wschód słońca
der Sonnenschein;Die Sonne Scheint;Sunshine;4;Światło blask
der Sonnenuntergang;Die Sonne Geht Unter;Sunset;4;Zachód słońca
der Spatz;Die Spatzen;Sparrow;2;Wróbel
der Speck;Die Speck;Bacon;2;słonina
der Speer;Die Speere;Spear;2;Włócznia
der Spiegel;Die Spiegel;Mirror;3;lustro
der Spieler;Die Spieler;Player;3;Gracz
der Spielplatz;Die Spielplätze;Playground;4;Plac zabaw
der Spieß;Die Spieße;Spit;2;Pluć
der Spion;Die Spione;Spy;2;Szpieg
der Spitzname;Die Spitznamen;Nickname;4;Przezwisko
der Spritz;Die Spritzer;Splash;3;Pluśnięcie
der Sprung;Die Sprünge;Jump;3;Skok
der Staat;Die Staaten;State;2;Stan
der Stahl;Die Stähle;Steel;2;stal
der Stamm;Die Stämme;Tribe;2;Plemię
der Stapel;Die Stapel;Stack;3;Stos
der Star;Die Stare;Starling;1;Szpak
der Start;Die Starts;Launch;2;start
der Stein;Die Steine;Stone;2;kamień
der Stern;Die Sterne;Star;2;gwiazda
der Stich;Die Stiche;Pang;2;Ostry ból
der Stift;Die Stifte;Pen;2;Długopis
der Stil;Die Stile;Style;1;Styl
der Stock;Die Stöcke;Stick;2;Kij
der Strahl;Die Strahlen;Ray;3;Promień
der Strand;Die Strände;Beach;3;plaża
der Streifen;Die Streifen;Strip;4;Rozebrać się
der Streik;Die Streiks;Strike;3;Strajk
der Strom;Die Ströme;Stream;2;Strumień
der Strumpf;Die Strümpfe;Stocking;3;Pończocha
der Stuhl;Die Stühle;Chair;2;krzesło
der Stumpf;Die Stümpfe;Stump;3;Kikut
der Stundenplan;Der Spielplan;Schedule;4;Harmonogram
der Sturm;Die Stürme;Storm;2;burza
der Sumpf;Die Sümpfe;Swamp;2;Bagno
der Supermarkt;Die Supermärkte;Supermarket;4;Supermarket
der Sänger;Die Sänger;Singer;3;Piosenkarz
der Süden;Die Souths;South;2;południe
der Tag;Die Tagen;Day;1;dzień
der Tanz;Die Tänze;Dance;1;Taniec
der Techniker;Die Techniker;Technician;4;Technik
der Tee;Die Tees;Tea;1;herbata
der Teich;Die Teiche;Pond;2;Staw
der Teig;Die Teige;Dough;1;Ciasto
der Teil;Die Teile;Part;1;cześć
der Tempel;Die Tempel;Temple;3;Świątynia
der Teppich;Die Teppiche;Carpet;3;dywan
der Termin;Die Termine;Appointment;3;Spotkanie
der Teufel;Die Teufel;Fuck;3;Pierdolić
der Therapeut;Die Therapeuten;Therapist;4;Terapeuta
der Thron;Die Throne;Throne;2;Tron
der Tierarzt;Die Tierärzte;Vet;4;Weterynarz
der Tisch;Die Tische;Table;2;stół
der Tod;Die Tode;Death;1;Śmierć
der Ton;Die Töne;Tone;1;Ton
der Topf;Die Töpfe;Pot;1;garnek
der Trainer;Die Trainer;Coach;3;Trener
der Traktor;Die Traktoren;Tractor;3;Ciągnik
der Traum;Die Träume;Dream;2;sen
der Truthahn;Die Truthähne;Turkey;4;indyk
der Träger;Die Träger;Carrier;3;Przewoźnik
der Turm;Die Türme;Tower;1;wieża
der Typ;Die Typen;Type;1;Rodzaj
der Umfang;Die Umfänge;Perimeter;3;Obwód
der Umhang;Die Umhänge;Cape;3;Peleryna
der Umriss;Die Umrisse;Outline;3;Zarys
der Umschlag;Die Umschläge;Envelope;4;Koperta
der Umstand;Die Umstände;Circumstance;3;Okoliczność
der Unfall;Die Unfälle;Accident;3;wypadek
der Unglaube;Die Unglauben;Disbelief;4;Niedowierzanie
der Unsinn;Die Unsinn;Nonsense;3;Nonsens
der Unterarm;Die Unterarme;Forearm;4;Przedramię
der Unterschied;Die Unterschiede;Difference;4;Różnica
der Urheberrechts;Die Urheberrechte;Copyright;4;prawa autorskie
der Urlaub;Die Urlaub;Vacation;3;Wakacje
der Ursprung;Die Ursprünge;Origin;4;pochodzenie
der Vampir;Die Vampire;Vampire;3;Wampir
der Vater;Die Väter;Father;2;ojciec
der Verband;Die Verbände;Dressing;3;Ubieranie się
der Verbündete;Die Verbündeten;Ally;4;Sprzymierzyć
der Verdacht;Der Verdacht;Suspicion;4;Podejrzenie
der Verdächtige;Die Verdächtigen;Suspect;4;Podejrzany
der Vergleich;Die Vergleiche;Comparison;4;Porównanie
der Vergnügungspark;Die Vergnügungen;Amusement;4;Rozrywka
der Verkauf;Die Verkäufe;Sale;3;Sprzedaż
der Verkehr;Die Verkehre;Traffic;3;Ruch drogowy
der Verlag;Die Verleger;Publisher;3;Wydawca
der Verlierer;Die Verlierer;Loser;4;Nieudacznik
der Verlust;Die Verluste;Loss;3;Strata
der Verrat;Der Verrat;Betrayal;3;Zdrada
der Vers;Die Verse;Verse;1;Werset
der Versuch;Die Versuche;Attempt;3;próba
der Vertrag;Die Verträge;Contract;3;Kontrakt
der Vogel;Die Vögel;Bird;2;ptak
der Vorfahr;Die Vorfahren;Ancestor;3;Przodek
der Vorfall;Die Vorfälle;Incident;3;Incydent
der Vorschlag;Die Vorschläge;Suggestion;4;propozycja
der Vorteil;Die Vorteile;Advantage;3;Korzyść
der Vortrag;Die Vorträge;Lecture;3;Wykład
der Vorwurf;Die Vorwürfe;Accusation;3;Oskarżenie
der Vulkan;Die Vulkane;Volcano;3;Wulkan
der Wagen;Die Wagen;Wagon;2;wóz
der Wal;Die Wale;Whale;1;Wieloryb
der Wald;Die Wälder;Forest;1;las
der Wanderer;Die Wanderer;Walker;4;Piechur
der Wasserhahn;Die Wasserhähne;Tap;4;Uzyskiwać
der Wecker;Die Wecker;Alarm;3;budzik
der Weg;Die Wege;Way;1;droga
der Wein;Die Weine;Wine;1;wino
der Weise;Die Weisen;Sage;2;szałwia
der Weizen;Die Weizen;Wheat;3;Pszenica
der Welpe;Die Welpen;Puppy;2;Szczeniak
der Wert;Die Werte;Value;1;Wartość
der Westen;Die Wests;West;3;zachód
der Wettbewerb;Die Wettbewerbe;Contest;4;Konkurs
der Whisky;Die Whiskys;Whiskey;3;Whisky
der Widerstand;Die Widerstände;Resistance;4;Opór
der Winkel;Die Winkel;Angle;3;Kąt, narożnik
der Wissenschaftler;Die Wissenschaftler;Scientist;4;Naukowiec
der Witz;Die Witze;Joke;1;Żart
der Wodka;Die Wodkas;Vodka;2;wódka
der Wunsch;Die Wünsche;Wish;3;Życzenie
der Wurf;Die Würfe;Litter;1;Śmieci
der Wurm;Die Würmer;Worm;1;Robak
der Wächter;Die Wachen;Guard;3;Strażnik
der Würfel;Die Würfel;Cube;3;Sześcian
der Zahnarzt;Die Zahnärzte;Dentist;4;dentysta
der Zapfen;Die Zapfen;Peg;3;Kołek
der Zauber;Die Zauber;Spell;3;Zaklęcie
der Zauberer;Die Zauberer;Wizard;4;Czarodziej
der Zaun;Die Zäune;Fence;1;Ogrodzenie
der Zaunkönig;Die Zaunkönige;Wren;4;Strzyżyk
der Zeigefinger;Die Zeigefingern;Forefinger;4;Palec wskazujący
der Zement;Die Zemente;Cement;3;Cement
der Zeuge;Die Zeugen;Witness;2;Świadek
der Zigeuner;Die Zigeuner;Gypsy;4;cygański
der Zimmermann;Die Zimmerleute;Carpenter;4;stolarz
der Zirkus;Die Zirkusse;Circus;3;Cyrk
der Zucker;Die Zucker;Sugar;3;cukier
der Zug;Die Züge;Train;1;pociąg
der Zuschuss;Die Zuschüsse;Grant;4;Dotacja
der Zweifel;Die Zweifel;Doubt;3;Wątpliwość
der Zweig;Die Zweige;Twig;2;Gałązka
der Zwerg;Die Zwerge;Dwarf;2;Krasnolud
der Zwilling;Die Zwillinge;Twin;4;Bliźniak
der Zähler;Die Zähler;Counter;3;Licznik
der Ältere;Die Ältesten;Elder;3;Starszy
der Überlebende;Die Überlebenden;Survivor;4;Niedobitek
der Übersetzer;Die Übersetzer;Translator;4;Tłumacz
die Abfahrt;Die Abfahrten;Departure;3;odjazd
die Ablenkung;Die Ablenkungen;Distraction;4;Roztargnienie
die Absicht;Die Absichten;Intention;3;Zamiar
die Abteilung;Die Abteilungen;Department;4;dział
die Abwesenheit;Die Abwesenheiten;Absence;4;Brak
die Adresse;Die Adressen;Address;3;adres
die Agentur;Die Agenturen;Agency;3;Agencja
die Akademie;Die Akademien;Academy;4;Akademia
die Aktentasche;Die Aktentaschen;Briefcase;4;Aktówka
die Aktion;Die Aktionen;Action;3;Akcja
die Aktivität;Die Aktivitäten;Activity;4;Działalność
die Aluminium;Die Aluminums;Aluminum;4;Aluminium
die Ameise;Die Ameisen;Ant;3;mrówka
die Amerikaner;Die Amerikaner;American;4;amerykański
die Anderen;Die Anderen;Others;3;Inni
die Anforderung;Die Anfragen;Request;4;Wniosek
die Anhörung;Die Anhörungen;Hearing;4;Przesłuchanie
die Anker;Die Anker;Anchor;2;Kotwica
die Ankunft;Die Ankünfte;Arrival;3;przybycie
die Ankündigung;Die Ankündigungen;Announcement;4;Zapowiedź
die Anleitung;Die Anleitungen;Instruction;4;Instrukcja
die Antennen;Die Antennen;Antenna;4;Antena
die Antwort;Die Antworten;Answer;3;odpowiedź
die Anzeige;Die Anzeigen;Ad;3;Ogłoszenie
die Armee;Die Armeen;Army;2;armia
die Art;Die Arten;Kind;1;gatunek
die Asche;Die Asche;Ash;2;Popiół
die Atmosphäre;Die Atmosphären;Atmosphere;4;Atmosfera
die Attraktion;Die Attraktionen;Attraction;4;Atrakcja
die Aufgabe;Die Aufgaben;Task;3;zadanie
die Aufmerksamkeit;Die Aufmerksamkeit;Attention;4;Uwaga
die Aufnahme;Die Aufnahmen;Recording;4;Nagranie
die Aufregung;Die Aufregungen;Excitement;4;Podniecenie
die Augenbraue;Die Augenbrauen;Eyebrow;4;Brew
die Ausgabe;Die Ausgaben;Edition;3;Wydanie
die Ausnahme;Die Ausnahmen;Exception;4;Wyjątek
die Ausrüstung;Die Ausrüstungen;Equipment;4;Ekwipunek
die Aussage;Die Aussagen;Statement;3;Oświadczenie
die Aussicht;Die Ansichten;View;4;Pogląd
die Auszeichnung;Die Auszeichnungen;Award;4;wyróżnienie
die Autobahn;Die Autobahnen;Highway;4;Autostrada
die Banane;Die Bananen;Banana;3;banan
die Bank;Die Bänke;Bench;1;ławkabank
die Barmherzigkeit;Die Barmherzigkeit;Mercy;4;miłosierdzie
die Barriere;Die Barrieren;Barrier;4;Bariera
die Batterie;Die Batterien;Battery;4;Bateria
die Baumwolle;Die Baumwollen;Cotton;4;Bawełna
die Bedeutung;Die Bedeutungen;Meaning;4;Oznaczający
die Bedingung;Die Bedingungen;Condition;4;warunek
die Beere;Die Beeren;Berry;2;Jagoda
die Begegnung;Die Begegnungen;Encounter;4;mecz
die Begeisterung;Die Begeisterung;Enthusiasm;4;Entuzjazm
die Begnadigung;Die Begnadigungen;Pardon;4;Pardon
die Behandlung;Die Behandlungen;Treatment;4;Leczenie
die Beihilfen;Die Beihilfen;Aid;4;pierwsza pomoc
die Bekanntschaft;Die Bekannten;Acquaintance;4;Znajomy
die Beleidigung;Die Beleidigungen;Insult;4;Znieważenie
die Beleuchtung;Die Beleuchtung;Lighting;4;Oświetlenie
die Belohnung;Die Belohnungen;Reward;4;Nagroda
die Bemerkung;Die Bemerkungen;Remark;4;spostrzeżenie
die Beobachtung;Die Beobachtungen;Observation;4;Obserwacja
die Bequemlichkeit;Die Bequemlichkeiten;Convenience;4;Wygoda
die Berührung;Die Berührungen;Touch;4;Dotykać
die Besatzung;Die Besatzungen;Crew;4;Załoga
die Beschreibung;Die Beschreibungen;Description;4;Opis
die Beschwerde;Die Beschwerden;Complaint;4;Reklamacja
die Besorgung;Die Besorgungen;Errand;4;sprawunek
die Bestimmung;Die Bestimmungen;Determination;4;Determinacja
die Bestürzung;Die Bestürzt;Dismay;4;Przerażenie
die Beute;Die Beute;Prey;2;trofeum, zdobycz
die Bewegung;Die Bewegungen;Movement;4;Ruch
die Bewunderung;Die Bewunderung;Admiration;4;Podziw
die Beziehung;Die Beziehungen;Relation;4;Relacja
die Bibel;Die Bibeln;Bible;2;Biblia
die Bibliothek;Die Bibliotheken;Library;4;Biblioteka
die Biegung;Die Biegungen;Bend;3;schylać się
die Biene;Die Bienen;Bee;2;pszczoła
die Birke;Die Birken;Birch;2;Brzozowy
die Blase;Die Blasen;Bubble;2;Bańka
die Blume;Die Blumen;Flower;2;kwiat
die Bluse;Die Blusen;Blouse;2;bluzka
die Blüte;Die Blüten;Blossom;2;Kwitnąć
die Blütenblatt;Die Blütenblätter;Petal;4;Płatek kwiatu
die Bogen;Die Bögen;Arc;2;Łuk
die Bohne;Die Bohnen;Bean;2;fasola
die Bombe;Die Bomben;Bomb;2;Bomba
die Botschaft;Die Botschaften;Embassy;4;Ambasada
die Brandung;Die Brandungen;Surf;4;Surfować
die Braut;Die Bräute;Bride;2;Panna młoda
die Bremse;Die Bremsen;Brake;3;hamulec
die Briefmarke;Die Briefmarken;Stamp;4;znaczek pocztowy
die Brust;Die Brüste;Breast;2;pierś
die Brücke;Die Brücken;Bridge;3;mostpod mostem
die Bucht;Die Buchten;Bay;2;Zatoka
die Bäckerei;Die Bäckereien;Bakery;4;piekarnia
die Böen;Die Böen;Gust;1;Poryw
die Chemische;Die Chemikalien;Chemical;4;Chemiczny
die Creme;Die Cremes;Cream;2;Krem
die Dach;Die Dächer;Rooftop;1;Dachu
die Dame;Die Damen;Lady;1;Dama
die Dankbarkeit;Die Danksagungen;Gratitude;4;Wdzięczność
die Danksagung;Die Danksagungen;Thanksgiving;4;święto Dziękczynienia
die Datei;Die Dateien;File;2;Plik
die Daten;Die Daten;Data;2;Dane
die Debatte;Die Debatten;Debate;3;Debata
die Decke;Die Decken;Ceiling;2;sufit
die Dichtung;Die Dichtungen;Seal;4;Foka
die Diskussion;Die Diskussionen;Discussion;4;Dyskusja
die Disziplin;Die Disziplinen;Discipline;4;Dyscyplina
die Diät;Die Diäten;Diet;1;Dieta
die Dose;Die Dosen;Can;1;Mogą
die Dosis;Die Dosen;Dose;2;Dawka
die Dringlichkeit;Die Dringlichkeiten;Urgency;4;Pilna sprawa
die Druck;Die Drucke;Print;2;Wydrukować
die Dunkelheit;Die Dunkelheiten;Dark;4;Ciemny
die Dusche;Die Duschen;Shower;3;Kabina prysznicowa
die Dämmerung;Die Dämmerungen;Dusk;4;Zmierzch
die Düne;Die Dünen;Dune;1;Wydma
die Ebene;Die Ebenen;Plain;2;Zwykły
die Ecke;Die Ecken;Corner;1;kąt
die Ehe;Die Ehen;Marriage;1;Małżeństwo
die Ehefrau;Die Ehefrauen;Wife;3;żona
die Ehre;Die Ehre;Honor;1;Zaszczyt
die Eiche;Die Eichen;Oak;2;dąb
die Eidechse;Die Eidechsen;Lizard;4;Jaszczurka
die Eifersucht;Die Eifersucht;Jealousy;4;Zazdrość
die Eigenschaft;Die Eigenschaften;Property;4;Nieruchomość
die Eile;Die Eilt;Hurry;1;Spieszyć się
die Eingeweide;Die Eingeweide;Gut;4;Jelito
die Einheit;Die Einheiten;Unit;3;Jednostka
die Einkaufshalle;Die Einkaufszentren;Mall;4;Centrum handlowe
die Einladung;Die Einladungen;Invitation;4;Zaproszenie
die Einleitung;Die Einleitungen;Introduction;4;Wstęp
die Einrichtung;Die Einrichtungen;Facility;4;placówka
die Einsamkeit;Die Einsamkeiten;Loneliness;4;Samotność
die Einsicht;Die Einsichten;Insight;4;Wgląd
die Einsparung;Die Einsparungen;Saving;4;Oszczędność
die Einstellung;Die Einstellungen;Setting;4;Ustawienie
die Eisenbahn;Die Eisenbahnen;Railroad;4;Popędzać
die Eitelkeit;Die Eitelkeiten;Vanity;4;próżność
die Email;Die EMails;EMail;2;E-mail
die Energie;Die Energien;Energy;3;Energia
die Enkelin;Die Enkel;Granddaughter;3;Wnuczka
die Ente;Die Ente;Duck;1;kaczka
die Entscheidung;Die Entscheidungen;Decision;4;Decyzja
die Entschuldigung;Die Entschuldigung;Apology;4;Przeprosiny
die Enttäuschung;Die Enttäuschungen;Disappointment;4;Rozczarowanie
die Entwicklung;Die Entwicklungen;Development;4;Rozwój
die Erbse;Die Erbsen;Pea;2;groszek
die Erdbeere;Die Erdbeeren;Strawberry;4;truskawka
die Erde;Die Erden;Earth;1;planeta ziemia
die Erdnuss;Die Erdnüsse;Peanut;3;Arachid
die Erinnerung;Die Erinnerungen;Reminder;4;Przypomnienie
die Erklärung;Die Erklärungen;Explanation;4;Wyjaśnienie
die Erlaubnis;Die Erlaubnisse;Permission;4;Pozwolenie
die Ernte;Die Ernte;Crop;2;Przyciąć
die Erscheinung;Die Erscheinungen;Appearance;4;Wygląd zewnętrzny
die Erschöpfung;Die Erschöpfungs;Exhaustion;4;Wyczerpanie
die Erwartung;Die Erwartungen;Expectation;4;Oczekiwanie
die Erwähnung;Die Erwähnungen;Mention;4;Wzmianka
die Essenz;Die Essenzen;Essence;3;Istota
die Eule;Die Eulen;Owl;1;Sowa
die Ewigkeit;Die Ewigkeit;Eternity;4;Wieczność
die Existenz;Die Existenzen;Existence;4;Istnienie
die Fabrik;Die Fabriken;Factory;3;fabryka
die Fackel;Die Fackeln;Torch;3;Pochodnia
die Fahrt;Die Fahrten;Ride;2;Jeździć
die Fakultät;Die Fakultäten;Faculty;4;Wydział
die Falle;Die Fallen;Trap;2;Pułapka
die Falte;Die Falten;Fold;2;Zginać
die Falten;Die Falten;Wrinkle;3;Zmarszczka
die Familie;Die Familien;Family;3;rodzina
die Farbe;Die Farben;Color;2;kolor
die Faust;Die Fäuste;Fist;2;Pięść
die Feder;Die Federn;Feather;2;Pióro
die Fee;Die Feen;Fairy;1;Wróżka
die Ferse;Die Fersen;Heel;2;Obcas
die Festung;Die Forts;Fort;3;Fort
die Figur;Die Figuren;Figure;2;figura
die Fiktion;Die Fiktionen;Fiction;3;Fikcja
die Firma;Die Firmen;Firm;2;Solidny
die Flagge;Die Fahnen;Flag;3;Flaga
die Flamme;Die Flammen;Flame;3;Płomień
die Flasche;Die Flaschen;Bottle;3;butelka
die Fledermaus;Die Fledermäuse;Bat;4;Nietoperz
die Fliese;Die Fliesen;Tile;3;Płytka
die Flocke;Die Flocken;Flake;3;Płatek
die Flotte;Die Flotten;Liquor;3;Trunek
die Flucht;Die Fluchten;Escape;3;Ucieczka
die Flug;Die Flusen;Flying;1;Latający
die Flöte;Die Flöten;Flute;2;flet prosty
die Flüssigkeit;Die Flüssigkeiten;Liquid;4;Płyn
die Forelle;Die Forellen;Trout;3;Pstrąg
die Form;Die Formen;Shape;1;kształt
die Forschung;Die Forschungen;Research;4;Badania
die Fotze;Die Fotzen;Pussy;2;Kiciuś
die Frage;Die Fragen;Question;2;Pytanie
die Fraktion;Die Fraktionen;Fraction;4;Frakcja
die Fransen;Die Fransen;Fringe;3;Grzywka
die Franzosen;Die Frenches;French;4;Francuski
die Freiheit;Die Freiheiten;Freedom;4;Wolność
die Freiwillige;Die Freiwilligen;Volunteer;4;Wolontariusz
die Freude;Die Freuden;Pleasure;3;radość
die Freundlichkeit;Die Freundlichkeiten;Kindness;4;Życzliwość
die Freundschaft;Die Freundschaften;Friendship;4;Przyjaźń
die Funktion;Die Funktionen;Function;4;Funkcjonować
die Fähre;Die Fähren;Ferry;2;Prom
die Gabel;Die Gabeln;Fork;2;widelec
die Galaxie;Die Galaxien;Galaxy;3;Galaktyka
die Gallerie;Die Galerien;Gallery;4;Galeria
die Gans;Die Gänse;Goose;1;gęś
die Gasse;Die Gassen;Alley;2;Aleja
die Geburt;Die Geburten;Birth;3;Narodziny
die Gebühr;Die Gebühren;Fee;3;Opłata
die Gefahr;Die Gefahren;Danger;3;niebezpieczeństwo
die Gegensprechanlage;Die Gegensprechanlagen;Intercom;4;Awiofon
die Geisel;Die Geiseln;Hostage;3;Zakładnik
die Gemeinde;Die Gemeinden;Community;4;Społeczność
die Geschichte;Die Geschichten;Story;4;Fabuła
die Geschwindigkeit;Die Geschwindigkeiten;Speed;4;Prędkość
die Geschwister;Die Geschwister;Sibling;4;Rodzeństwo
die Gesellschaft;Die Gesellschaften;Society;4;społeczeństwo
die Geste;Die Gesten;Gesture;2;Gest
die Gewalt;Die Gewalten;Violence;3;Przemoc
die Gewissheit;Die Gewissheiten;Certainty;4;Pewność
die Gezeiten;Die Gezeiten;Tide;4;pływy
die Gitarre;Die Gitarren;Guitar;3;Gitara
die Glocke;Die Glocken;Bell;3;dzwon
die Gnade;Die Gnaden;Grace;2;łaska
die Grenze;Die Grenzen;Border;3;Granica
die Grille;Die Grillen;Cricket;3;Krykiet
die Großeltern;Die Großeltern;Grandparent;4;Dziadkowie
die Großmutter;Die Großmütter;Grandmother;4;Babcia
die Grube;Die Gruben;Pit;2;Dół
die Grundlage;Die Grundlagen;Foundation;4;Fundacja
die Gruppe;Die Gruppen;Group;3;Grupa
die Größe;Die Größen;Size;2;Rozmiar
die Gummi;Die Gummis;Gum;2;Guma
die Gunst;Die Gunst;Favor;2;Przysługa
die Halle;Die Hallen;Hall;2;hala
die Halskette;Die Halsketten;Necklace;4;Naszyjnik
die Haltung;Die Haltungen;Posture;3;Postawa
die Handvoll;Die Hände Voll;Handful;4;Garść
die Hang;Die Hänge;Hillside;1;Stok
die Harmonie;Die Harmonien;Harmony;4;Harmonia
die Haube;Die Hauben;Hood;2;kaptur
die Haupt;Die Haupte;Main;2;Główny
die Hausaufgabe;Die Hausaufgaben;Homework;4;Zadanie domowe
die Haut;Die Häute;Skin;1;skóra
die Hecke;Die Hecken;Hedge;2;Żywopłot
die Heilung;Die Heilungen;Cure;3;Leczyć
die Henne;Die Hennen;Hen;2;Kura
die Herausforderung;Die Herausforderungen;Challenge;4;Wyzwanie
die Herde;Die Herden;Herd;2;Stado
die Herrlichkeit;Die Herrlichkeiten;Glory;4;Chwała
die Hexe;Die Hexen;Witch;1;Czarownica
die Hilfe;Die Hilft;Help;2;pomoc
die Hitze;Die Heats;Heat;2;gorąco
die Hochzeit;Die Hochzeiten;Wedding;4;wesele
die Hoffnung;Die Hoffnungen;Hope;4;Mieć nadzieję
die Hose;Die Hose;Pant;1;spodnie
die Hure;Die Huren;Whore;1;Kurwa
die Hälfte;Die Hälften;Half;3;Połowa
die Höflichkeit;Die Höflichkeiten;Courtesy;4;Kurtuazja
die Höhe;Die Höhen;Height;1;Wzrost, wysokośc
die Höhle;Die Höhlen;Cave;2;Jaskinia
die Hölle;Die Höllen;Hell;2;Piekło
die Hüfte;Die Hüften;Hip;2;Biodro
die Hütte;Die Hütten;Hut;2;Chata
die Idee;Die Ideen;Idea;1;Pomysł
die Identität;Die Identitäten;Identity;4;Tożsamość
die Indische;Die Indianer;Indian;4;indyjski
die Insel;Die Inseln;Island;2;wyspa
die Inspektion;Die Inspektionen;Inspection;4;Kontrola
die Intelligenz;Die Intelligenzen;Intelligence;4;Inteligencja
die Intensität;Die Intensitäten;Intensity;4;Intensywność
die Interesse;Die Interessen;Interest;4;Zainteresowanie
die Intimität;Die Intimitäten;Intimacy;4;Intymność
die Investition;Die Investitionen;Investment;4;Inwestycja
die Ironie;Die Ironien;Irony;3;Ironia
die Italienische;Die Italiener;Italian;4;Włoski
die Jacke;Die Jacken;Jacket;2;kurtka
die Jagd;Die Jagden;Hunt;1;Polowanie
die Jahreszeit;Die Jahreszeiten;Season;4;Pora roku
die Japaner;Die Japaneses;Japanese;3;język japoński
die Jungfrau;Die Jungfrauen;Virgin;4;dziewica
die Kajüte;Die Kabinen;Cabin;3;Kabina
die Kamera;Die Kameras;Camera;3;Kamera
die Kammer;Die Kammern;Chamber;3;Izba
die Kampagne;Die Kampagnen;Campaign;4;Kampania
die Kanone;Die Kanonen;Cannon;3;Armata
die Kapazität;Die Kapazität;Capacity;4;Pojemność
die Kapelle;Die Kapellen;Chapel;3;Kaplica
die Kappe;Die Kappen;Cap;2;Czapka
die Karikatur;Die Karikaturen;Cartoon;4;Kreskówka
die Karotte;Die Karotten;Carrot;3;Marchewka
die Karriere;Die Karrieren;Career;4;Kariera zawodowa
die Karte;Die Karten;Card;2;karta
die Kartoffel;Die Kartoffeln;Potato;4;ziemniak
die Kathedrale;Die Kathedralen;Cathedral;4;katedra
die Katze;Die Katzen;Cat;2;kot
die Kerze;Die Kerzen;Candle;2;świeca
die Kette;Die Ketten;Chain;2;Łańcuch
die Kichern;Das Kichern;Giggle;3;Chichot
die Kiefer;Die Kiefern;Pine;3;sosna
die Kindheit;Die Kindheit;Childhood;4;Dzieciństwo
die Kirche;Die Kirchen;Church;3;kościół
die Kirsche;Die Kirschen;Cherry;3;wiśnia
die Kiste;Die Kisten;Crate;2;Skrzynia
die Klappe;Die Klappen;Flap;3;Klapka
die Klarheit;Die Klarheiten;Clarity;4;Przejrzystość
die Klasse;Die Klassen;Class;3;Klasa
die Klassenkameraden;Die Klassenkameraden;Classmate;4;Kolega z klasy
die Klaue;Die Krallen;Claw;2;Pazur
die Klinge;Die Klingen;Blade;3;Ostrze
die Klinik;Die Kliniken;Clinic;3;Klinika
die Klippe;Die Klippen;Cliff;3;Klif
die Knospe;Die Knospen;Bud;3;Pączek
die Kohlen;Die Kohlen;Coal;3;Węgiel
die Kolonie;Die Kolonien;Colony;3;Kolonia
die Kommission;Die Kommissionen;Commission;4;zamawiać
die Kommode;Die Kommoden;Dresser;3;Kredens
die Kommunikation;Die Kommunikations;Communication;4;Komunikacja
die Konferenz;Die Konferenzen;Conference;4;Konferencja
die Konsequenz;Die Konsequenzen;Consequence;4;Konsekwencja
die Konsole;Die Konsolen;Console;3;Konsola
die Konstruktion;Die Konstruktionen;Construction;4;Budowa
die Konvention;Die Konventionen;Convention;4;Konwencja
die Konzentration;Die Konzentrationen;Concentration;4;Stężenie
die Kopfhaut;Die Kopfhaut;Scalp;4;Oskalpować
die Kopie;Die Kopien;Copy;2;Kopiuj
die Kosten;Die Kosten;Cost;3;Koszt
die Krabbe;Die Krabben;Crab;3;Krab
die Kraft;Die Kräfte;Force;2;Zmuszać
die Kraftstoff;Die Kraftstoffe;Fuel;4;Paliwo
die Krankenschwester;Die Krankenschwestern;Nurse;4;pielęgniarka
die Krankheit;Die Krankheiten;Sickness;4;choroba
die Kratz;Die Kratzer;Scratch;2;Zadrapanie
die Kreation;Die Kreationen;Creation;4;kreacja
die Krippe;Die Krippen;Crib;3;Kołyska
die Krise;Die Krisen;Crisis;2;Kryzys
die Krone;Die Kronen;Crown;2;korona
die Krume;Die Krümel;Crumb;2;Miękisz
die Kruste;Die Krusten;Crust;3;Skorupa
die Krähe;Die Krähen;Crow;2;Wrona
die Kugel;Die Kugeln;Bullet;2;Pocisk
die Kuh;Die Kühe;Cow;1;krowa
die Kultur;Die Kulturen;Culture;3;Kultura
die Kunst;Die Künste;Art;2;sztuka
die Kuppel;Die Kuppeln;Dome;3;Kopuła
die Kurve;Die Kurven;Curve;2;Krzywa
die Kämpfe;Die Kämpfe;Fighting;3;Walczący
die Küche;Die Küchen;Kitchen;2;kuchnia
die Küste;Die Küsten;Coast;2;Wybrzeże
die Ladung;Die Ladungen;loading;3;załadunek
die Lampe;Die Lampen;Lamp;2;lampa
die Landschaft;Die Landschaften;Landscape;4;Krajobraz
die Landung;Die Landungen;Landing;3;Lądowanie
die Lanze;Die Lanzen;Lance;2;Lanca
die Lappen;Die Lumpen;Rag;3;Szmata
die Last;Die Lasten;Burden;1;Ciężar
die Laterne;Die Laternen;Lantern;3;latarnia
die Lauf;Die Läufe;Run;1;Biegać
die Lebenden;Die Livings;Living;4;Żyjący
die Lebensdauer;Die Lebensdauern;Lifetime;4;Dożywotni
die Leber;Die Lebern;Liver;2;Wątroba
die Legende;Die Legenden;Legend;3;Legenda
die Leiche;Die Leichen;Corpse;3;Zwłoki
die Leidenschaft;Die Leidenschaften;Passion;4;Pasja
die Leine;Die Leinen;Leash;2;Smycz
die Leinwand;Die Leinwände;Canvas;4;Płótno
die Leiste;Die Leisten;Ledge;3;Półka
die Leiter;Die Leitern;Ladder;3;drabina
die Liebe;Die Liebe;Love;2;miłość
die Liga;Die Ligen;League;1;Liga
die Lilie;Die Lilien;Lily;2;Lilia
die Limousine;Die Limousinen;Limo;4;Limuzyny
die Linke;Die Linke;Left;2;Lewo
die Linse;Die Linsen;Lens;2;Obiektyw
die Lippe;Die Lippen;Lip;2;warga
die Liste;Die Listen;List;2;Lista
die Literatur;Die Literaturen;Literature;4;Literatura
die Lizenz;Die Lizenzen;License;3;Licencja
die Locke;Die Locken;Curl;2;Kędzior
die Logik;Die Logik;Logic;2;Logika
die Luft;Die Lüfte;Air;1;powietrze
die Luftschleuse;Die Luftschleusen;Airlock;4;Airlock.
die Luke;Die Luken;Hatch;1;Właz
die Lunge;Die Lungen;Lung;2;Płuco
die Luxus;Der Luxus;Luxury;2;Luksus
die Länge;Die Längen;Length;2;Długość
die Lösung;Die Lösungen;Solution;3;Rozwiązanie
die Lücke;Die Lücken;Gap;2;Luka
die Lüge;Die Lügen;Lie;1;Kłamać
die Magie;Die Magie;Magic;2;magia
die Majestät;Die Majestäten;Majesty;4;Majestat
die Mama;Die Mütter;Mom;1;Mama
die Manschette;Die Manschetten;Cuff;4;Mankiet
die Marine;Die Marinen;Navy;3;Marynarka wojenna
die Marke;Die Marken;Brand;2;Marka
die Marmelade;Die Marmeladen;Jam;4;marmolada
die Maschine;Die Maschinen;Machine;4;maszyna
die Maschinen;Die Maschinen;Machinery;4;Maszyneria
die Maske;Die Masken;Mask;2;Maska
die Masse;Die Massen;Mass;2;Masa
die Mathematik;Die Mathematik;Math;4;Matematyka
die Matratze;Die Matratzen;Mattress;4;Materac
die Matte;Die Matten;Mat;2;Mata
die Maus;Die Mäuse;Mouse;1;mysz
die Medaille;Die Medaillen;Medal;4;Medal
die Medien;Die Medien;Media;3;Głoska bezdźwięczna
die Melodie;Die Melodien;Tune;3;Melodia
die Menge;Die Mengen;Crowd;2;Tłum
die Metapher;Die Metaphern;Metaphor;4;Metafora
die Miete;Die Mieten;Rent;2;czynsz
die Milch;Die Milch;Milk;2;mleko
die Mischung;Die Mischungen;Mixture;4;Mieszanina
die Mitte;Die Middles;Middle;2;Środkowy
die Mitten;Die Midsts;Midst;3;Środek
die Mitternachts;Die Mitternächte;Midnight;4;środek nocy
die Mode;Die Mode;Fashion;1;Moda
die Morgendämmerung;Die Morgengrauen;Dawn;4;Świt
die Musik;Die Musiken;Music;2;Muzyka
die Möbel;Die Möbel;Furniture;2;Meble
die Möglichkeit;Die Möglichkeiten;Possibility;4;Możliwość
die Mücke;Die Mücken;Mosquito;2;komar
die Mühle;Die Mühlen;Mill;2;Młyn
die Münze;Die Münzen;Coin;2;Moneta
die Nachbarschaft;Die Nachbarschaften;Neighborhood;4;Sąsiedztwo
die Nachricht;Die Nachrichten;Message;4;Wiadomość
die Nachrichten;Die Newses;News;4;wiadomości
die Nacht;Die Nächte;Night;2;noc
die Nadel;Die Nadeln;Needle;2;igła
die Naht;Die Nähte;Seam;1;Szew
die Narbe;Die Narben;Scar;2;Blizna
die Nase;Die Nasen;Nose;1;nos
die Natur;Die Natur;Nature;2;natura
die Neigung;Die Neigungen;Affection;3;Sympatia
die Nichte;Die Nichten;Niece;3;Siostrzenica
die Niederlage;Die Niederlagen;Defeat;4;Pokonać
die Nonne;Die Nonnen;Nun;2;Siostra zakonna
die Not;Die Nöte;Distress;1;awarja
die Note;Die Noten;Mark;1;ocena
die Notiz;Die Notizen;Note;2;Notatka
die Notwendigkeit;Die Notwendigkeiten;Necessity;4;Konieczność
die Oberfläche;Die Oberflächen;Surface;4;Powierzchnia
die Oma;Die Omas;Granny;1;Babunia
die Oper;Die Opern;Opera;1;Opera
die Operation;Die Operationen;Surgery;4;Chirurgia
die Organisation;Die Organisationen;Organization;4;Organizacja
die Orgel;Die Organe;Organ;2;Organ
die Panik;Die Panik;Panic;2;Panika
die Patrouille;Die Patrouillen;Patrol;4;Patrol
die Pause;Die Pausen;Break;2;Przerwa
die Peitsche;Die Peitschen;Whip;4;Bicz
die Periode;Die Perioden;Period;3;Okres
die Perle;Die Perlen;Pearl;2;Perła
die Perspektive;Die Perspektiven;Perspective;4;Perspektywiczny
die Persönlichkeit;Die Persönlichkeiten;Personality;4;Osobowość
die Perücke;Die Perücken;Wig;3;Peruka
die Pest;Die Plagen;Plague;1;Plaga
die Pfanne;Die Pfannen;Pan;3;Patelnia
die Pfeife;Die Pfeifen;Whistle;3;Gwizdać
die Pflanze;Die Pflanzen;Plant;3;roślina
die Pflaume;Die Pflaumen;Plum;3;śliwka
die Pfote;Die Pfoten;Paw;2;Łapa
die Pfütze;Die Pfützen;Puddle;3;Kałuża
die Philosophie;Die Philosophien;Philosophy;4;Filozofia
die Pille;Die Pillen;Pill;2;Pigułka
die Piste;Die Pisten;Slope;2;Nachylenie
die Pistole;Die Pistolen;Pistol;3;Pistolet
die Platte;Die Paneele;Panel;3;Płyta
die Polizei;Die Politiken;Police;3;Policja
die Postkarte;Die Postkarten;Postcard;4;kart
die Presse;Die Pressen;Press;3;naciskać
die Probe;Die Proben;Specimen;2;Próbka
die Produktion;Die Produktionen;Production;4;Produkcja
die Prozession;Die Prozessionen;Procession;4;Procesja
die Prärie;Die Prärien;Prairie;3;Preria
die Prüfung;Die Prüfungen;Exam;3;Egzamin
die Pumpe;Die Pumpen;Pump;2;Pompa
die Puppe;Die Puppen;Doll;2;Lalka
die Pyramide;Die Pyramiden;Pyramid;4;Piramida
die Qual;Die Qualen;Agony;1;Agonia
die Qualität;Die Qualitäten;Quality;4;Jakość
die Quelle;Die Quellen;Source;3;Źródło
die Rache;Die Rache;Revenge;2;Zemsta
die Rakete;Die Raketen;Rocket;3;Rakieta
die Rampe;Die Rampen;Ramp;2;Rampa
die Rast;Die Reste;Rest;1;Odpoczynek
die Ratte;Die Ratten;Rat;2;Szczur
die Raum;Die Räume;Room;1;Pokój
die Reaktion;Die Reaktionen;Reaction;4;Reakcja
die Rechnung;Die Rechnungen;Bill;4;rachunek
die Rede;Die Reden;Speech;1;Przemówienie
die Reflexion;Die Reflexionen;Reflection;4;Odbicie
die Regel;Die Regeln;Rule;2;Reguła
die Regierung;Die Regierungen;Government;4;Rząd kraju
die Reichweite;Die Reichweiten;Reach;4;Osiągać
die Reihe;Die Reihen;Row;2;rząd czegoś
die Reinigung;Die Reinigungen;Cleaning;4;Czyszczenie
die Reise;Die Reisen;Journey;2;podróż
die Reparatur;Die Reparaturen;Repair;4;Naprawic
die Republik;Die Republiken;Republic;4;Republika
die Reservierung;Die Reservierungen;Reservation;4;Rezerwacja
die Residenz;Die Residenzen;Residence;4;Rezydencja
die Rettung;Die Rettungen;Rescue;3;Ratunek
die Richtung;Die Richtungen;Direction;4;kierunek
die Rinde;Die Rinden;Bark;2;Szczekać
die Rippe;Die Rippen;Rib;2;Żebro
die Rolle;Die Rollen;Role;2;Rola
die Romantik;Die Romane;Romance;4;Romans
die Ruine;Die Ruinen;Ruin;2;Ruina
die Runde;Die Runden;Round;2;Okrągły
die Runden;Die Runden;Lap;3;Okrążenie
die Römisch;Die Römer;Roman;3;rzymski
die Rückkehr;Die Renditen;Return;4;Powrót
die Rüstung;Die Rüstungen;Armor;3;Zbroja
die Saat;Die Samen;Seed;1;Nasionko
die Sammlung;Die Sammlungen;Collection;4;Kolekcja
die Sandale;Die Sandalen;Sandal;3;Sandał
die Sauerstoff;Die Sauerstoffe;Oxygen;4;Tlen
die Schale;Die Schalen;Bowl;3;salaterka
die Schaltung;Die Schaltungen;Circuit;4;obwód elektryczny
die Schande;Die Schande;Shame;3;Wstyd
die Schattierung;Die Schatten;Shade;4;odcień
die Schaufel;Die Schaufeln;Shovel;4;Łopata
die Schaukel;Die Schaukeln;Swing;4;Huśtać się
die Scheibe;Die Scheiben;Slice;3;Plasterek
die Scheidung;Die Scheidungen;Divorce;4;Rozwód
die Scheiße;Die Scheiße;Shit;3;Gówno
die Scherbe;Die Scherben;Shard;3;Czerep
die Schere;Die Scheren;Scissors;3;nożyce
die Scheune;Die Scheunen;Barn;3;Stodoła
die Schicht;Die Schichten;Layer;3;Warstwa
die Schiene;Die Schienen;Rail;3;Szyna
die Schildkröte;Die Schildkröten;Turtle;4;żółw
die Schlagzeile;Die Schlagzeilen;Headline;4;Nagłówek
die Schlange;Die Schlangen;Snake;4;wąż
die Schleife;Die Schlaufen;Loop;4;Pętla
die Schlucht;Die Schluchten;Canyon;4;Kanion
die Schnur;Die Schnüre;String;3;Strunowy
die Schrotflinte;Die Schrotflinten;Shotgun;4;Strzelba
die Schublade;Die Schubladen;Drawer;4;szuflada
die Schuld;Die Schulden;Guilt;3;Wina
die Schule;Die Schulen;School;3;szkołaszkoła
die Schulter;Die Schultern;Shoulder;4;ramię
die Schwalbe;Die Schwalben;Swallow;4;Jaskółka
die Schwangerschaft;Die Schwangerschaften;Pregnancy;4;Ciąża
die Schwarze;Die Schwarzen;Black;4;Czarny
die Schwester;Die Schwestern;Sister;4;siostra
die Schwierigkeit;Die Schwierigkeiten;Difficulty;4;trudność
die Schwäche;Die Schwächen;Weakness;4;Słabość
die Schwärze;Die Schwärzen;Blackness;4;Czerń
die Schönheit;Die Schönheiten;Beauty;4;Piękno
die Schürze;Die Schürzen;Apron;3;Fartuch
die Seele;Die Seelen;Soul;2;Dusza
die Sehenswürdigkeit;Die Sehenswürdigkeiten;Sight;4;Wzrok
die Sehnsucht;Die Sehnsüchte;Longing;4;Tęsknota
die Seide;Die Seide;Silk;2;Jedwab
die Seife;Die Seifen;Soap;2;mydło
die Seite;Die Seiten;Side;2;strona
die Seitenleiste;Die Seitenleisten;Sidebar;4;Pasek boczny
die Selbstmord;Die Selbstmorde;Suicide;4;Samobójstwo
die Sequenz;Die Sequenzen;Sequence;3;Sekwencja
die Serviette;Die Servietten;Napkin;4;serwetka
die Sicherheit;Die Sicherheiten;Safety;4;Bezpieczeństwo
die Sicherungs;Die Sicherungen;Backup;4;Kopia zapasowa
die Siedlung;Die Siedlungen;Settlement;4;Osada
die Silbe;Die Silben;Syllable;2;Sylaba
die Sirene;Die Sirenen;Siren;3;Syrena
die Sitzung;Die Sitzungen;Session;3;Sesja
die Skizze;Die Skizzen;Sketch;3;Naszkicować
die Skulptur;Die Skulpturen;Sculpture;4;Rzeźba
die Socke;Die Socken;Sock;2;Skarpetka
die Sonne;Die Sonnen;Sun;2;słońce
die Sonnenbrille;Die Sunglasseses;Sunglasses;4;Okulary słoneczne
die Sorge;Die Sorgen;Worry;2;Martwić się
die Spannung;Die Spannungen;Tension;4;Napięcie
die Spinne;Die Spinnen;Spider;3;Pająk
die Spitze;Die Spitzen;Top;3;Szczyt
die Sprache;Die Sprachen;Language;3;język, mowa
die Spur;Die Spuren;Trace;1;Namierzać
die Stadt;Die Städte;City;2;miasto
die Stange;Die Stäbe;Rod;3;Pręt
die Stille;Die Stillen;Silence;3;Cisza
die Stimme;Die Stimmen;Voice;3;Głos
die Stimmung;Die Stimmungen;Mood;4;Nastrój
die Stirn;Die Stirn;Forehead;2;Czoło
die Strafe;Die Strafen;Punishment;3;Kara
die Straftat;Die Straftaten;Offense;4;Wykroczenie
die Strahlung;Die Strahlungen;Radiation;4;Promieniowanie
die Strategie;Die Strategien;Strategy;4;Strategia
die Straße;Die Straßen;Street;3;ulica
die Strecke;Die Spuren;Track;3;odcinek
die Struktur;Die Strukturen;Structure;4;Struktura
die Strömung;Die Ströme;Flow;4;Pływ
die Stunde;Die Stunden;Hour;3;godzina
die Stute;Die Stuten;Mare;2;Klacz
die Stärke;Die Stärken;Strength;3;Wytrzymałość
die Substanz;Die Substanzen;Substance;4;Substancja
die Suche;Die Suche;Search;2;Szukaj
die Summe;Die Summen;Sum;2;Suma
die Suppe;Die Suppen;Soup;2;zupa
die Sympathie;Die Sympathien;Sympathy;4;Współczucie
die Szene;Die Szenen;Scene;2;Scena
die Säge;Die Sägen;Saw;1;Piła
die Säulen;Die Säulen;Pillar;3;Filar
die Säure;Die Säuren;Acid;2;Kwas
die Sünde;Die Sünden;Sin;2;grzech
die Süße;Die Süßen;Sweet;1;Słodki
die Tabak;Die Tabake;Tobacco;2;Tytoń
die Taille;Die Taille;Waist;3;Talia
die Tante;Die Tanten;Aunt;2;ciocia
die Tasche;Die Taschen;Pocket;3;torba
die Taschenlampe;Die Taschenlampen;Flashlight;4;Latarka
die Tasse;Die Tassen;Cup;2;filiżanka
die Tat;Die Taten;Deed;1;Czyn
die Taube;Die Tauben;Pigeon;2;Gołąb
die Taverne;Die Tavernen;Tavern;3;Tawerna
die Technik;Die Techniken;Technique;3;Technika
die Temperatur;Die Temperaturen;Temperature;4;Temperatura
die Tentakel;Die Tentakeln;Tentacle;4;Macka
die Terrasse;Die Terrassen;Terrace;4;Taras
die Theorie;Die Theorien;Theory;3;Teoria
die Therapie;Die Therapie;Therapy;4;Terapia
die Tiefe;Die Tiefen;Depth;2;Głębokość
die Tinten;Die Tinten;Ink;3;Atrament
die Tochter;Die Töchter;Daughter;3;córka
die Toilette;Die Toiletten;Toilet;4;toaleta
die Tomate;Die Tomaten;Tomato;3;pomidor
die Tragödie;Die Tragödien;Tragedy;4;Tragedia
die Traube;Die Trauben;Grape;3;Winogrono
die Traufe;Die Traufe;Eave;3;Okapować
die Traurigkeit;Die Traurigkeiten;Sadness;4;Smutek
die Treppen;Die Treppe;Stair;3;Schodek
die Trommel;Die Trommeln;Drum;3;Bęben
die Truppe;Die Truppen;Troop;3;trupa
die Trübung;Die Trübungen;Haze;3;zakłócenie
die Trümmer;Die Trümmern;Rubble;3;Gruz
die Tugend;Die Tugenden;Virtue;3;Cnota
die Tunika;Die Tuniken;Tunic;3;Tunika
die Tänzerin;Die Tänzer;Dancer;4;Tancerz
die Tätowierung;Die Tattoos;Tattoo;4;Tatuaż
die Tür;Die Türen;Door;1;drzwi
die Türklingel;Die Türklingeln;Doorbell;4;Dzwonek do drzwi
die Türöffnung;Die Türen;Doorway;4;ościeże drzwiowe
die UBahn;Die UBahnen;Subway;2;Metro
die Uhr;Die Uhren;Watch;1;zegarek
die Umarmung;Die Umarmungen;Hug;4;Przytulać
die Umgebung;Die Umgebungen;Environment;4;Środowisko
die Unabhängigkeit;Die Unabhängigkeiten;Independence;4;Niezależność
die Universität;Die Universitäten;University;4;Uniwersytet
die Unschärfe;Die Unschärfen;Blur;4;rozmycie
die Unterhaltung;Die Unterhaltungen;Entertainment;4;Zabawa
die Unterschrift;Die Unterschriften;Signature;4;Podpis
die Untersuchung;Die Untersuchungen;Examination;4;Badanie
die Untertasse;Die Untertassen;Saucer;4;Spodek
die Unterwäsche;Die Unterwäsche;Underwear;4;bielizna
die Unwissenheit;Die Unwissenheit;Ignorance;4;Ignorancja
die Vene;Die Venen;Vein;1;Żyła
die Verbindung;Die Verbindungen;Connection;4;związek
die Verbrennung;Die Verbrennungen;Burn;4;Oparzenie
die Vereinbarung;Die Vereinbarungen;Arrangement;4;Układ
die Vergangenheit;Die Vergangenheit;Past;4;przeszłość
die Verletzung;Die Verletzungen;Injury;4;Obrażenia
die Vermietung;Die Vermietungen;Rental;4;Wynajem
die Vermutung;Die Vermutungen;Guess;4;Odgadnąć
die Verpflichtung;Die Verpflichtungen;Obligation;4;Obowiązek
die Verrücktheit;Die Verrücktheiten;Madness;4;Szaleństwo
die Versammlung;Die Versammlungen;Gathering;4;Zgromadzenie
die Verschiebung;Die Verschiebungen;Shift;4;Zmiana
die Versicherung;Die Versicherungen;Insurance;4;Ubezpieczenie
die Verwaltung;Die Verwaltungen;Administration;4;Administracja
die Verwendung;Die Verwendungen;Use;4;Posługiwać się
die Verwirrung;Die Verwirrungen;Confusion;4;Dezorientacja
die Verzweiflung;Die Verzweiflungen;Despair;4;Rozpacz
die Verzögerung;Die Verzögerungen;Delay;4;Opóźnienie
die Vorbereitung;Die Vorbereitungen;Preparation;4;Przygotowanie
die Vorhalle;Die Veranden;Porch;4;Ganek
die Waffe;Die Waffen;Gun;2;broń
die Wahl;Die Wahlen;Election;1;Wybór
die Wahrheit;Die Wahrheiten;Truth;4;Prawda
die Wahrnehmung;Die Wahrnehmungen;Perception;4;Postrzeganie
die Waise;Die Waisen;Orphan;2;Sierota
die Wange;Die Wangen;Cheek;2;policzek
die Wangenknochen;Die Wangenknochen;Cheekbone;4;Kość policzkowa
die Wanne;Die Wannen;Tub;2;Wanna
die Warnung;Die Warnungen;Warning;3;Ostrzeżenie
die Wartung;Die Wartungen;Maintenance;3;Utrzymanie
die Wasch;Die Wasch;Wash;2;Myć się
die Weide;Die Weiden;Pasture;2;Pastwisko
die Weisheit;Die Weisheiten;Wisdom;4;Mądrość
die Weite;Die Weiten;width;2;szerokość
die Welle;Die Wellen;Wave;2;Fala
die Welligkeit;Die Wellen;Ripple;4;Marszczyć
die Welt;Die Welt;World;1;świat
die Wende;Die Wenden;Turn;2;Zakręt
die Weste;Die Westen;Vest;2;Kamizelka
die Wette;Die Wetten;Bet;2;zakład
die Wichtigkeit;Die Wichtigkeiten;Importance;4;Znaczenie
die Wiege;Die Wiegen;Cradle;2;Kolebka
die Wiese;Die Wiesen;Meadow;2;łąka
die Wildnis;Die Wildnis;Wilderness;3;dźicz
die Windel;Die Windeln;Diaper;3;Pielucha
die Windschutzscheibe;Die Windschutzscheiben;Windshield;4;Przednia szyba
die Wissenschaft;Die Wissenschaften;Science;4;nauka
die Witwe;Die Witwen;Widow;2;Wdowa
die Woche;Die Wochen;Week;2;tydzień
die Wohnung;Die Wohnungen;Apartment;3;mieszkanie
die Wolke;Die Wolken;Cloud;2;chmura
die Wolle;Die Wolle;Wool;2;wełna
die Wunde;Die Wunden;Wound;2;Rana
die Wurst;Die Würste;Sausage;2;kiełbasa
die Wut;Die Wütet;Rage;1;Wściekłość
die Wärme;die Wärmen;Warmth;2;Ciepło
die Wäsche;Die Wäsche;Laundry;3;Pranie
die Wüste;Die Wüsten;Desert;2;pustynia
die Zahlung;Das Zahlt;Pay;3;Płacić
die Zeder;Die Zedern;Cedar;2;Cedr
die Zehe;Die Zehen;Toe;1;palec u nogi
die Zeichnung;Die Zeichnungen;Drawing;4;rysunek
die Zeit;Die Zeiten;Time;1;czas
die Zeitung;Die Zeitung;Newspaper;3;gazeta
die Zelle;Die Zellen;Cell;2;Komórka
die Zeremonie;Die Zeremonien;Ceremony;4;Ceremonia
die Zerstörung;Die Zerstörungen;Destruction;4;Zniszczenie
die Ziege;Die Ziegen;Goat;2;Koza
die Ziegel;Die Ziegel;Brick;3;Cegła
die Zigarette;Die Zigaretten;Cigarette;4;papieros
die Zigarre;Die Zigarren;Cigar;3;Cygaro
die Zitrone;Die Zitronen;Lemon;3;cytryna
die Zivilisation;Die Zivilisationen;Civilization;4;Cywilizacja
die Zufriedenheit;Die Zufriedenheiten;Satisfaction;4;Zadowolenie
die Zugehörigkeit;Die Zugehörigkeiten;Affiliation;4;Przynależność
die Zugriffs;Die Zugriffe;Access;4;Dostęp
die Zukunft;Die Zukunfte;Future;3;przyszłość
die Zulassung;Die Zulassungen;Approval;4;Aprobata
die Zunge;Die Zungen;Tongue;2;język
die Zuordnung;Die Zuordnungen;Assignment;4;przydzielone zadanie
die Zuzwinkern;Die Zwinkert;Wink;4;Puścić oczko
die Zwiebel;Die Zwiebeln;Onion;3;cebula
die Zwischenzeit;Die Zwischenzeiten;Meantime;4;W międzyczasie
die Öffentlichkeit;Die Öffentlichkeit;Public;4;Publiczny
die Überlebens;Die Überreste;Survival;4;Przetrwanie
die Überlegung;Die Überlegungen;Consideration;4;Namysł
die Überraschung;Die Überraschungen;Surprise;4;Niespodzianka
die Übersetzung;Die Übersetzungen;Translation;4;Tłumaczenie
die Übertragungs;Die Übertragungen;Transmission;4;Przenoszenie
die Überzeugung;Die Überzeugungen;Conviction;4;Przekonanie
die Übung;Die Übungen;Exercise;2;Ćwiczenie`;
