export const rawNounsForms = `das Abendessen;die Abendessen;Dinner;4;kolacja
das Abenteuer;die Abenteuer;Adventure;4;Przygoda
das Abzeichen;die Abzeichen;Badge;4;Odznaka
das Ahorn;die Ahorne;Maple;2;Klon
das Alter;die Alter;Age;2;wiek
das Angebot;die Angebote;Offer;3;Oferta
das Armband;die Armbänder;Bracelet;3;Bransoletka
das Arschloch;die Arschlöcher;Asshole;4;Dupek
das Artefakt;die Artefakte;Artifact;4;Artefakt
das Aspekt;die Aspekte;Aspect;3;Aspekt
das Auge;die Augen;Eye;1;oko
das Augenlid;die Augenlider;Eyelid;4;Powieka
das Ausmaß;die Ausmaße;Extent;3;Zakres
das Bad;die Bäder;Bath;1;kąpiel
das Band;die Bänder;Tape;1;Taśma
das Bauernhaus;die Bauernhäuser;Farmhouse;4;Dom wiejski
das Becken;die Becken;Basin;3;Basen
das Bedürfnis;die Bedürfnisse;Need;4;Potrzebować
das Begräbnis;die Begräbnisse;Funeral;4;Pogrzeb
das Bein;die Beine;Leg;1;noga
das Beispiel;die Beispiele;Example;4;przykład
das Bericht;die Berichte;Report;3;Raport
das Bett;die Betten;Bed;1;łóżko
das Bewusstsein;die Bewussts;Consciousness;4;Świadomość
das Bier;die Biere;Beer;1;piwo
das Bild;die Bilder;Picture;1;obraz
das Blatt;die Blätter;Leaf;2;Liść
das Blut;die Blut;Blood;1;krew
das Boot;die Boote;Boat;1;łódź
das Brett;die Bretter;Plank;2;Deska
das Buch;die Bücher;Book;1;książka
das Bündel;die Bündel;Bundle;3;plik czegoś
das Büro;die Büros;Office;1;biuro
das Dach;die Dächer;Roof;1;dach
das Datum;die Daten;Date;2;data
das Ding;die Dinge;Thing;1;Rzecz
das Dokument;die Dokumente;Document;4;Dokument
das Dorf;die Dörfer;Village;1;wieś
das Dreieck;die Dreiecke;Triangle;3;Trójkąt
das Dunkel;die Dunkel;Gloom;3;Mrok
das Ei;die Eier;Egg;1;jajo
das Eichhörnchen;die Eichhörnchen;Squirrel;4;Wiewiórka
das Einkaufen;die Einkäufe;Shopping;4;Zakupy
das Einkommen;die Einkommen;Income;4;Dochód
das Elternteil;die Eltern;Parent;4;Rodzic
das Ende;die Enden;End;1;koniec
das Englisch;die Englishes;English;4;język angielski
das Erdbeben;die Erdbeben;Earthquake;4;Trzęsienie ziemi
das Ereignis;die Events;Event;4;Wydarzenie
das Ergebnis;die Ergebnisse;Result;4;Wynik
das Erlebnis;die Erlebnisse;Experience;4;Doświadczenie
das Essen;die Eatings;Eating;2;Jedzenie
das Etikett;die Etiketten;Label;3;Etykieta
das Fahrrad;die Fahrräder;Bike;3;rower
das Fahrzeug;die Fahrzeuge;Vehicle;4;Pojazd
das Feld;die Felder;Field;1;Pole
das Fell;die Felle;Fur;1;Futro
das Fenster;die Fenster;Window;3;okno
das Fernsehen;die Fernseher;Television;4;Telewizja
das Fest;die Feste;Festival;1;Festiwal
das Festmahl;die Feste;Feast;4;Święto
das Fett;die Fette;Fat;1;tłuszcz
das Feuer;die Feuer;Fire;2;ogień
das Feuerzeug;die Feuerzeuge;Lighter;4;zapalniczka
das Fieber;die Fieber;Fever;3;Gorączka
das Fitnesscenter;die FitnessStudios;Gym;4;siłownia
das Flimmern;die Flackert;Flicker;4;Migotanie
das Floß;die Flöße;Raft;1;Tratwa
das Flugzeug;die Flugzeuge;Plane;4;samolot
das Foto;die Fotos;Photo;1;Zdjęcie
das Frühstück;die Frühstücke;Breakfast;4;śniadanie
das Gasthaus;die Gasthöfe;Inn;4;Zajazd
das Gebet;die Gebete;Prayer;2;Modlitwa
das Gebäude;die Gebäude;Building;3;budynek
das Gedicht;die Gedichte;Poem;3;Wiersz
das Gefrier;die Gefrier;Freezer;3;Zamrażarka
das Gefängnis;die Gefängnisse;Prison;4;Więzienie
das Gefäss;die Gläser;Jar;3;Słoik
das Gefühl;die Gefühle;Feeling;3;Uczucie
das Gehalt;die Gehälter;Salary;3;Pensja
das Geheimnis;die Geheimnisse;Secret;4;Sekret
das Gehirn;die Gehirne;Brain;3;mózg
das Geld;die Gelder;Money;1;pieniądze
das Gelächter;die Gelächter;Laughter;4;Śmiech
das Geländer;die Geländer;Railing;4;Balustrada
das Gemälde;die Gemälde;Painting;3;malunek
das Gemüse;die Gemüse;Vegetable;3;Warzywo
das Gen;die Gene;Gene;1;Gen
das Genie;die Genies;Genius;2;Geniusz
das Gepäck;die Gepäck;Luggage;3;bagaż
das Gericht;die Gerichte;Court;3;Sąd
das Gerichtsgebäude;die Gerichtsgebäuden;Courthouse;4;Budynek sądu
das Geräusch;die Geräusche;Noise;4;Hałas
das Gerücht;die Gerüchte;Rumor;3;Plotka
das Geschenk;die Geschenke;Gift;4;prezent
das Gesetz;die Gesetze;Law;3;Ustawa
das Gesicht;die Gesichter;Face;3;twarz
das Gespenst;die Geister;Ghost;4;Duch
das Gespräch;die Gespräche;Talk;4;Rozmowa
das Getränk;die Getränke;Drink;3;napój
das Gewebe;die Gewebe;Tissue;3;Papierowa chusteczka
das Gewehr;die Gewehre;Rifle;3;karabin
das Gewicht;die Gewichte;Weight;3;Waga
das Gewissen;die Gewissen;Conscience;4;Sumienie
das Gift;die Gifte;Poison;1;trucizna
das Glück;die Glück;Fortune;2;szczęście
das Glühen;die Glüht;Glow;3;Blask
das Grab;die Gräber;Grave;1;Mogiła
das Gras;die Gräser;Grass;1;trawa
das Grinsen;die Grins;Grin;3;Szeroki uśmiech
das Gute;die Güter;Good;1;Dobro
das Haar;die Haare;Hair;1;włos
das Handgelenk;die Handgelenke;Wrist;4;Nadgarstek
das Handtuch;die Handtücher;Towel;4;Ręcznik
das Handwerk;die Handwerk;Craft;4;Rękodzieło
das Hauptquartier;die Headquarterses;Headquarters;4;Siedziba
das Haus;die Häuser;House;1;dom
das Haustier;die Haustiere;Pet;4;Zwierzak domowy
das Heck;die Hecks;Stern;1;rufa
das Hemd;die Hemden;Shirt;1;koszula
das Herrenhaus;die Herrenhäuser;Manor;4;Dwór
das Herz;die Herzen;Heart;1;serce
das Hinken;die Hinkt;Limp;3;Utykać
das Huhn;die Hühner;Chicken;1;kurczak
das Insekt;die Insekten;Insect;3;Owad
das Institut;die Institute;Institute;4;Instytut
das Intervall;die Intervalle;Interval;4;Interwał
das Jahr;die Jahre;Year;1;rok
das Jahrhundert;die Jahrhunderte;Century;4;stulecie
das Jahrzehnt;die Jahrzehnte;Decade;4;Dekada
das Juwel;die Juwelen;Jewel;2;Klejnot
das Kabel;die Kabel;Cable;2;Kabel
das Kalb;die Kälber;Calf;1;cielak
das Kamel;die Kamele;Camel;2;Wielbłąd
das Kanu;die Kanus;Canoe;1;Kajak
das Kapitel;die Kapitel;Chapter;3;Rozdział
das Keuchen;die Keuchen;Gasp;3;Łapanie tchu
das Kind;die Kinder;Child;1;dziecko
das Kinderbett;die Kinderbetten;Cot;4;Łóżko składane
das Kinn;die Kinne;Chin;1;podbródek
das Kissen;die Kissen;Pillow;3;Poduszka
das Klassenzimmer;die Klassenzimmer;Classroom;4;sala, klasa
das Klavier;die Klaviere;Piano;3;Fortepian
das Kleid;die Kleider;Dress;2;sukienka
das Kleidungsstück;die Kleidungsstücke;Garment;4;Część garderoby
das Knie;die Knie;Knee;1;kolano
das Kompliment;die Komplimente;Compliment;4;Komplement
das Kongress;die Kongresse;Congress;4;Kongres
das Konzept;die Konzepte;Concept;3;Pojęcie
das Konzert;die Konzerte;Concert;3;Koncert
das Korn;die Körner;Grain;1;Ziarno
das Kostüm;die Kostüme;Costume;3;Kostium
das Krankenhaus;die Krankenhäuser;Hospital;4;szpital
das Kraut;die Kräuter;Herb;2;Ziele
das Kreuz;die Kreuze;Cross;2;Krzyż
das Kupfer;die Kupfer;Copper;3;Miedź
das Kätzchen;die Kätzchen;Kitten;4;Kotek
das Königreich;die Königreiche;Kingdom;4;Królestwo
das Küken;die Küken;Chick;2;Pisklę
das Labor;die Labore;Lab;2;Laboratorium
das Labyrinth;die Labyrinthe;Maze;4;Labirynt
das Lachen;die Lachen;Laugh;3;uśmiech
das Lamm;die Lämmer;Lamb;1;owieczka
das Land;die Länder;Country;1;kraj
das Leben;die Leben;Life;2;życie
das Lebensmittel;die Lebensmittel;Grocery;4;Sklep spożywczy
das Leder;die Leder;Leather;2;materiał skóra
das Lehren;die Lehren;Teaching;3;Nauczanie
das Leiden;die Leiden;Suffering;3;Cierpienie
das Licht;die Lichter;Light;2;swiatło
das Liebesspiel;die Lovemakings;Lovemaking;4;Uprawianie miłości
das Lied;die Lieder;Song;1;Utwór muzyczny
das Lob;die Lobs;Praise;1;Pochwała
das Loch;die Löcher;Hole;1;dziura
das Los;die Lose;Lot;1;Działka
das Lächeln;die Lächeln;Smile;3;Uśmiechnij się
das Maultier;die Maultiere;Mule;4;Muł
das Meer;die Meere;Sea;1;morze
das Mehl;die Mehle;Flour;1;Mąka
das Menü;die Menüs;Menu;1;Menu
das Messer;die Messer;Knife;3;nóż
das Metall;die Metalle;Metal;3;metal
das Mikrofon;die Mikrofone;Microphone;4;Mikrofon
das Mittagessen;die Mittagessen;Lunch;4;obiad
das Mondlicht;die Mondlicht;Moonlight;4;światło księżyca
das Moos;die Moose;Moss;1;Mech
das Motiv;die Motive;Motive;2;Motyw
das Motorrad;die Motorräder;Motorcycle;4;Motocykl
das Murmeln;die Murmeln;Murmur;3;Szmer
das Muster;die Muster;Pattern;3;Wzór
das Mädchen;die Mädchen;Girl;3;dziewczynka
das Nachthemd;die Nachthemden;Nightgown;4;Koszula nocna
das Nasenloch;die Nasenlöcher;Nostril;4;Nozdrze
das Netzwerk;die Netzwerke;Network;4;Sieć
das Objekt;die Objekte;Object;3;Obiekt
das Ohr;die Ohren;Ear;1;ucho
das Opfer;die Opfer;Victim;2;Ofiara
das Paar;die Paare;Pair;1;para
das Paket;die Pakete;Package;2;paczka
das Paradies;die Paradiese;Paradise;4;raj
das Personal;die Personnels;Personnel;4;Personel
das Pferd;die Pferde;Horse;2;koń
das Pflaster;die Pflaster;Plaster;4;Gips
das Pfund;die Pfunde;Pound;2;Funt
das Phänomen;die Phänomene;Phenomenon;4;Zjawisko
das Picknick;die Picknicks;Picnic;4;Piknik
das Plakat;die Poster;Poster;3;Plakat
das Porträt;die Porträts;Portrait;3;Portret
das Produkt;die Produkte;Product;3;Produkt
das Profil;die Profile;Profile;3;Profil
das Programm;die Programme;Program;4;Program
das Publikum;die Publikum;Audience;4;Publiczność
das Pulver;die Pulver;Powder;3;Proszek
das Quadrat;die Quadrate;Square;3;Kwadrat
das Rad;die Räder;Wheel;1;koło
das Rasiermesser;die Rasierer;Razor;4;Brzytwa
das Recht;die Rechte;Right;2;prawo
das Regal;die Regale;Shelf;2;regał
das Reich;die Reiche;Empire;2;Imperium
das Rennen;die Rennen;Race;3;Wyścigi
das Rezept;die Rezepte;Recipe;3;Przepis
das Rindfleisch;die Rindfleische;Beef;4;wołowina
das Risiko;die Risiken;Risk;3;Ryzyko
das Rohr;die Röhren;Pipe;1;Rura
das Rotkehlchen;die Rotkehlchen;Robin;4;Rudzik
das Salz;die Salze;Salt;1;sól
das Schaf;die Schafe;Sheep;2;Owce
das Scharnier;die Scharniere;Hinge;4;Zawias
das Schicksal;die Schicksale;Fate;4;Los
das Schiff;die Schiffe;Ship;3;statek
das Schlafzimmer;die Schlafzimmer;Bedroom;4;sypialnia
das Schlagen;die Schläge;Beating;4;Bicie
das Schließfach;die Schließfächer;Locker;4;Szafka
das Schloss;die Schlösser;Lock;3;Zamek
das Schlurfen;die Shufflings;Shuffling;4;Shuffling.
das Schnäppchen;die Schnäppchen;Bargain;4;Okazja
das Schreiben;die Schriften;Writing;4;Pismo
das Schwein;die Schweine;Pig;3;świnia
das Schwert;die Schwerter;Sword;3;Miecz
das Schwimmen;die Swimming;Swimming;4;Pływanie
das Segel;die Segel;Sail;2;Żagiel
das Seil;die Seile;Rope;1;lina
das Silber;die Silber;Silver;3;srebro
das Skelett;die Skelette;Skeleton;3;Szkielet
das Sonnenlicht;die Sunlights;Sunlight;4;Światło słoneczne
das Spannfutter;die Spann;Chuck;4;Gdakanie
das Speicher;die Speicher;Storage;4;Składowanie
das Spiel;die Spiele;Game;2;Gra
das Spielzeug;die Spielzeuge;Toy;4;Zabawka
das Sprichwort;die Sprüche;Saying;4;Powiedzenie
das Staub;die Stäube;Dust;2;Pył
das Stirnrunzeln;die Stirn Runzelt;Frown;4;Marszczyć brwi
das Stöhnen;die Stöhnen;Groan;3;Jęk
das Stück;die Stücke;Piece;2;kawałek
das Szenario;die Szenarien;Scenario;4;Scenariusz
das Tagebuch;die Tagebücher;Diary;4;Dziennik
das Tal;die Täler;Valley;1;Dolina
das Taschentuch;die Taschentücher;Handkerchief;4;chusteczka
das Telefon;die Telefone;Phone;3;telefon
das Teleskop;die Teleskope;Telescope;4;Teleskop
das Thema;die Themen;Topic;2;Temat
das Tier;die Tiere;Animal;1;zwierze
das Treppenhaus;die Treppenhäuser;Staircase;4;Klatka schodowa
das Trikot;die Trikots;Jersey;3;Golf
das Unbehagen;die Unbehagen;Discomfort;4;Dyskomfort
das Universum;die Universen;Universe;4;Wszechświat
das Unkraut;die Unkräuter;Weed;3;Chwast
das Unternehmen;die Unternehmen;Enterprise;4;Przedsiębiorstwo
das Urteil;die Urteile;Judgment;3;Osąd
das Verbrechen;die Verbrechen;Crime;4;przestępstwo
das Verfahren;die Verfahren;Procedure;4;Procedura
das Verhalten;die Verhalten;Behavior;4;Zachowanie
das Versprechen;die Versprechen;Promise;4;Obietnica
das Vertrauen;die Vertrauen;Confidence;4;Zaufanie
das Viertel;die Viertel;Quarter;3;Jedna czwarta
das Violett;die Veilchen;Violet;3;Fioletowy
das Volk;die Völker;People;1;Ludzie
das Volumen;die Volumina;Volume;3;Tom
das Wachs;die Wachse;Wax;2;Wosk
das Wachstum;die Wachstum;Growth;4;Wzrost
das Wandern;die Wandern;Walk;3;Spacerować
das Warten;die Warten;Wait;3;Czekać
das Waschbecken;die Waschbecken;Sink;4;Tonąć
das Wasser;die Wasser;Water;3;woda
das Weibchen;die Weibchen;Female;4;Płeć żeńska
das Weihnachtslied;die Weihnachtslieder;Carol;4;kolęda
das Weiß;die Weißen;White;1;biały
das Werkzeug;die Werkzeuge;Tool;4;Narzędzie
das Wetter;die Wetter;Weather;3;pogoda
das Willkommen;die Willkommen;Welcome;4;Witamy
das Wochenende;die Wochenenden;Weekend;4;Weekend
das Wohl;die Willen;Sake;1;Wzgląd
das Wort;die Worte;Word;1;słowo
das Wrack;die Wracks;Wreck;2;Wrak
das Wunder;die Wunder;Wonder;3;Zastanawiać się
das Wörterbuch;die Wörterbücher;Dictionary;4;słownik
das Zelt;die Zelte;Tent;1;Namiot
das Zentrum;die Zentren;Center;3;centrum
das Zeugnis;die Zeugnisse;Testimony;3;Świadectwo
das Ziel;die Ziele;Target;1;cel
das Zifferblatt;die Zifferblätter;Dial;4;Wybierz
das Zischen;die Zischt;Hiss;3;Syk
das Zittern;die Zittern;Shiver;3;Dreszcz
das Zusammentreffen;die Zufälle;Coincidence;4;Zbieg okoliczności
das Öl;die Öle;Oil;1;olej
der Abend;die Abende;Evening;2;wieczór
der Abstieg;die Abfahrten;Descent;3;Zejście
der Absturz;die Abstürze;Crash;3;Rozbić się
der Abzug;die Abzüge;Trigger;2;Cyngiel
der Adler;die Adler;Eagle;2;Orzeł
der Affe;die Affen;Monkey;1;Małpa
der Akzent;die Akzente;Accent;3;Akcent
der Albtraum;die Alpträume;Nightmare;4;Koszmar
der Alkohol;die Alkohole;Alcohol;3;alkohol
der Anfang;die Anfänge;Beginning;3;początek
der Angriff;die Angriffe;Attack;3;Atak
der Anhänger;die Anhänger;Trailer;4;Zwiastun filmu
der Anruf;die Anrufe;Call;2;Połączenie
der Anrufer;die Anrufer;Caller;3;dzwoniący
der Ansager;die Ansager;Announcer;3;Spiker
der Ansatz;die Ansätze;Approach;3;Zbliżać się
der Anspruch;die Ansprüche;Claim;4;pretensja, roszczenie
der Anstieg;die Anstiege;Climb;3;Wspiąć się
der Anwalt;die Anwälte;Lawyer;3;Prawnik
der Anzug;die Anzüge;Suit;2;garnitur
der Appetit;die Appetit;Appetite;3;apetyt
der Arbeiter;die Arbeiter;Worker;4;Pracownik
der Arbeitgeber;die Arbeitgeber;Employer;4;Pracodawca
der Angestellte;die Angestellten;Employee;4;zatrudniony
der Artikel;die Artikel;Article;3;Artykuł
der Aschenbecher;die Aschenbecher;Ashtray;4;Popielniczka
der Assistent;die Assistenten;Assistant;4;Asystent
der Atem;die Atem;Breath;1;Oddech
der Attentäter;die Attentäter;Assassin;4;Morderca
der Aufenthalt;die Aufenthalte;Stay;4;Zostać
der Aufgang;die Aufgänge;Rise;3;Podwyżka
der Aufprall;die Aufpralle;Impact;4;Uderzenie
der Aufsatz;die Aufsätze;Essay;3;Praca pisemna
der Aufwand;die Aufwände;Effort;3;Wysiłek
der Aufzug;die Aufzüge;Elevator;3;Winda
der Ausdruck;die Ausdrücke;Expression;4;Wyrażenie
der Ausgang;die Ausgänge;Exit;3;wyjście
der Ausländer;die Ausländer;Foreigner;4;Cudzoziemiec
der Autor;die Autoren;Author;2;Autor
der Bach;die Bäche;Creek;1;zatoczka
der Bademantel;die Bademäntel;Bathrobe;4;Szlafrok
der Baldachin;die Baldachine;Canopy;4;Daszek
der Balkon;die Balkone;Balcony;3;Balkon
der Ballon;die Ballons;Balloon;3;Balon
der Barbier;die Barbiere;Barber;3;Fryzjer
der Barkeeper;die Barkeeper;Bartender;4;Barman
der Bart;die Bärte;Beard;1;broda
der Bauch;die Bäuche;Belly;2;Brzuch
der Bauer;die Bauern;Farmer;2;Rolnik
der Bauernhof;die Bauernhöfe;Farm;4;gospodarstwo rolne
der Baum;die Bäume;Tree;1;drzewo
der Becher;die Becher;Mug;3;Kubek
der Befehl;die Befehle;Command;3;Komenda
der Begriff;die Begriffe;Term;3;Semestr
der Bereich;die Bereiche;Range;3;Zasięg
der Berg;die Berge;Mountain;1;góra
der Bergmann;die Bergleute;Miner;4;Górnik
der Beruf;die Berufe;Profession;2;Zawód
der Besen;die Besen;Broom;2;miotła
der Besuch;die Besuche;Visit;3;Odwiedzać
der Besucher;die Besucher;Visitor;4;odwiedzający
der Beton;die Betone;Concrete;2;Beton
der Betreiber;die Betreiber;Operator;4;Operator
der Beweis;die Beweise;Evidence;3;Dowód
der Bewohner;die Bewohner;Resident;4;Mieszkaniec
der Bischof;die Bischöfe;Bishop;3;Biskup
der Biss;die Bisse;Bite;1;Ugryzienie
der Blick;die Blicke;Gaze;2;Spojrzenie
der Blitz;die Blitze;Flash;2;Lampa błyskowa
der Bluterguss;die Blutergüsse;Bruise;4;Siniak
der Boden;die Böden;Floor;2;ziemia
der Bogen;die Bögen;Bow;2;Kokarda
der Bogenschütze;die Bogenschützen;Archer;4;Łucznik
der Bohrer;die Bohrer;Drill;3;Wiertarka
der Bolzen;die Bolzen;Bolt;3;Śruba
der Bote;die Boten;Messenger;1;Posłaniec
der Botschafter;die Botschafter;Ambassador;4;Ambasador
der Brief;die Briefe;Letter;2;list
der Bruder;die Brüder;Brother;3;brat
der Brunnen;die Brunnen;Fountain;3;studnia
der Bulle;die Bullen;Bull;2;Byk
der Busch;die Büsche;Bush;2;Krzak
der Bäcker;die Bäcker;Baker;3;piekarz
der Bär;die Bären;Bear;1;niedźwiedź
der Bücherladen;die Bücherladen;Bookstore;4;Księgarnia
der Büffel;die Büffel;Buffalo;3;Bawół
der Bürger;die Bürger;Citizen;3;Obywatel
der Bürgermeister;die Bürgermeister;Mayor;4;Burmistrz
der Bürgersteig;die Bürgersteige;Sidewalk;4;Chodnik
der Champagner;die Champagner;Champagne;4;szampan
der Charakter;die Charaktere;Character;4;Postać
der Chirurg;die Chirurgen;Surgeon;3;Chirurg
der Chor;die Chöre;Chorus;1;Chór
der Dachboden;die Dachböden;Attic;4;Strych
der Damm;die Dämme;Dam;1;Zapora
der Dampf;die Dämpfe;Steam;2;Parowy
der Datensatz;die Datensätze;Record;4;Nagrywać
der Daumen;die Daumen;Thumb;3;kciuk
der Deckel;die Deckel;Lid;3;Pokrywa
der Dekan;die Dekane;Dean;2;Dziekan
der Delfin;die Delphine;Dolphin;3;Delfin
der Detektiv;die Detektive;Detective;4;Detektyw
der Deutsche;die Deutschen;German;4;Niemiecki
der Diakon;die Diakone;Deacon;3;Diakon
der Dialog;die Dialoge;Dialogue;3;Dialog
der Diamant;die Diamanten;Diamond;3;Diament
der Dieb;die Diebe;Thief;1;Złodziej
der Diener;die Diener;Servant;3;Sługa
der Dinosaurier;die Dinosaurier;Dinosaur;4;Dinozaur
der Direktor;die Direktoren;Director;4;Dyrektor
der Doktor;die Doktoren;Doctor;3;Lekarz
der Dolch;die Dolche;Dagger;2;Sztylet
der Donner;die Donner;Thunder;3;grzmot
der Doppelgänger;die Doppelgänger;Double;4;Podwójnie
der Dorfbewohner;die Dorfbewohner;Villager;4;Wieśniak
der Dorn;die Dornen;Thorn;1;Cierń
der Drache;die Drachen;Dragon;3;smok
der Dreck;die Dirts;Dirt;2;Brud
der Druck;die Drücke;Pressure;2;Nacisk
der Dschungel;die Dschungel;Jungle;4;Dżungla
der Duft;die Düfte;Scent;1;aromat, woń
der Durchgang;die Durchgänge;Passage;4;Przejście
der Dämon;die Dämonen;Demon;2;Demon
der Efeu;die Efeu;Ivy;1;Bluszcz
der Effekt;die Effekte;Effect;3;Efekt
der Ehemann;die Ehemänner;Husband;3;mąż
der Eimer;die Eimer;Bucket;2;Wiaderko
der Eindringling;die Eindringlinge;Intruder;4;Intruz
der Eindruck;die Eindrücke;Impression;4;Wrażenie
der Einfluss;die Einflüsse;Influence;4;Wpływ
der Einheimische;die Eingeborenen;Native;4;Rodzinny
der Einsatz;die Einsätze;Stake;3;Stawka
der Eintopf;die Eintöpfe;Stew;3;Gulasz
der Eintritt;die Einträge;Entry;4;Wejście
der Einwand;die Einwände;Objection;3;Sprzeciw
der Ekel;die Ekelt;Disgust;1;Niesmak
der Elefant;die Elefanten;Elephant;3;słoń
der Ellbogen;die Ellbogen;Elbow;4;łokieć
der Empfänger;die Empfänger;Receiver;4;Odbiorca
der Engel;die Engel;Angel;2;Anioł
der Enkel;die Enkel;Grandchild;2;Wnuczkek
der Entwurf;die Entwürfe;Draft;3;Projekt
der Erbe;die Erben;Heir;1;Dziedzic
der Erfolg;die Erfolge;Success;3;Powodzenie
der Ermittler;die Ermittler;Investigator;4;Badacz
der Erwachsene;die Erwachsenen;GrownUp;4;Dorosły
der Erzähler;die Erzähler;Narrator;4;Narrator
der Esel;die Esel;Ass;1;osioł
der Experte;die Experten;Expert;3;Ekspert
der Faden;die Fäden;Thread;2;nić
der Fahrer;die Fahrer;Driver;3;Kierowca
der Faktor;die Faktoren;Factor;3;Czynnik
der Fall;die Fälle;Case;1;przypadek
der Fang;die Fänge;Catch;1;Łapać
der Farbton;die Farbtöne;Hue;3;barwa
der Favorit;die Favoriten;Favorite;3;Ulubiony
der Fehler;die Fehler;Mistake;3;błąd
der Feier;die Feiern;Celebration;2;Uroczystość
der Feigling;die Feiglinge;Coward;4;tchórz
der Feind;die Feinde;Enemy;2;wróg
der Fingernagel;die Fingernägel;Fingernail;4;Paznokieć
der Fisch;die Fische;Fish;2;Ryba
der Fischer;die Fischer;Fisherman;3;Rybak
der Fleck;die Flecken;Stain;2;Plama
der Fluch;die Flüche;Curse;2;Przekleństwo
der Flug;die Flüge;Flight;1;Lot
der Flughafen;die Flughäfen;Airport;4;lotnisko
der Flur;die Flure;Hallway;1;Korytarz
der Fluss;die Flüsse;River;2;rzeka
der Flüchtling;die Flüchtlinge;Refugee;4;Uchodźca
der Flügel;die Flügel;Wing;3;Skrzydło
der Fortschritt;die Fortschritte;Progress;4;Postęp
der Fotograf;die Fotografen;Photographer;4;Fotograf
der Fremde;die Fremden;Stranger;3;Nieznajomy
der Freund;die Freunde;Friend;3;przyjacieł
der Friedhof;die Friedhöfe;Cemetery;4;Cmentarz
der Frosch;die Frösche;Frog;3;Żaba
der Frühling;die Federn;Spring;4;wiosna
der Fuchs;die Foxs;Fox;2;lis
der Fuhrmann;die Fuhr;Carter;4;Furman
der Funke;die Funken;Spark;2;Iskra
der Fuß;die Füße;Foot;1;Stopa
der Fußball;die Fußbälle;Football;3;Piłka nożna
der Führer;die Führer;Leader;3;Lider
der Gang;die Gänge;Aisle;1;Nawa
der Garten;die Gärten;Garden;3;ogród
der Gast;die Gäste;Guest;1;Gość
der Gastgeber;die Gastgeber;Host;4;Gospodarz
der Geburtstag;die Geburtstage;Birthday;4;urodziny
der Gedanke;die Gedanken;Thought;3;Myśl
der Gefangene;die Gefangenen;Prisoner;4;Więzień
der Gegenstand;die Gegenstände;Item;4;Przedmiot
der Gegner;die Gegner;Opponent;3;Przeciwnik
der Gehweg;die Gehwege;Walkway;3;ścieżka
der Geist;die Gemüter;Mind;2;Umysł
der Geldbeutel;die Geldbeutel;Purse;4;Portmonetka
der Gelehrte;die Gelehrten;Scholar;4;Uczony
der Genosse;die Genossen;Comrade;3;Towarzysz
der Geruch;die Gerüche;Smell;3;Zapach
der Gesang;die Gesänge;Singing;3;Śpiewanie
der Geschmack;die Geschmäcker;Taste;4;Smak
der Gestank;die Gestank;Stench;3;Smród
der Gewinn;die Gewinne;Profit;3;Zysk
der Gewinner;die Gewinner;Winner;4;Zwycięzca
der Glaube;die Glauben;Faith;3;Wiara
der Gott;die Götter;God;1;bóg
der Gouverneur;die Gouverneure;Governor;4;Gubernator
der Graben;die Gräben;Ditch;3;Rów
der Grad;die Grade;Degree;1;stopień
der Graf;die Grafen;Earl;1;Hrabia
der Granit;die Granite;Granite;3;Granit
der Grat;die Grate;Ridge;1;Grzbiet
der Grieche;die Griechen;Greek;3;grecki
der Griff;die Griffe;Grip;2;Chwyt
der Großvater;die Großväter;Grandfather;4;Dziadek
der Grund;die Gründe;Reason;2;powód
der Gurt;die Gurte;Strap;1;pas
der Gürtel;die Gürtel;Belt;3;Pasek
der Hafen;die Häfen;Harbor;2;Port
der Hai;die Haie;Shark;1;Rekin
der Hain;die Haine;Grove;1;Gaj
der Haken;die Haken;Hook;2;Hak
der Hals;die Hälse;Neck;1;szyja
der Handel;die Händel;Trade;3;Handel
der Handschuh;die Handschuhe;Glove;4;Rękawica
der Hase;die Hasen;Rabbit;1;Królik
der Hass;die Hass;Hatred;1;Nienawiść
der Haushalt;die Haushalte;Household;4;Gospodarstwo domowe
der Hecht;die Hechte;Pike;2;Szczupak
der Heilige;die Heiligen;Saint;3;Święty
der Held;die Helden;Hero;1;Bohater
der Helm;die Helme;Helmet;1;Kask
der Herbst;die Herbste;Autumn;3;jesień
der Herzog;die Herzöge;Duke;3;Książę
der Herzschlag;die Herzschläge;Heartbeat;4;Bicie serca
der Himmel;die Himmel;Sky;3;niebo
der Hinter;die Hintern;Rear;3;Tył
der Hintergrund;die Hintergründe;Background;4;Tło
der Hinweis;die Hinweise;Hint;3;Wskazówka
der Hirte;die Hirten;Shepherd;2;Pasterz
der Hof;die Höfe;Courtyard;1;Dziedziniec
der Honig;die Honige;Honey;2;Miód
der Horizont;die Horizonte;Horizon;4;Horyzont
der Hubschrauber;die Hubschrauber;Helicopter;4;Śmigłowiec
der Huf;die Hufe;Hoof;1;Kopyto
der Hund;die Hunde;Dog;1;pies
der Hurrikan;die Hurrikane;Hurricane;4;Huragan
der Hut;die Hüte;Hat;1;kapelusz
der Händler;die Händler;Dealer;3;Kupiec
der Hügel;die Hügel;Hill;2;Wzgórze
der Impuls;die Impulse;Impulse;3;Impuls
der Ingenieur;die Ingenieure;Engineer;4;Inżynier
der Ingwer;die Ingwer;Ginger;3;Imbir
der Inhalt;die Inhalte;Content;3;Zadowolony
der Innenraum;die Innenräume;Interior;4;Wnętrze
der Inspektor;die Inspektoren;Inspector;4;Inspektor
der Instinkt;die Instinkte;Instinct;4;Instynkt
der Jahrestag;die Jahrestage;Anniversary;4;Rocznica
der Jasmin;die Jasmin;Jasmine;3;Jaśmin
der Jäger;die Jäger;Hunter;2;Łowca
der Kabelbaum;die Kabelbäume;Harness;4;Uprząż
der Kaffee;die Kaffee;Coffee;3;kawa
der Kaiser;die Kaiser;Emperor;3;cesarz
der Kalender;die Kalender;Calendar;4;Kalendarz
der Kamin;die Kamine;Fireplace;2;Kominek
der Kamm;die Kämme;Comb;1;grzebień
der Kampf;die Kämpfe;Fight;2;Bić się
der Kanal;die Kanäle;Channel;2;Kanał
der Kandidat;die Kandidaten;Candidate;4;Kandydat
der Kapitän;die Kapitäne;Captain;3;Kapitan
der Kauf;die Käufe;Purchase;1;Zakup
der Keks;die Kekse;Cookie;1;Ciastko
der Keller;die Keller;Basement;3;piwnica
der Kellner;die Kellner;Waiter;3;kelner
der Kerl;die Kerle;Guy;1;Facet
der Kern;die Kerne;Core;1;Rdzeń
der Kies;die Kiese;Gravel;1;Żwir
der Klick;die Klicks;Click;2;Kliknij
der Klumpen;die Klumpen;Lump;3;Bryła
der Knochen;die Knochen;Bone;3;kość
der Knopf;die Knöpfe;Button;2;guzik
der Knoten;die Knoten;Knot;3;Węzeł
der Knöchel;die Knöchel;Ankle;3;kostka
der Koch;die Köche;Cook;1;kocharz
der Koffer;die Koffer;Suitcase;3;Walizka
der Kojote;die Kojoten;Coyote;3;Kojot
der Koks;die Kokse;Coke;1;Koks
der Kollege;die Kollegen;Colleague;3;Współpracownik
der Kommandant;die Kommandeure;Commander;4;Dowódca
der Kommentar;die Kommentare;Comment;4;Komentarz
der Konflikt;die Konflikte;Conflict;4;Konflikt
der Kontakt;die Kontakte;Contact;3;Kontakt
der Kontext;die Kontexte;Context;3;Kontekst
der Kontinent;die Kontinente;Continent;4;Kontynent
der Konus;die Kegel;Cone;2;Stożek
der Kopf;die Köpfe;Head;1;głowa
der Kopfschmerz;die Kopfschmerzen;Headache;4;Bół głowy
der Korb;die Körbe;Basket;1;kosz
der Kragen;die Kragen;Collar;3;kołnierz
der Kran;die Kräne;Crane;1;Dźwig
der Krankenwagen;die Krankenwagen;Ambulance;4;Ambulans
der Krater;die Krater;Crater;3;Krater
der Krebs;die Krebs;Cancer;2;Nowotwór
der Kredit;die Kredite;Credit;3;Kredyt
der Kreis;die Kreise;Circle;2;okrąg
der Kreislauf;die Kreisläufe;Cycle;4;Cykl
der Kreuzer;die Kreuzer;Cruiser;3;Krążownik
der Krieg;die Kriege;War;2;Wojna
der Krieger;die Krieger;Warrior;3;Wojownik
der Kristall;die Kristalle;Crystal;4;Kryształ
der Kritiker;die Kritiker;Critic;4;Krytyk
der Krug;die Krüge;Pitcher;1;Dzban
der Kuchen;die Kuchen;Cake;3;placek
der Kunden;die Kunden;Customer;3;Klient
der Kunststoff;die Kunststoff;Plastic;4;Plastikowy
der Kurs;die Kurse;Course;1;kurs
der Kuss;die Küsse;Kiss;1;pocałunek
der Käfer;die Käfer;Beetle;2;Chrząszcz
der Käfig;die Käfige;Cage;2;Klatka szybowa
der Kämpfer;die Kämpfer;Fighter;3;zawodnik sportów walki
der Käse;die Käse;Cheese;1;Ser
der König;die Könige;King;2;król
der Körper;die Körper;Body;3;ciało
der Küchenchef;die Köche;Chef;4;Szef kuchni
der Kühler;die Kühler;Cooler;3;Chłodnica
der Kühlschrank;die Kühlschränke;Refrigerator;4;lodówka
der Kürbis;die Kürbisse;Pumpkin;3;Dynia
der Lachs;die Lachse;Salmon;2;Łosoś
der Lautsprecher;die Lautsprecher;Speaker;4;Głośnik
der Lavendel;die Lavendel;Lavender;4;Lawenda
der Lehrer;die Lehrer;Teacher;3;nauczyciel
der Leser;die Leser;Reader;2;Czytelnik
der Leutnant;die Leutnants;Lieutenant;4;Porucznik
der Liebhaber;die Liebhaber;Lover;4;Kochanek
der Liebling;die Lieblinge;Darling;4;kochanie
der Lippenstift;die Lippenstifte;Lipstick;4;Pomadka
der Lorbeer;die Lorbeeren;Laurel;3;Laur
der Läufer;die Läufer;Runner;3;Biegacz
der Löffel;die Löffel;Spoon;3;łyżka
der Löwe;die Löwen;Lion;1;Lew
der Lügner;die Lügner;Liar;3;kłamca
der Macher;die Macher;Maker;3;Producent
der Magier;die Magier;Mage;3;Mag
der Maler;die Maler;Painter;2;Malarz
der Mann;die Männer;Man;1;mężczyzna
der Mantel;die Mäntel;Coat;3;płaszcz
der Markt;die Märkte;Market;2;Rynek
der Marmor;die Murmeln;Marble;3;Marmur
der Marsch;die Märsche;March;3;Marsz
der Maulwurf;die Maulwürfe;Mole;4;Kret
der Maurer;die Maurer;Mason;3;Mason
der Mechaniker;die Mechanik;Mechanic;4;Mechanik
der Meister;die Meister;Master;3;mistrz
der Mensch;die Menschen;Human;3;człowiek
der Metzger;die Metzger;Butcher;3;rzeźnik
der Missbrauch;die Missbräuche;Abuse;4;Nadużywać
der Mitbewohner;die Mitbewohner;Roommate;4;Współlokator
der Modus;die Modi;Mode;2;Tryb
der Mohn;die Mohne;Poppy;1;mak
der Monat;die Monate;Month;2;miesiąc
der Mond;die Monde;Moon;1;księżyc
der Mord;die Morde;Murder;1;Morderstwo
der Morgen;die Morgen;Morning;3;ranek
der Motor;die Motoren;Engine;2;Silnik
der Mund;die Münder;Mouth;1;usta
der Musiker;die Musiker;Musician;3;Muzyk
der Muskel;die Muskeln;Muscle;3;Mięsień
der Mythos;die Mythen;Myth;3;Mit
der Mönch;die Mönche;Monk;2;Mnich
der Mörder;die Mörder;Killer;3;Zabójca
der Müller;die Müller;Miller;3;Młynarz
der Nachbar;die Nachbarn;Neighbor;3;sąsiad
der Nachmittag;die Nachmittage;Afternoon;4;popołudnie
der Nagel;die Nägel;Nail;2;gwóźdź
der Nebel;die Nebel;Fog;2;Mgła
der Neffe;die Neffen;Nephew;2;Siostrzeniec
der Nerv;die Nerven;Nerve;1;Nerw
der Nervenkitzel;die Nervenkitzel;Thrill;4;Dreszczyk
der Norden;die Norths;North;3;północ
der Oberst;die Obersten;Colonel;3;Pułkownik
der Obstgarten;die Obstgärten;Orchard;4;sad owocowy
der Offizier;die Offiziere;Officer;4;Oficer
der Ohrring;die Ohrringe;Earring;3;Kolczyk
der Onkel;die Onkel;Uncle;2;wuj
der Ort;die Orte;Place;1;miejsce
der Ozean;die Ozeane;Ocean;2;Ocean
der Palast;die Paläste;Palace;3;Pałac
der Papst;die Päpste;Pope;2;Papież
der Pass;die Pässe;Passport;1;paszport
der Passagier;die Passagiere;Passenger;4;Pasażer
der Passant;die Passanten;PasserBy;3;Przechodzień
der Pfannkuchen;die Pfannkuchen;Pancake;4;Naleśnik
der Pfarrer;die Pastoren;Reverend;3;Czcigodny
der Pfeffer;die Paprika;Pepper;3;Pieprz
der Pfeil;die Pfeile;Arrow;2;Strzałka
der Pferdeschwanz;die Pferdeschwänze;Ponytail;4;Koński ogon
der Pfirsich;die Pfirsiche;Peach;4;Brzoskwinia
der Pilger;die Pilger;Pilgrim;3;Pielgrzym
der Pilz;die Pilze;Mushroom;1;Grzyb
der Pinguin;die Pinguine;Penguin;3;Pingwin
der Pirat;die Piraten;Pirate;2;Pirat
der Plattenteller;die Platten;Platter;4;Talerz
der Platz;die Plätze;Plaza;2;miejsce do siedzenia
der Pol;die Pole;Pole;1;Polak
der Politiker;die Politiker;Politician;4;Polityk
der Polizist;die Polizisten;Cop;4;Policjant
der Prediger;die Prediger;Preacher;4;Kaznodzieja
der Preis;die Preise;Price;2;cena
der Priester;die Priester;Priest;4;Kapłan
der Privatsphäre;die Privatsphären;Privacy;4;Prywatność
der Prozess;die Prozesse;Process;3;Proces
der Präsident;die Präsidenten;President;4;Prezydent
der Psychiater;die Psychiater;Psychiatrist;4;Psychiatra
der Pullover;die Pullover;Sweater;4;Sweter
der Punkt;die Punkte;Point;2;Punkt
der Rabe;die Raben;Raven;1;Kruk
der Rahmen;die Rahmen;Frame;3;Rama
der Rang;die Reihen;Rank;1;Ranga
der Rasen;die Rasen;Lawn;2;Trawnik
der Rat;die Räte;Council;1;rada
der Ratschlag;die Ratschläge;Advice;4;porada
der Rauch;die Raucht;Smoke;2;Palić
der Raum;die Räume;Space;1;Przestrzeń
der Rebell;die Rebellen;Rebel;3;Buntownik
der Rechtsmittelgrund;die Rechtsmittelgründe;Plea;4;Zarzut
der Regen;die Regen;Rain;2;deszcz
der Regenbogen;die Regenbogen;Rainbow;4;Tęcza
der Reichtum;die Reichtümer;Wealth;4;Bogactwo
der Reiniger;die Reiniger;Cleaner;4;Odkurzacz
der Reis;die Reis;Rice;1;Ryż
der Reisende;die Reisenden;Traveler;4;Podróżny
der Rhythmus;die Rhythmen;Rhythm;4;Rytm
der Richter;die Richter;Judge;3;Sędzia
der Riss;die Risse;Crack;1;Pękać
der Ritter;die Ritter;Knight;3;Rycerz
der Roboter;die Roboter;Robot;3;Robot
der Rock;die Röcke;Skirt;1;spódnica
der Rollstuhl;die Rollstühle;Wheelchair;4;Wózek inwalidzki
der Roman;die Romane;Novel;2;Powieść
der Rubin;die Rubinen;Ruby;2;Rubin
der Rucksack;die Rucksäcke;Backpack;4;Plecak
der Ruf;die Rufe;exclamation;1;okrzyk
der Rumpf;die Rümpfe;Hull;2;kadłub
der Russe;die Russen;Russian;2;Rosyjski
der Rücken;die Rücken;Back;3;plecy
der Rücksitz;die Rücksitze;Backseat;4;Tylne siedzenie
der Saft;die Säfte;Juice;1;sok
der Salat;die Salate;Salad;2;sałatka
der Sarg;die Särge;Coffin;1;Trumna
der Satellit;die Satelliten;Satellite;4;Satelita
der Sattel;die Sättel;Saddle;3;Siodło
der Satz;die Sätze;Set;1;Ustawić
der Saum;die Säume;Hem;1;Brzeg
der Schaden;die Schäden;Damage;3;Szkoda
der Schal;die Schals;Scarf;2;Szalik
der Schalter;die Schalter;Switch;4;Przełącznik
der Schatten;die Schatten;Shadow;4;cień
der Schatz;die Schätze;Treasure;3;Skarb
der Schaum;die Schäume;Foam;3;Pianka
der Scheinwerfer;die Scheinwerfer;Headlight;4;Reflektor
der Schinken;die Schinken;Ham;4;szynka
der Schlaf;die Schlaf;Sleep;3;Spać
der Schlag;die Schläge;Blow;3;Cios
der Schlamm;die Schlämme;Mud;3;Błoto
der Schlauch;die Schläuche;Hose;4;Wąż gumowy
der Schleier;die Schleier;Veil;4;Welon
der Schlepper;die Schlepper;Tug;4;Holownik
der Schlitz;die Schlitze;Slot;3;Otwór
der Schläger;die Schläger;Thug;4;Bandyta
der Schlüssel;die Schlüssel;Key;4;klucz
der Schmerz;die Schmerzen;Pain;3;Ból
der Schmetterling;die Schmetterlinge;Butterfly;4;motyl
der Schmuck;die Schmuck;Jewelry;3;Biżuteria
der Schnabel;die Schnäbel;Beak;4;Dziób
der Schnee;die Schnee;Snow;3;śnieg
der Schnitt;die Schnitte;Cut;3;Skaleczenie
der Schnittpunkt;die Schnittpunkte;Intersection;4;Skrzyżowanie
der Schnurrbart;die Schnurrbärte;Mustache;4;Wąsy
der Schock;die Schocks;Shock;3;Zaszokować
der Schornstein;die Schornsteine;Chimney;4;Komin
der Schrank;die Schränke;Closet;3;szafa
der Schrecken;die Schrecken;Terror;4;Terror
der Schrei;die Schreie;Scream;3;Krzyk
der Schreibtisch;die Schreibtische;Desk;4;Biurko
der Schritt;die Schritte;Step;3;Krok
der Schuh;die Schuhe;Shoe;2;but
der Schuppen;die Schuppen;Shed;4;Szopa
der Schuss;die Schüsse;Shot;3;Strzał
der Schutz;die Schutz;Protection;3;Ochrona
der Schwan;die Schwäne;Swan;3;Łabędź
der Schweif;die Schwänze;Tail;3;Ogon
der Schwimmer;die Schwimmer;Float;4;Pływak
der Schädel;die Schädel;Skull;3;Czaszka
der Schüler;die Schüler;Pupil;3;Uczeń
der See;die Seen;Lake;1;jezioro
der Segen;die Segen;Blessing;2;Błogosławieństwo
der Sekretär;die Sekretäre;Secretary;4;Sekretarz
der Sessel;die Sessel;Armchair;3;fotel
der Seufzer;die Sighes;Sigh;3;Westchnienie
der Sieg;die Siege;Victory;1;Zwycięstwo
der Sieger;die Sieger;Victor;3;triumpfator
der Sinn;die Sinne;Sense;1;Sens
der Smaragd;die Smaragde;Emerald;3;Szmaragd
der Sohn;die Söhne;Son;1;syn
der Soldat;die Soldaten;Soldier;3;Żołnierz
der Sommer;die Sommer;Summer;3;lato
der Sonnenaufgang;die Sonnenaufgang;Sunrise;4;wschód słońca
der Sonnenschein;die Sonne Scheint;Sunshine;4;Światło blask
der Sonnenuntergang;die Sonne Geht Unter;Sunset;4;Zachód słońca
der Spatz;die Spatzen;Sparrow;2;Wróbel
der Speck;die Speck;Bacon;2;słonina
der Speer;die Speere;Spear;2;Włócznia
der Spiegel;die Spiegel;Mirror;3;lustro
der Spieler;die Spieler;Player;3;Gracz
der Spielplatz;die Spielplätze;Playground;4;Plac zabaw
der Spieß;die Spieße;Spit;2;Pluć
der Spion;die Spione;Spy;2;Szpieg
der Spitzname;die Spitznamen;Nickname;4;Przezwisko
der Spritz;die Spritzer;Splash;3;Pluśnięcie
der Sprung;die Sprünge;Jump;3;Skok
der Staat;die Staaten;State;2;Stan
der Stahl;die Stähle;Steel;2;stal
der Stamm;die Stämme;Tribe;2;Plemię
der Stapel;die Stapel;Stack;3;Stos
der Star;die Stare;Starling;1;Szpak
der Start;die Starts;Launch;2;start
der Stein;die Steine;Stone;2;kamień
der Stern;die Sterne;Star;2;gwiazda
der Stich;die Stiche;Pang;2;Ostry ból
der Stift;die Stifte;Pen;2;Długopis
der Stil;die Stile;Style;1;Styl
der Stock;die Stöcke;Stick;2;Kij
der Strahl;die Strahlen;Ray;3;Promień
der Strand;die Strände;Beach;3;plaża
der Streifen;die Streifen;Strip;4;Rozebrać się
der Streik;die Streiks;Strike;3;Strajk
der Strom;die Ströme;Stream;2;Strumień
der Strumpf;die Strümpfe;Stocking;3;Pończocha
der Stuhl;die Stühle;Chair;2;krzesło
der Stumpf;die Stümpfe;Stump;3;Kikut
der Sturm;die Stürme;Storm;2;burza
der Sumpf;die Sümpfe;Swamp;2;Bagno
der Supermarkt;die Supermärkte;Supermarket;4;Supermarket
der Sänger;die Sänger;Singer;3;Piosenkarz
der Süden;die Souths;South;2;południe
der Tag;die Tagen;Day;1;dzień
der Tanz;die Tänze;Dance;1;Taniec
der Techniker;die Techniker;Technician;4;Technik
der Tee;die Tees;Tea;1;herbata
der Teich;die Teiche;Pond;2;Staw
der Teig;die Teige;Dough;1;Ciasto
der Teil;die Teile;Part;1;cześć
der Tempel;die Tempel;Temple;3;Świątynia
der Teppich;die Teppiche;Carpet;3;dywan
der Termin;die Termine;Appointment;3;Spotkanie
der Teufel;die Teufel;Fuck;3;Pierdolić
der Therapeut;die Therapeuten;Therapist;4;Terapeuta
der Thron;die Throne;Throne;2;Tron
der Tierarzt;die Tierärzte;Vet;4;Weterynarz
der Tisch;die Tische;Table;2;stół
der Tod;die Tode;Death;1;Śmierć
der Ton;die Töne;Tone;1;Ton
der Topf;die Töpfe;Pot;1;garnek
der Trainer;die Trainer;Coach;3;Trener
der Traktor;die Traktoren;Tractor;3;Ciągnik
der Traum;die Träume;Dream;2;sen
der Truthahn;die Truthähne;Turkey;4;indyk
der Träger;die Träger;Carrier;3;Przewoźnik
der Turm;die Türme;Tower;1;wieża
der Typ;die Typen;Type;1;Rodzaj
der Umfang;die Umfänge;Perimeter;3;Obwód
der Umhang;die Umhänge;Cape;3;Peleryna
der Umriss;die Umrisse;Outline;3;Zarys
der Umschlag;die Umschläge;Envelope;4;Koperta
der Umstand;die Umstände;Circumstance;3;Okoliczność
der Unfall;die Unfälle;Accident;3;wypadek
der Unglaube;die Unglauben;Disbelief;4;Niedowierzanie
der Unsinn;die Unsinn;Nonsense;3;Nonsens
der Unterarm;die Unterarme;Forearm;4;Przedramię
der Unterschied;die Unterschiede;Difference;4;Różnica
der Urheberrechts;die Urheberrechte;Copyright;4;prawa autorskie
der Urlaub;die Urlaub;Vacation;3;Wakacje
der Ursprung;die Ursprünge;Origin;4;pochodzenie
der Vampir;die Vampire;Vampire;3;Wampir
der Vater;die Väter;Father;2;ojciec
der Verband;die Verbände;Dressing;3;Ubieranie się
der Verbündete;die Verbündeten;Ally;4;Sprzymierzyć
der Verdacht;die Verdachte;Suspicion;4;Podejrzenie
der Verdächtige;die Verdächtigen;Suspect;4;Podejrzany
der Vergleich;die Vergleiche;Comparison;4;Porównanie
der Vergnügungspark;die Vergnügungen;Amusement;4;Rozrywka
der Verkauf;die Verkäufe;Sale;3;Sprzedaż
der Verkehr;die Verkehre;Traffic;3;Ruch drogowy
der Verlag;die Verleger;Publisher;3;Wydawca
der Verlierer;die Verlierer;Loser;4;Nieudacznik
der Verlust;die Verluste;Loss;3;Strata
der Verrat;die Verrate;Betrayal;3;Zdrada
der Vers;die Verse;Verse;1;Werset
der Versuch;die Versuche;Attempt;3;próba
der Vertrag;die Verträge;Contract;3;Kontrakt
der Vogel;die Vögel;Bird;2;ptak
der Vorfahr;die Vorfahren;Ancestor;3;Przodek
der Vorfall;die Vorfälle;Incident;3;Incydent
der Vorschlag;die Vorschläge;Suggestion;4;propozycja
der Vorteil;die Vorteile;Advantage;3;Korzyść
der Vortrag;die Vorträge;Lecture;3;Wykład
der Vorwurf;die Vorwürfe;Accusation;3;Oskarżenie
der Vulkan;die Vulkane;Volcano;3;Wulkan
der Wagen;die Wagen;Wagon;2;wóz
der Wal;die Wale;Whale;1;Wieloryb
der Wald;die Wälder;Forest;1;las
der Wanderer;die Wanderer;Walker;4;Piechur
der Wasserhahn;die Wasserhähne;Tap;4;Uzyskiwać
der Wecker;die Wecker;Alarm;3;budzik
der Weg;die Wege;Way;1;droga
der Wein;die Weine;Wine;1;wino
der Weise;die Weisen;Sage;2;szałwia
der Weizen;die Weizen;Wheat;3;Pszenica
der Welpe;die Welpen;Puppy;2;Szczeniak
der Wert;die Werte;Value;1;Wartość
der Westen;die Wests;West;3;zachód
der Wettbewerb;die Wettbewerbe;Contest;4;Konkurs
der Whisky;die Whiskys;Whiskey;3;Whisky
der Widerstand;die Widerstände;Resistance;4;Opór
der Winkel;die Winkel;Angle;3;Kąt, narożnik
der Wissenschaftler;die Wissenschaftler;Scientist;4;Naukowiec
der Witz;die Witze;Joke;1;Żart
der Wodka;die Wodkas;Vodka;2;wódka
der Wunsch;die Wünsche;Wish;3;Życzenie
der Wurf;die Würfe;Litter;1;Śmieci
der Wurm;die Würmer;Worm;1;Robak
der Wächter;die Wachen;Guard;3;Strażnik
der Würfel;die Würfel;Cube;3;Sześcian
der Zahnarzt;die Zahnärzte;Dentist;4;dentysta
der Zapfen;die Zapfen;Peg;3;Kołek
der Zauber;die Zauber;Spell;3;Zaklęcie
der Zauberer;die Zauberer;Wizard;4;Czarodziej
der Zaun;die Zäune;Fence;1;Ogrodzenie
der Zaunkönig;die Zaunkönige;Wren;4;Strzyżyk
der Zeigefinger;die Zeigefingern;Forefinger;4;Palec wskazujący
der Zement;die Zemente;Cement;3;Cement
der Zeuge;die Zeugen;Witness;2;Świadek
der Zigeuner;die Zigeuner;Gypsy;4;cygański
der Zimmermann;die Zimmerleute;Carpenter;4;stolarz
der Zirkus;die Zirkusse;Circus;3;Cyrk
der Zucker;die Zucker;Sugar;3;cukier
der Zug;die Züge;Train;1;pociąg
der Zuschuss;die Zuschüsse;Grant;4;Dotacja
der Zweifel;die Zweifel;Doubt;3;Wątpliwość
der Zweig;die Zweige;Twig;2;Gałązka
der Zwerg;die Zwerge;Dwarf;2;Krasnolud
der Zwilling;die Zwillinge;Twin;4;Bliźniak
der Zähler;die Zähler;Counter;3;Licznik
der Ältere;die Ältesten;Elder;3;Starszy
der Überlebende;die Überlebenden;Survivor;4;Niedobitek
der Übersetzer;die Übersetzer;Translator;4;Tłumacz
die Abfahrt;die Abfahrten;Departure;3;odjazd
die Ablenkung;die Ablenkungen;Distraction;4;Roztargnienie
die Absicht;die Absichten;Intention;3;Zamiar
die Abteilung;die Abteilungen;Department;4;dział
die Abwesenheit;die Abwesenheiten;Absence;4;Brak
die Adresse;die Adressen;Address;3;adres
die Agentur;die Agenturen;Agency;3;Agencja
die Akademie;die Akademien;Academy;4;Akademia
die Aktentasche;die Aktentaschen;Briefcase;4;Aktówka
die Aktion;die Aktionen;Action;3;Akcja
die Aktivität;die Aktivitäten;Activity;4;Działalność
die Aluminium;die Aluminums;Aluminum;4;Aluminium
die Ameise;die Ameisen;Ant;3;mrówka
die Amerikaner;die Amerikaner;American;4;amerykański
die Anderen;die Anderen;Others;3;Inni
die Anforderung;die Anfragen;Request;4;Wniosek
die Anhörung;die Anhörungen;Hearing;4;Przesłuchanie
die Anker;die Anker;Anchor;2;Kotwica
die Ankunft;die Ankünfte;Arrival;3;przybycie
die Ankündigung;die Ankündigungen;Announcement;4;Zapowiedź
die Anleitung;die Anleitungen;Instruction;4;Instrukcja
die Antennen;die Antennen;Antenna;4;Antena
die Antwort;die Antworten;Answer;3;odpowiedź
die Anzeige;die Anzeigen;Ad;3;Ogłoszenie
die Armee;die Armeen;Army;2;armia
die Art;die Arten;Kind;1;gatunek
die Asche;die Asche;Ash;2;Popiół
die Atmosphäre;die Atmosphären;Atmosphere;4;Atmosfera
die Attraktion;die Attraktionen;Attraction;4;Atrakcja
die Aufgabe;die Aufgaben;Task;3;zadanie
die Aufmerksamkeit;die Aufmerksamkeit;Attention;4;Uwaga
die Aufnahme;die Aufnahmen;Recording;4;Nagranie
die Aufregung;die Aufregungen;Excitement;4;Podniecenie
die Augenbraue;die Augenbrauen;Eyebrow;4;Brew
die Ausgabe;die Ausgaben;Edition;3;Wydanie
die Ausnahme;die Ausnahmen;Exception;4;Wyjątek
die Ausrüstung;die Ausrüstungen;Equipment;4;Ekwipunek
die Aussage;die Aussagen;Statement;3;Oświadczenie
die Aussicht;die Ansichten;View;4;Pogląd
die Auszeichnung;die Auszeichnungen;Award;4;wyróżnienie
die Autobahn;die Autobahnen;Highway;4;Autostrada
die Banane;die Bananen;Banana;3;banan
die Bank;die Bänke;Bench;1;ławkabank
die Barmherzigkeit;die Barmherzigkeit;Mercy;4;miłosierdzie
die Barriere;die Barrieren;Barrier;4;Bariera
die Batterie;die Batterien;Battery;4;Bateria
die Baumwolle;die Baumwollen;Cotton;4;Bawełna
die Bedeutung;die Bedeutungen;Meaning;4;Oznaczający
die Bedingung;die Bedingungen;Condition;4;warunek
die Beere;die Beeren;Berry;2;Jagoda
die Begegnung;die Begegnungen;Encounter;4;mecz
die Begeisterung;die Begeisterung;Enthusiasm;4;Entuzjazm
die Begnadigung;die Begnadigungen;Pardon;4;Pardon
die Behandlung;die Behandlungen;Treatment;4;Leczenie
die Beihilfen;die Beihilfen;Aid;4;pierwsza pomoc
die Bekanntschaft;die Bekannten;Acquaintance;4;Znajomy
die Beleidigung;die Beleidigungen;Insult;4;Znieważenie
die Beleuchtung;die Beleuchtung;Lighting;4;Oświetlenie
die Belohnung;die Belohnungen;Reward;4;Nagroda
die Bemerkung;die Bemerkungen;Remark;4;spostrzeżenie
die Beobachtung;die Beobachtungen;Observation;4;Obserwacja
die Bequemlichkeit;die Bequemlichkeiten;Convenience;4;Wygoda
die Berührung;die Berührungen;Touch;4;Dotykać
die Besatzung;die Besatzungen;Crew;4;Załoga
die Beschreibung;die Beschreibungen;Description;4;Opis
die Beschwerde;die Beschwerden;Complaint;4;Reklamacja
die Besorgung;die Besorgungen;Errand;4;sprawunek
die Bestimmung;die Bestimmungen;Determination;4;Determinacja
die Bestürzung;die Bestürzt;Dismay;4;Przerażenie
die Beute;die Beute;Prey;2;trofeum, zdobycz
die Bewegung;die Bewegungen;Movement;4;Ruch
die Bewunderung;die Bewunderung;Admiration;4;Podziw
die Beziehung;die Beziehungen;Relation;4;Relacja
die Bibel;die Bibeln;Bible;2;Biblia
die Bibliothek;die Bibliotheken;Library;4;Biblioteka
die Biegung;die Biegungen;Bend;3;schylać się
die Biene;die Bienen;Bee;2;pszczoła
die Birke;die Birken;Birch;2;Brzozowy
die Blase;die Blasen;Bubble;2;Bańka
die Blume;die Blumen;Flower;2;kwiat
die Bluse;die Blusen;Blouse;2;bluzka
die Blüte;die Blüten;Blossom;2;Kwitnąć
die Blütenblatt;die Blütenblätter;Petal;4;Płatek kwiatu
die Bogen;die Bögen;Arc;2;Łuk
die Bohne;die Bohnen;Bean;2;fasola
die Bombe;die Bomben;Bomb;2;Bomba
die Botschaft;die Botschaften;Embassy;4;Ambasada
die Brandung;die Brandungen;Surf;4;Surfować
die Braut;die Bräute;Bride;2;Panna młoda
die Bremse;die Bremsen;Brake;3;hamulec
die Briefmarke;die Briefmarken;Stamp;4;znaczek pocztowy
die Brust;die Brüste;Breast;2;pierś
die Brücke;die Brücken;Bridge;3;mostpod mostem
die Bucht;die Buchten;Bay;2;Zatoka
die Bäckerei;die Bäckereien;Bakery;4;piekarnia
die Böen;die Böen;Gust;1;Poryw
die Chemische;die Chemikalien;Chemical;4;Chemiczny
die Creme;die Cremes;Cream;2;Krem
die Dach;die Dächer;Rooftop;1;Dachu
die Dame;die Damen;Lady;1;Dama
die Dankbarkeit;die Danksagungen;Gratitude;4;Wdzięczność
die Danksagung;die Danksagungen;Thanksgiving;4;święto Dziękczynienia
die Datei;die Dateien;File;2;Plik
die Daten;die Daten;Data;2;Dane
die Debatte;die Debatten;Debate;3;Debata
die Decke;die Decken;Ceiling;2;sufit
die Dichtung;die Dichtungen;Seal;4;Foka
die Diskussion;die Diskussionen;Discussion;4;Dyskusja
die Disziplin;die Disziplinen;Discipline;4;Dyscyplina
die Diät;die Diäten;Diet;1;Dieta
die Dose;die Dosen;Can;1;Mogą
die Dosis;die Dosen;Dose;2;Dawka
die Dringlichkeit;die Dringlichkeiten;Urgency;4;Pilna sprawa
die Druck;die Drucke;Print;2;Wydrukować
die Dunkelheit;die Dunkelheiten;Dark;4;Ciemny
die Dusche;die Duschen;Shower;3;Kabina prysznicowa
die Dämmerung;die Dämmerungen;Dusk;4;Zmierzch
die Düne;die Dünen;Dune;1;Wydma
die Ebene;die Ebenen;Plain;2;Zwykły
die Ecke;die Ecken;Corner;1;kąt
die Ehe;die Ehen;Marriage;1;Małżeństwo
die Ehefrau;die Ehefrauen;Wife;3;żona
die Ehre;die Ehre;Honor;1;Zaszczyt
die Eiche;die Eichen;Oak;2;dąb
die Eidechse;die Eidechsen;Lizard;4;Jaszczurka
die Eifersucht;die Eifersucht;Jealousy;4;Zazdrość
die Eigenschaft;die Eigenschaften;Property;4;Nieruchomość
die Eile;die Eilt;Hurry;1;Spieszyć się
die Eingeweide;die Eingeweide;Gut;4;Jelito
die Einheit;die Einheiten;Unit;3;Jednostka
die Einkaufshalle;die Einkaufszentren;Mall;4;Centrum handlowe
die Einladung;die Einladungen;Invitation;4;Zaproszenie
die Einleitung;die Einleitungen;Introduction;4;Wstęp
die Einrichtung;die Einrichtungen;Facility;4;placówka
die Einsamkeit;die Einsamkeiten;Loneliness;4;Samotność
die Einsicht;die Einsichten;Insight;4;Wgląd
die Einsparung;die Einsparungen;Saving;4;Oszczędność
die Einstellung;die Einstellungen;Setting;4;Ustawienie
die Eisenbahn;die Eisenbahnen;Railroad;4;Popędzać
die Eitelkeit;die Eitelkeiten;Vanity;4;próżność
die Email;die EMails;EMail;2;E-mail
die Energie;die Energien;Energy;3;Energia
die Enkelin;die Enkel;Granddaughter;3;Wnuczka
die Ente;die Ente;Duck;1;kaczka
die Entscheidung;die Entscheidungen;Decision;4;Decyzja
die Entschuldigung;die Entschuldigung;Apology;4;Przeprosiny
die Enttäuschung;die Enttäuschungen;Disappointment;4;Rozczarowanie
die Entwicklung;die Entwicklungen;Development;4;Rozwój
die Erbse;die Erbsen;Pea;2;groszek
die Erdbeere;die Erdbeeren;Strawberry;4;truskawka
die Erde;die Erden;Earth;1;planeta ziemia
die Erdnuss;die Erdnüsse;Peanut;3;Arachid
die Erinnerung;die Erinnerungen;Reminder;4;Przypomnienie
die Erklärung;die Erklärungen;Explanation;4;Wyjaśnienie
die Erlaubnis;die Erlaubnisse;Permission;4;Pozwolenie
die Ernte;die Ernte;Crop;2;Przyciąć
die Erscheinung;die Erscheinungen;Appearance;4;Wygląd zewnętrzny
die Erschöpfung;die Erschöpfungs;Exhaustion;4;Wyczerpanie
die Erwartung;die Erwartungen;Expectation;4;Oczekiwanie
die Erwähnung;die Erwähnungen;Mention;4;Wzmianka
die Essenz;die Essenzen;Essence;3;Istota
die Eule;die Eulen;Owl;1;Sowa
die Ewigkeit;die Ewigkeit;Eternity;4;Wieczność
die Existenz;die Existenzen;Existence;4;Istnienie
die Fabrik;die Fabriken;Factory;3;fabryka
die Fackel;die Fackeln;Torch;3;Pochodnia
die Fahrt;die Fahrten;Ride;2;Jeździć
die Fakultät;die Fakultäten;Faculty;4;Wydział
die Falle;die Fallen;Trap;2;Pułapka
die Falte;die Falten;Fold;2;Zginać
die Falten;die Falten;Wrinkle;3;Zmarszczka
die Familie;die Familien;Family;3;rodzina
die Farbe;die Farben;Color;2;kolor
die Faust;die Fäuste;Fist;2;Pięść
die Feder;die Federn;Feather;2;Pióro
die Fee;die Feen;Fairy;1;Wróżka
die Ferse;die Fersen;Heel;2;Obcas
die Festung;die Forts;Fort;3;Fort
die Figur;die Figuren;Figure;2;figura
die Fiktion;die Fiktionen;Fiction;3;Fikcja
die Firma;die Firmen;Firm;2;Solidny
die Flagge;die Fahnen;Flag;3;Flaga
die Flamme;die Flammen;Flame;3;Płomień
die Flasche;die Flaschen;Bottle;3;butelka
die Fledermaus;die Fledermäuse;Bat;4;Nietoperz
die Fliese;die Fliesen;Tile;3;Płytka
die Flocke;die Flocken;Flake;3;Płatek
die Flotte;die Flotten;Liquor;3;Trunek
die Flucht;die Fluchten;Escape;3;Ucieczka
die Flug;die Flusen;Flying;1;Latający
die Flöte;die Flöten;Flute;2;flet prosty
die Flüssigkeit;die Flüssigkeiten;Liquid;4;Płyn
die Forelle;die Forellen;Trout;3;Pstrąg
die Form;die Formen;Shape;1;kształt
die Forschung;die Forschungen;Research;4;Badania
die Fotze;die Fotzen;Pussy;2;Kiciuś
die Frage;die Fragen;Question;2;Pytanie
die Fraktion;die Fraktionen;Fraction;4;Frakcja
die Fransen;die Fransen;Fringe;3;Grzywka
die Franzosen;die Frenches;French;4;Francuski
die Freiheit;die Freiheiten;Freedom;4;Wolność
die Freiwillige;die Freiwilligen;Volunteer;4;Wolontariusz
die Freude;die Freuden;Pleasure;3;radość
die Freundlichkeit;die Freundlichkeiten;Kindness;4;Życzliwość
die Freundschaft;die Freundschaften;Friendship;4;Przyjaźń
die Funktion;die Funktionen;Function;4;Funkcjonować
die Fähre;die Fähren;Ferry;2;Prom
die Gabel;die Gabeln;Fork;2;widelec
die Galaxie;die Galaxien;Galaxy;3;Galaktyka
die Gallerie;die Galerien;Gallery;4;Galeria
die Gans;die Gänse;Goose;1;gęś
die Gasse;die Gassen;Alley;2;Aleja
die Geburt;die Geburten;Birth;3;Narodziny
die Gebühr;die Gebühren;Fee;3;Opłata
die Gefahr;die Gefahren;Danger;3;niebezpieczeństwo
die Gegensprechanlage;die Gegensprechanlagen;Intercom;4;Awiofon
die Geisel;die Geiseln;Hostage;3;Zakładnik
die Gemeinde;die Gemeinden;Community;4;Społeczność
die Geschichte;die Geschichten;Story;4;Fabuła
die Geschwindigkeit;die Geschwindigkeiten;Speed;4;Prędkość
die Geschwister;die Geschwister;Sibling;4;Rodzeństwo
die Gesellschaft;die Gesellschaften;Society;4;społeczeństwo
die Geste;die Gesten;Gesture;2;Gest
die Gewalt;die Gewalten;Violence;3;Przemoc
die Gewissheit;die Gewissheiten;Certainty;4;Pewność
die Gezeiten;die Gezeiten;Tide;4;pływy
die Gitarre;die Gitarren;Guitar;3;Gitara
die Glocke;die Glocken;Bell;3;dzwon
die Gnade;die Gnaden;Grace;2;łaska
die Grenze;die Grenzen;Border;3;Granica
die Grille;die Grillen;Cricket;3;Krykiet
die Großeltern;die Großeltern;Grandparent;4;Dziadkowie
die Großmutter;die Großmütter;Grandmother;4;Babcia
die Grube;die Gruben;Pit;2;Dół
die Grundlage;die Grundlagen;Foundation;4;Fundacja
die Gruppe;die Gruppen;Group;3;Grupa
die Größe;die Größen;Size;2;Rozmiar
die Gummi;die Gummis;Gum;2;Guma
die Gunst;die Gunst;Favor;2;Przysługa
die Halle;die Hallen;Hall;2;hala
die Halskette;die Halsketten;Necklace;4;Naszyjnik
die Haltung;die Haltungen;Posture;3;Postawa
die Handvoll;die Hände Voll;Handful;4;Garść
die Hang;die Hänge;Hillside;1;Stok
die Harmonie;die Harmonien;Harmony;4;Harmonia
die Haube;die Hauben;Hood;2;kaptur
die Haupt;die Haupte;Main;2;Główny
die Hausaufgabe;die Hausaufgaben;Homework;4;Zadanie domowe
die Haut;die Häute;Skin;1;skóra
die Hecke;die Hecken;Hedge;2;Żywopłot
die Heilung;die Heilungen;Cure;3;Leczyć
die Henne;die Hennen;Hen;2;Kura
die Herausforderung;die Herausforderungen;Challenge;4;Wyzwanie
die Herde;die Herden;Herd;2;Stado
die Herrlichkeit;die Herrlichkeiten;Glory;4;Chwała
die Hexe;die Hexen;Witch;1;Czarownica
die Hilfe;die Hilft;Help;2;pomoc
die Hitze;die Heats;Heat;2;gorąco
die Hochzeit;die Hochzeiten;Wedding;4;wesele
die Hoffnung;die Hoffnungen;Hope;4;Mieć nadzieję
die Hose;die Hose;Pant;1;spodnie
die Hure;die Huren;Whore;1;Kurwa
die Hälfte;die Hälften;Half;3;Połowa
die Höflichkeit;die Höflichkeiten;Courtesy;4;Kurtuazja
die Höhe;die Höhen;Height;1;Wzrost, wysokośc
die Höhle;die Höhlen;Cave;2;Jaskinia
die Hölle;die Höllen;Hell;2;Piekło
die Hüfte;die Hüften;Hip;2;Biodro
die Hütte;die Hütten;Hut;2;Chata
die Idee;die Ideen;Idea;1;Pomysł
die Identität;die Identitäten;Identity;4;Tożsamość
die Indische;die Indianer;Indian;4;indyjski
die Insel;die Inseln;Island;2;wyspa
die Inspektion;die Inspektionen;Inspection;4;Kontrola
die Intelligenz;die Intelligenzen;Intelligence;4;Inteligencja
die Intensität;die Intensitäten;Intensity;4;Intensywność
die Interesse;die Interessen;Interest;4;Zainteresowanie
die Intimität;die Intimitäten;Intimacy;4;Intymność
die Investition;die Investitionen;Investment;4;Inwestycja
die Ironie;die Ironien;Irony;3;Ironia
die Italienische;die Italiener;Italian;4;Włoski
die Jacke;die Jacken;Jacket;2;kurtka
die Jagd;die Jagden;Hunt;1;Polowanie
die Jahreszeit;die Jahreszeiten;Season;4;Pora roku
die Japaner;die Japaneses;Japanese;3;język japoński
die Jungfrau;die Jungfrauen;Virgin;4;dziewica
die Kajüte;die Kabinen;Cabin;3;Kabina
die Kamera;die Kameras;Camera;3;Kamera
die Kammer;die Kammern;Chamber;3;Izba
die Kampagne;die Kampagnen;Campaign;4;Kampania
die Kanone;die Kanonen;Cannon;3;Armata
die Kapazität;die Kapazität;Capacity;4;Pojemność
die Kapelle;die Kapellen;Chapel;3;Kaplica
die Kappe;die Kappen;Cap;2;Czapka
die Karikatur;die Karikaturen;Cartoon;4;Kreskówka
die Karotte;die Karotten;Carrot;3;Marchewka
die Karriere;die Karrieren;Career;4;Kariera zawodowa
die Karte;die Karten;Card;2;karta
die Kartoffel;die Kartoffeln;Potato;4;ziemniak
die Kathedrale;die Kathedralen;Cathedral;4;katedra
die Katze;die Katzen;Cat;2;kot
die Kerze;die Kerzen;Candle;2;świeca
die Kette;die Ketten;Chain;2;Łańcuch
die Kiefer;die Kiefern;Pine;3;sosna
die Kindheit;die Kindheit;Childhood;4;Dzieciństwo
die Kirche;die Kirchen;Church;3;kościół
die Kirsche;die Kirschen;Cherry;3;wiśnia
die Kiste;die Kisten;Crate;2;Skrzynia
die Klappe;die Klappen;Flap;3;Klapka
die Klarheit;die Klarheiten;Clarity;4;Przejrzystość
die Klasse;die Klassen;Class;3;Klasa
die Klassenkameraden;die Klassenkameraden;Classmate;4;Kolega z klasy
die Klaue;die Krallen;Claw;2;Pazur
die Klinge;die Klingen;Blade;3;Ostrze
die Klinik;die Kliniken;Clinic;3;Klinika
die Klippe;die Klippen;Cliff;3;Klif
die Knospe;die Knospen;Bud;3;Pączek
die Kohlen;die Kohlen;Coal;3;Węgiel
die Kolonie;die Kolonien;Colony;3;Kolonia
die Kommission;die Kommissionen;Commission;4;zamawiać
die Kommode;die Kommoden;Dresser;3;Kredens
die Kommunikation;die Kommunikations;Communication;4;Komunikacja
die Konferenz;die Konferenzen;Conference;4;Konferencja
die Konsequenz;die Konsequenzen;Consequence;4;Konsekwencja
die Konsole;die Konsolen;Console;3;Konsola
die Konstruktion;die Konstruktionen;Construction;4;Budowa
die Konvention;die Konventionen;Convention;4;Konwencja
die Konzentration;die Konzentrationen;Concentration;4;Stężenie
die Kopfhaut;die Kopfhaut;Scalp;4;Oskalpować
die Kopie;die Kopien;Copy;2;Kopiuj
die Kosten;die Kosten;Cost;3;Koszt
die Krabbe;die Krabben;Crab;3;Krab
die Kraft;die Kräfte;Force;2;Zmuszać
die Kraftstoff;die Kraftstoffe;Fuel;4;Paliwo
die Krankenschwester;die Krankenschwestern;Nurse;4;pielęgniarka
die Krankheit;die Krankheiten;Sickness;4;choroba
die Kratz;die Kratzer;Scratch;2;Zadrapanie
die Kreation;die Kreationen;Creation;4;kreacja
die Krippe;die Krippen;Crib;3;Kołyska
die Krise;die Krisen;Crisis;2;Kryzys
die Krone;die Kronen;Crown;2;korona
die Krume;die Krümel;Crumb;2;Miękisz
die Kruste;die Krusten;Crust;3;Skorupa
die Krähe;die Krähen;Crow;2;Wrona
die Kugel;die Kugeln;Bullet;2;Pocisk
die Kuh;die Kühe;Cow;1;krowa
die Kultur;die Kulturen;Culture;3;Kultura
die Kunst;die Künste;Art;2;sztuka
die Kuppel;die Kuppeln;Dome;3;Kopuła
die Kurve;die Kurven;Curve;2;Krzywa
die Kämpfe;die Kämpfe;Fighting;3;Walczący
die Küche;die Küchen;Kitchen;2;kuchnia
die Küste;die Küsten;Coast;2;Wybrzeże
die Ladung;die Ladungen;loading;3;załadunek
die Lampe;die Lampen;Lamp;2;lampa
die Landschaft;die Landschaften;Landscape;4;Krajobraz
die Landung;die Landungen;Landing;3;Lądowanie
die Lanze;die Lanzen;Lance;2;Lanca
die Lappen;die Lumpen;Rag;3;Szmata
die Last;die Lasten;Burden;1;Ciężar
die Laterne;die Laternen;Lantern;3;latarnia
die Lauf;die Läufe;Run;1;Biegać
die Lebenden;die Livings;Living;4;Żyjący
die Lebensdauer;die Lebensdauern;Lifetime;4;Dożywotni
die Leber;die Lebern;Liver;2;Wątroba
die Legende;die Legenden;Legend;3;Legenda
die Leiche;die Leichen;Corpse;3;Zwłoki
die Leidenschaft;die Leidenschaften;Passion;4;Pasja
die Leine;die Leinen;Leash;2;Smycz
die Leinwand;die Leinwände;Canvas;4;Płótno
die Leiste;die Leisten;Ledge;3;Półka
die Leiter;die Leitern;Ladder;3;drabina
die Liebe;die Liebe;Love;2;miłość
die Liga;die Ligen;League;1;Liga
die Lilie;die Lilien;Lily;2;Lilia
die Limousine;die Limousinen;Limo;4;Limuzyny
die Linke;die Linke;Left;2;Lewo
die Linse;die Linsen;Lens;2;Obiektyw
die Lippe;die Lippen;Lip;2;warga
die Liste;die Listen;List;2;Lista
die Literatur;die Literaturen;Literature;4;Literatura
die Lizenz;die Lizenzen;License;3;Licencja
die Locke;die Locken;Curl;2;Kędzior
die Logik;die Logik;Logic;2;Logika
die Luft;die Lüfte;Air;1;powietrze
die Luftschleuse;die Luftschleusen;Airlock;4;Airlock.
die Luke;die Luken;Hatch;1;Właz
die Lunge;die Lungen;Lung;2;Płuco
die Länge;die Längen;Length;2;Długość
die Lösung;die Lösungen;Solution;3;Rozwiązanie
die Lücke;die Lücken;Gap;2;Luka
die Lüge;die Lügen;Lie;1;Kłamać
die Magie;die Magie;Magic;2;magia
die Majestät;die Majestäten;Majesty;4;Majestat
die Mama;die Mütter;Mom;1;Mama
die Manschette;die Manschetten;Cuff;4;Mankiet
die Marine;die Marinen;Navy;3;Marynarka wojenna
die Marke;die Marken;Brand;2;Marka
die Marmelade;die Marmeladen;Jam;4;marmolada
die Maschine;die Maschinen;Machine;4;maszyna
die Maschinen;die Maschinen;Machinery;4;Maszyneria
die Maske;die Masken;Mask;2;Maska
die Masse;die Massen;Mass;2;Masa
die Mathematik;die Mathematik;Math;4;Matematyka
die Matratze;die Matratzen;Mattress;4;Materac
die Matte;die Matten;Mat;2;Mata
die Maus;die Mäuse;Mouse;1;mysz
die Medaille;die Medaillen;Medal;4;Medal
die Medien;die Medien;Media;3;Głoska bezdźwięczna
die Melodie;die Melodien;Tune;3;Melodia
die Menge;die Mengen;Crowd;2;Tłum
die Metapher;die Metaphern;Metaphor;4;Metafora
die Miete;die Mieten;Rent;2;czynsz
die Milch;die Milch;Milk;2;mleko
die Mischung;die Mischungen;Mixture;4;Mieszanina
die Mitte;die Middles;Middle;2;Środkowy
die Mitten;die Midsts;Midst;3;Środek
die Mitternachts;die Mitternächte;Midnight;4;środek nocy
die Mode;die Mode;Fashion;1;Moda
die Morgendämmerung;die Morgengrauen;Dawn;4;Świt
die Musik;die Musiken;Music;2;Muzyka
die Möbel;die Möbel;Furniture;2;Meble
die Möglichkeit;die Möglichkeiten;Possibility;4;Możliwość
die Mücke;die Mücken;Mosquito;2;komar
die Mühle;die Mühlen;Mill;2;Młyn
die Münze;die Münzen;Coin;2;Moneta
die Nachbarschaft;die Nachbarschaften;Neighborhood;4;Sąsiedztwo
die Nachricht;die Nachrichten;Message;4;Wiadomość
die Nachrichten;die Newses;News;4;wiadomości
die Nacht;die Nächte;Night;2;noc
die Nadel;die Nadeln;Needle;2;igła
die Naht;die Nähte;Seam;1;Szew
die Narbe;die Narben;Scar;2;Blizna
die Nase;die Nasen;Nose;1;nos
die Natur;die Natur;Nature;2;natura
die Neigung;die Neigungen;Affection;3;Sympatia
die Nichte;die Nichten;Niece;3;Siostrzenica
die Niederlage;die Niederlagen;Defeat;4;Pokonać
die Nonne;die Nonnen;Nun;2;Siostra zakonna
die Not;die Nöte;Distress;1;awarja
die Note;die Noten;Mark;1;ocena
die Notiz;die Notizen;Note;2;Notatka
die Notwendigkeit;die Notwendigkeiten;Necessity;4;Konieczność
die Oberfläche;die Oberflächen;Surface;4;Powierzchnia
die Oma;die Omas;Granny;1;Babunia
die Oper;die Opern;Opera;1;Opera
die Operation;die Operationen;Surgery;4;Chirurgia
die Organisation;die Organisationen;Organization;4;Organizacja
die Orgel;die Organe;Organ;2;Organ
die Panik;die Panik;Panic;2;Panika
die Patrouille;die Patrouillen;Patrol;4;Patrol
die Pause;die Pausen;Break;2;Przerwa
die Peitsche;die Peitschen;Whip;4;Bicz
die Periode;die Perioden;Period;3;Okres
die Perle;die Perlen;Pearl;2;Perła
die Perspektive;die Perspektiven;Perspective;4;Perspektywiczny
die Persönlichkeit;die Persönlichkeiten;Personality;4;Osobowość
die Perücke;die Perücken;Wig;3;Peruka
die Pest;die Plagen;Plague;1;Plaga
die Pfanne;die Pfannen;Pan;3;Patelnia
die Pfeife;die Pfeifen;Whistle;3;Gwizdać
die Pflanze;die Pflanzen;Plant;3;roślina
die Pflaume;die Pflaumen;Plum;3;śliwka
die Pfote;die Pfoten;Paw;2;Łapa
die Pfütze;die Pfützen;Puddle;3;Kałuża
die Philosophie;die Philosophien;Philosophy;4;Filozofia
die Pille;die Pillen;Pill;2;Pigułka
die Piste;die Pisten;Slope;2;Nachylenie
die Pistole;die Pistolen;Pistol;3;Pistolet
die Platte;die Paneele;Panel;3;Płyta
die Polizei;die Politiken;Police;3;Policja
die Postkarte;die Postkarten;Postcard;4;kart
die Presse;die Pressen;Press;3;naciskać
die Probe;die Proben;Specimen;2;Próbka
die Produktion;die Produktionen;Production;4;Produkcja
die Prozession;die Prozessionen;Procession;4;Procesja
die Prärie;die Prärien;Prairie;3;Preria
die Prüfung;die Prüfungen;Exam;3;Egzamin
die Pumpe;die Pumpen;Pump;2;Pompa
die Puppe;die Puppen;Doll;2;Lalka
die Pyramide;die Pyramiden;Pyramid;4;Piramida
die Qual;die Qualen;Agony;1;Agonia
die Qualität;die Qualitäten;Quality;4;Jakość
die Quelle;die Quellen;Source;3;Źródło
die Rache;die Rache;Revenge;2;Zemsta
die Rakete;die Raketen;Rocket;3;Rakieta
die Rampe;die Rampen;Ramp;2;Rampa
die Rast;die Reste;Rest;1;Odpoczynek
die Ratte;die Ratten;Rat;2;Szczur
die Raum;die Räume;Room;1;Pokój
die Reaktion;die Reaktionen;Reaction;4;Reakcja
die Rechnung;die Rechnungen;Bill;4;rachunek
die Rede;die Reden;Speech;1;Przemówienie
die Reflexion;die Reflexionen;Reflection;4;Odbicie
die Regel;die Regeln;Rule;2;Reguła
die Regierung;die Regierungen;Government;4;Rząd kraju
die Reichweite;die Reichweiten;Reach;4;Osiągać
die Reihe;die Reihen;Row;2;rząd czegoś
die Reinigung;die Reinigungen;Cleaning;4;Czyszczenie
die Reise;die Reisen;Journey;2;podróż
die Reparatur;die Reparaturen;Repair;4;Naprawic
die Republik;die Republiken;Republic;4;Republika
die Reservierung;die Reservierungen;Reservation;4;Rezerwacja
die Residenz;die Residenzen;Residence;4;Rezydencja
die Rettung;die Rettungen;Rescue;3;Ratunek
die Richtung;die Richtungen;Direction;4;kierunek
die Rinde;die Rinden;Bark;2;Szczekać
die Rippe;die Rippen;Rib;2;Żebro
die Rolle;die Rollen;Role;2;Rola
die Romantik;die Romane;Romance;4;Romans
die Ruine;die Ruinen;Ruin;2;Ruina
die Runde;die Runden;Round;2;Okrągły
die Runden;die Runden;Lap;3;Okrążenie
die Römisch;die Römer;Roman;3;rzymski
die Rückkehr;die Renditen;Return;4;Powrót
die Rüstung;die Rüstungen;Armor;3;Zbroja
die Saat;die Samen;Seed;1;Nasionko
die Sammlung;die Sammlungen;Collection;4;Kolekcja
die Sandale;die Sandalen;Sandal;3;Sandał
die Sauerstoff;die Sauerstoffe;Oxygen;4;Tlen
die Schale;die Schalen;Bowl;3;salaterka
die Schaltung;die Schaltungen;Circuit;4;obwód elektryczny
die Schande;die Schande;Shame;3;Wstyd
die Schattierung;die Schatten;Shade;4;odcień
die Schaufel;die Schaufeln;Shovel;4;Łopata
die Schaukel;die Schaukeln;Swing;4;Huśtać się
die Scheibe;die Scheiben;Slice;3;Plasterek
die Scheidung;die Scheidungen;Divorce;4;Rozwód
die Scheiße;die Scheiße;Shit;3;Gówno
die Scherbe;die Scherben;Shard;3;Czerep
die Schere;die Scheren;Scissors;3;nożyce
die Scheune;die Scheunen;Barn;3;Stodoła
die Schicht;die Schichten;Layer;3;Warstwa
die Schiene;die Schienen;Rail;3;Szyna
die Schildkröte;die Schildkröten;Turtle;4;żółw
die Schlagzeile;die Schlagzeilen;Headline;4;Nagłówek
die Schlange;die Schlangen;Snake;4;wąż
die Schleife;die Schlaufen;Loop;4;Pętla
die Schlucht;die Schluchten;Canyon;4;Kanion
die Schnur;die Schnüre;String;3;Strunowy
die Schrotflinte;die Schrotflinten;Shotgun;4;Strzelba
die Schublade;die Schubladen;Drawer;4;szuflada
die Schuld;die Schulden;Guilt;3;Wina
die Schule;die Schulen;School;3;szkołaszkoła
die Schulter;die Schultern;Shoulder;4;ramię
die Schwalbe;die Schwalben;Swallow;4;Jaskółka
die Schwangerschaft;die Schwangerschaften;Pregnancy;4;Ciąża
die Schwarze;die Schwarzen;Black;4;Czarny
die Schwester;die Schwestern;Sister;4;siostra
die Schwierigkeit;die Schwierigkeiten;Difficulty;4;trudność
die Schwäche;die Schwächen;Weakness;4;Słabość
die Schwärze;die Schwärzen;Blackness;4;Czerń
die Schönheit;die Schönheiten;Beauty;4;Piękno
die Schürze;die Schürzen;Apron;3;Fartuch
die Seele;die Seelen;Soul;2;Dusza
die Sehenswürdigkeit;die Sehenswürdigkeiten;Sight;4;Wzrok
die Sehnsucht;die Sehnsüchte;Longing;4;Tęsknota
die Seide;die Seide;Silk;2;Jedwab
die Seife;die Seifen;Soap;2;mydło
die Seite;die Seiten;Side;2;strona
die Seitenleiste;die Seitenleisten;Sidebar;4;Pasek boczny
die Selbstmord;die Selbstmorde;Suicide;4;Samobójstwo
die Sequenz;die Sequenzen;Sequence;3;Sekwencja
die Serviette;die Servietten;Napkin;4;serwetka
die Sicherheit;die Sicherheiten;Safety;4;Bezpieczeństwo
die Sicherungs;die Sicherungen;Backup;4;Kopia zapasowa
die Siedlung;die Siedlungen;Settlement;4;Osada
die Silbe;die Silben;Syllable;2;Sylaba
die Sirene;die Sirenen;Siren;3;Syrena
die Sitzung;die Sitzungen;Session;3;Sesja
die Skizze;die Skizzen;Sketch;3;Naszkicować
die Skulptur;die Skulpturen;Sculpture;4;Rzeźba
die Socke;die Socken;Sock;2;Skarpetka
die Sonne;die Sonnen;Sun;2;słońce
die Sonnenbrille;die Sunglasseses;Sunglasses;4;Okulary słoneczne
die Sorge;die Sorgen;Worry;2;Martwić się
die Spannung;die Spannungen;Tension;4;Napięcie
die Spinne;die Spinnen;Spider;3;Pająk
die Spitze;die Spitzen;Top;3;Szczyt
die Sprache;die Sprachen;Language;3;język, mowa
die Spur;die Spuren;Trace;1;Namierzać
die Stadt;die Städte;City;2;miasto
die Stange;die Stäbe;Rod;3;Pręt
die Stille;die Stillen;Silence;3;Cisza
die Stimme;die Stimmen;Voice;3;Głos
die Stimmung;die Stimmungen;Mood;4;Nastrój
die Stirn;die Stirn;Forehead;2;Czoło
die Strafe;die Strafen;Punishment;3;Kara
die Straftat;die Straftaten;Offense;4;Wykroczenie
die Strahlung;die Strahlungen;Radiation;4;Promieniowanie
die Strategie;die Strategien;Strategy;4;Strategia
die Straße;die Straßen;Street;3;ulica
die Strecke;die Spuren;Track;3;odcinek
die Struktur;die Strukturen;Structure;4;Struktura
die Strömung;die Ströme;Flow;4;Pływ
die Stunde;die Stunden;Hour;3;godzina
die Stute;die Stuten;Mare;2;Klacz
die Stärke;die Stärken;Strength;3;Wytrzymałość
die Substanz;die Substanzen;Substance;4;Substancja
die Suche;die Suche;Search;2;Szukaj
die Summe;die Summen;Sum;2;Suma
die Suppe;die Suppen;Soup;2;zupa
die Sympathie;die Sympathien;Sympathy;4;Współczucie
die Szene;die Szenen;Scene;2;Scena
die Säge;die Sägen;Saw;1;Piła
die Säulen;die Säulen;Pillar;3;Filar
die Säure;die Säuren;Acid;2;Kwas
die Sünde;die Sünden;Sin;2;grzech
die Süße;die Süßen;Sweet;1;Słodki
die Tabak;die Tabake;Tobacco;2;Tytoń
die Taille;die Taille;Waist;3;Talia
die Tante;die Tanten;Aunt;2;ciocia
die Tasche;die Taschen;Pocket;3;torba
die Taschenlampe;die Taschenlampen;Flashlight;4;Latarka
die Tasse;die Tassen;Cup;2;filiżanka
die Tat;die Taten;Deed;1;Czyn
die Taube;die Tauben;Pigeon;2;Gołąb
die Taverne;die Tavernen;Tavern;3;Tawerna
die Technik;die Techniken;Technique;3;Technika
die Temperatur;die Temperaturen;Temperature;4;Temperatura
die Tentakel;die Tentakeln;Tentacle;4;Macka
die Terrasse;die Terrassen;Terrace;4;Taras
die Theorie;die Theorien;Theory;3;Teoria
die Therapie;die Therapie;Therapy;4;Terapia
die Tiefe;die Tiefen;Depth;2;Głębokość
die Tinten;die Tinten;Ink;3;Atrament
die Tochter;die Töchter;Daughter;3;córka
die Toilette;die Toiletten;Toilet;4;toaleta
die Tomate;die Tomaten;Tomato;3;pomidor
die Tragödie;die Tragödien;Tragedy;4;Tragedia
die Traube;die Trauben;Grape;3;Winogrono
die Traufe;die Traufe;Eave;3;Okapować
die Traurigkeit;die Traurigkeiten;Sadness;4;Smutek
die Treppen;die Treppe;Stair;3;Schodek
die Trommel;die Trommeln;Drum;3;Bęben
die Truppe;die Truppen;Troop;3;trupa
die Trübung;die Trübungen;Haze;3;zakłócenie
die Trümmer;die Trümmern;Rubble;3;Gruz
die Tugend;die Tugenden;Virtue;3;Cnota
die Tunika;die Tuniken;Tunic;3;Tunika
die Tänzerin;die Tänzer;Dancer;4;Tancerz
die Tätowierung;die Tattoos;Tattoo;4;Tatuaż
die Tür;die Türen;Door;1;drzwi
die Türklingel;die Türklingeln;Doorbell;4;Dzwonek do drzwi
die Türöffnung;die Türen;Doorway;4;ościeże drzwiowe
die UBahn;die UBahnen;Subway;2;Metro
die Uhr;die Uhren;Watch;1;zegarek
die Umarmung;die Umarmungen;Hug;4;Przytulać
die Umgebung;die Umgebungen;Environment;4;Środowisko
die Unabhängigkeit;die Unabhängigkeiten;Independence;4;Niezależność
die Universität;die Universitäten;University;4;Uniwersytet
die Unschärfe;die Unschärfen;Blur;4;rozmycie
die Unterhaltung;die Unterhaltungen;Entertainment;4;Zabawa
die Unterschrift;die Unterschriften;Signature;4;Podpis
die Untersuchung;die Untersuchungen;Examination;4;Badanie
die Untertasse;die Untertassen;Saucer;4;Spodek
die Unterwäsche;die Unterwäsche;Underwear;4;bielizna
die Unwissenheit;die Unwissenheit;Ignorance;4;Ignorancja
die Vene;die Venen;Vein;1;Żyła
die Verbindung;die Verbindungen;Connection;4;związek
die Verbrennung;die Verbrennungen;Burn;4;Oparzenie
die Vereinbarung;die Vereinbarungen;Arrangement;4;Układ
die Vergangenheit;die Vergangenheit;Past;4;przeszłość
die Verletzung;die Verletzungen;Injury;4;Obrażenia
die Vermietung;die Vermietungen;Rental;4;Wynajem
die Vermutung;die Vermutungen;Guess;4;Odgadnąć
die Verpflichtung;die Verpflichtungen;Obligation;4;Obowiązek
die Verrücktheit;die Verrücktheiten;Madness;4;Szaleństwo
die Versammlung;die Versammlungen;Gathering;4;Zgromadzenie
die Verschiebung;die Verschiebungen;Shift;4;Zmiana
die Versicherung;die Versicherungen;Insurance;4;Ubezpieczenie
die Verwaltung;die Verwaltungen;Administration;4;Administracja
die Verwendung;die Verwendungen;Use;4;Posługiwać się
die Verwirrung;die Verwirrungen;Confusion;4;Dezorientacja
die Verzweiflung;die Verzweiflungen;Despair;4;Rozpacz
die Verzögerung;die Verzögerungen;Delay;4;Opóźnienie
die Vorbereitung;die Vorbereitungen;Preparation;4;Przygotowanie
die Vorhalle;die Veranden;Porch;4;Ganek
die Waffe;die Waffen;Gun;2;broń
die Wahl;die Wahlen;Election;1;Wybór
die Wahrheit;die Wahrheiten;Truth;4;Prawda
die Wahrnehmung;die Wahrnehmungen;Perception;4;Postrzeganie
die Waise;die Waisen;Orphan;2;Sierota
die Wange;die Wangen;Cheek;2;policzek
die Wangenknochen;die Wangenknochen;Cheekbone;4;Kość policzkowa
die Wanne;die Wannen;Tub;2;Wanna
die Warnung;die Warnungen;Warning;3;Ostrzeżenie
die Wartung;die Wartungen;Maintenance;3;Utrzymanie
die Wasch;die Wasch;Wash;2;Myć się
die Weide;die Weiden;Pasture;2;Pastwisko
die Weisheit;die Weisheiten;Wisdom;4;Mądrość
die Weite;die Weiten;width;2;szerokość
die Welle;die Wellen;Wave;2;Fala
die Welligkeit;die Wellen;Ripple;4;Marszczyć
die Welt;die Welt;World;1;świat
die Wende;die Wenden;Turn;2;Zakręt
die Weste;die Westen;Vest;2;Kamizelka
die Wette;die Wetten;Bet;2;zakład
die Wichtigkeit;die Wichtigkeiten;Importance;4;Znaczenie
die Wiege;die Wiegen;Cradle;2;Kolebka
die Wiese;die Wiesen;Meadow;2;łąka
die Wildnis;die Wildnis;Wilderness;3;dźicz
die Windel;die Windeln;Diaper;3;Pielucha
die Windschutzscheibe;die Windschutzscheiben;Windshield;4;Przednia szyba
die Wissenschaft;die Wissenschaften;Science;4;nauka
die Witwe;die Witwen;Widow;2;Wdowa
die Woche;die Wochen;Week;2;tydzień
die Wohnung;die Wohnungen;Apartment;3;mieszkanie
die Wolke;die Wolken;Cloud;2;chmura
die Wolle;die Wolle;Wool;2;wełna
die Wunde;die Wunden;Wound;2;Rana
die Wurst;die Würste;Sausage;2;kiełbasa
die Wut;die Wütet;Rage;1;Wściekłość
die Wärme;die Wärmen;Warmth;2;Ciepło
die Wäsche;die Wäsche;Laundry;3;Pranie
die Wüste;die Wüsten;Desert;2;pustynia
die Zahlung;die Zahlungen;Pay;3;Płacić
die Zeder;die Zedern;Cedar;2;Cedr
die Zehe;die Zehen;Toe;1;palec u nogi
die Zeichnung;die Zeichnungen;Drawing;4;rysunek
die Zeit;die Zeiten;Time;1;czas
die Zeitung;die Zeitung;Newspaper;3;gazeta
die Zelle;die Zellen;Cell;2;Komórka
die Zeremonie;die Zeremonien;Ceremony;4;Ceremonia
die Zerstörung;die Zerstörungen;Destruction;4;Zniszczenie
die Ziege;die Ziegen;Goat;2;Koza
die Ziegel;die Ziegel;Brick;3;Cegła
die Zigarette;die Zigaretten;Cigarette;4;papieros
die Zigarre;die Zigarren;Cigar;3;Cygaro
die Zitrone;die Zitronen;Lemon;3;cytryna
die Zivilisation;die Zivilisationen;Civilization;4;Cywilizacja
die Zufriedenheit;die Zufriedenheiten;Satisfaction;4;Zadowolenie
die Zugehörigkeit;die Zugehörigkeiten;Affiliation;4;Przynależność
die Zugriffs;die Zugriffe;Access;4;Dostęp
die Zukunft;die Zukunfte;Future;3;przyszłość
die Zulassung;die Zulassungen;Approval;4;Aprobata
die Zunge;die Zungen;Tongue;2;język
die Zuordnung;die Zuordnungen;Assignment;4;przydzielone zadanie
die Zuzwinkern;die Zwinkert;Wink;4;Puścić oczko
die Zwiebel;die Zwiebeln;Onion;3;cebula
die Zwischenzeit;die Zwischenzeiten;Meantime;4;W międzyczasie
die Öffentlichkeit;die Öffentlichkeit;Public;4;Publiczny
die Überlebens;die Überreste;Survival;4;Przetrwanie
die Überlegung;die Überlegungen;Consideration;4;Namysł
die Überraschung;die Überraschungen;Surprise;4;Niespodzianka
die Übersetzung;die Übersetzungen;Translation;4;Tłumaczenie
die Übertragungs;die Übertragungen;Transmission;4;Przenoszenie
die Überzeugung;die Überzeugungen;Conviction;4;Przekonanie
die Übung;die Übungen;Exercise;2;Ćwiczenie`;
